---
title: Linking Freshchat as a source
sidebar: Docs
showTitle: true
availability:
  free: full
  selfServe: full
  enterprise: full
sourceId: Freshchat
---

import SourceSetupIntro from "../_snippets/source-setup-intro.mdx"
import SyncModes from "../_snippets/sync-modes.mdx"
import TroubleshootingLink from "../_snippets/dw-troubleshooting-link.mdx"
import AlphaRelease from "../_snippets/alpha-release.mdx"

<AlphaRelease />

The Freshchat connector syncs agents, users, groups, and more into the PostHog data warehouse, so you can analyze them alongside your product data.

## Prerequisites

Credentials that can read the data you want to sync. PostHog only reads data, so read access is enough.

## Adding a data source

<SourceSetupIntro />

Enter your Freshchat account domain and API token to pull your Freshchat messaging data.

Your **account domain** is the host of your Freshchat account - e.g. `acme.freshchat.com`. Use the regional API host if your account lives in a specific data center (e.g. `api.eu.freshchat.com`).

Your **API token** is generated by an account admin under **Admin settings → API tokens**. It is sent as a Bearer token.

You'll be asked for:

- **Freshchat account domain**: for example `acme.freshchat.com`.
- **API token**

## Sync modes

<SyncModes />

All Freshchat tables are full refresh. Each sync replaces the contents of the table.

## Configuration

<SourceParameters />

## Supported tables

<SourceTables />

## Troubleshooting

- If the connection fails with an authorization error, the API token is wrong, expired, or has been revoked. Create a new one, then reconnect the source.
- If a table syncs no rows, the credential may not have access to that data. Check its permissions, then reconnect the source.

<TroubleshootingLink />
