import chromium from 'chrome-aws-lambda'
import path from 'path'
import fs from 'fs'
import blogTemplate from '../src/templates/OG/blog.js'
import docsHandbookTemplate from '../src/templates/OG/docs-handbook.js'
import customerTemplate from '../src/templates/OG/customer.js'
import careersTemplate from '../src/templates/OG/careers.js'
import tutorialTemplate from '../src/templates/OG/tutorial.js'
import jobTemplate from '../src/templates/OG/job.js'
import { flattenMenu } from './utils'
import fetch from 'node-fetch'
import { GatsbyNode } from 'gatsby'
import sidebars from '../src/sidebars/index'

export const onPostBuild: GatsbyNode['onPostBuild'] = async ({ graphql }) => {}
