// Icons served from PostHog CDN — prepend 'https://us.posthog.com' at runtime.
// For integrations not listed here the component falls back to Clearbit logo API.
export const POSTHOG_CDN_ICONS: Record<string, string> = {
    ABsmartly: '/static/services/absmartly.com.png',
    Accoil: '/static/services/accoil.com.png',
    Acoustic: '/static/services/acoustic.com.png',
    ActiveCampaign: '/static/services/activecampaign.png',
    Airship: '/static/services/airship.com.png',
    Airtable: '/static/services/airtable.png',
    'Algolia Insights': '/static/services/algolia.com.png',
    'Amazon S3': '/static/services/aws-kinesis.png',
    Amplitude: '/static/services/amplitude.com.png',
    'Angler AI': '/static/services/getangler.ai.png',
    Attentive: '/static/services/attentive.com.png',
    Attio: '/static/services/attio.png',
    Avo: '/static/services/avo.png',
    'AWS Kinesis': '/static/services/aws-kinesis.png',
    BigQuery: '/static/services/bigquery.png',
    'Blend AI': '/static/services/blend.com.png',
    Braze: '/static/services/braze.png',
    Brevo: '/static/services/brevo.png',
    'Calliper Cloud': '/static/services/cloud.com.png',
    Canny: '/static/services/canny.io.png',
    Canvas: '/static/services/supernova.ai.png',
    Clearbit: '/static/services/clearbit.png',
    CleverTap: '/static/services/clevertap.com.png',
    ClickUp: '/static/services/clickup.svg',
    'Customer.io': '/static/services/customerio.png',
    Discord: '/static/services/discord.png',
    Drip: '/static/services/drip.com.png',
    Encharge: '/static/services/encharge.io.png',
    'Engage.so': '/static/services/engage.png',
    Fullstory: '/static/services/fullstory.com.png',
    Gameball: '/static/services/gameball.co.png',
    GitHub: '/static/services/github.png',
    GitLab: '/static/services/gitlab.png',
    Gleap: '/static/services/gleap.png',
    'Google Ads Conversions': '/static/services/google-ads.png',
    'Google Cloud Storage': '/static/services/google-cloud-storage.png',
    'Google Pub/Sub': '/static/services/google-cloud.png',
    HubSpot: '/static/services/hubspot.png',
    Hyperengage: '/static/services/hyperengage.io.png',
    'Inleads AI': '/static/services/inleads.ai.png',
    Insider: '/static/services/insider.com.png',
    Intercom: '/static/services/intercom.png',
    Iterable: '/static/services/iterable.com.png',
    Jira: '/static/services/jira.png',
    'June.so': '/static/services/june.png',
    Kameleoon: '/static/services/kameleoon.com.png',
    Klaviyo: '/static/services/klaviyo.png',
    Knock: '/static/services/knock.png',
    Koala: '/static/services/koala.com.png',
    'Kudosity SMS': '/static/services/kudosity.png',
    LaunchDarkly: '/static/services/launchdarkly.com.png',
    Launchpad: '/static/services/launchpad.com.png',
    Linear: '/static/services/linear.png',
    'LinkedIn Ads Conversions': '/static/services/linkedin.png',
    LiveLike: '/static/services/livelike.com.png',
    Loops: '/static/services/loops.png',
    m3ter: '/static/services/m3ter.com.png',
    Mailgun: '/static/services/mailgun.png',
    Mailjet: '/static/services/mailjet.png',
    Make: '/static/services/make.png',
    'Meta Ads Conversions': '/static/services/meta-ads.png',
    Metronome: '/static/services/metronome.com.png',
    'Microsoft Teams': '/static/services/microsoft-teams.png',
    Mixpanel: '/static/services/mixpanel.com.png',
    'Moloco MCM': '/static/services/moloco.com.png',
    MSSQL: '/static/services/sql-azure.png',
    MySQL: '/static/services/mysql.png',
    OneSignal: '/static/services/onesignal.svg',
    Optimizely: '/static/services/optimizely.com.png',
    Outfunnel: '/static/services/outfunnel.com.png',
    Pipedrive: '/static/services/pipedrive.com.png',
    'Pinterest Conversions API': '/static/services/pinterest.com.png',
    PlayerZero: '/static/services/playerzero.ai.png',
    Postgres: '/static/services/postgres.png',
    PostHog: '/static/posthog-icon.svg',
    Prodeology: '/static/services/prodeology.com.png',
    Pushwoosh: '/static/services/pushwoosh.com.png',
    Recombee: '/static/services/recombee.com.png',
    'Reddit Conversions API': '/static/services/reddit.png',
    'RevX Cloud': '/static/services/revx.io.png',
    Ripe: '/static/services/ripe.com.png',
    RudderStack: '/static/services/rudderstack.png',
    Salesforce: '/static/services/salesforce.png',
    Saleswings: '/static/services/saleswingsapp.com.png',
    Schematic: '/static/services/schematichq.com.png',
    Sendgrid: '/static/services/sendgrid.png',
    Slack: '/static/services/slack.png',
    'Snapchat Ads Conversions': '/static/services/snapchat.png',
    Snowflake: '/static/services/snowflake.png',
    Sprig: '/static/services/sprig.com.png',
    StackAdapt: '/static/services/stackadapt.com.png',
    Stripe: '/static/services/stripe.png',
    'TikTok Ads Conversions': '/static/services/tiktok.png',
    Topsort: '/static/services/topsort.com.png',
    Userlist: '/static/services/userlist.png',
    Usermaven: '/static/services/usermaven.com.png',
    UserMotion: '/static/services/usermotion.com.png',
    Userpilot: '/static/services/userpilot.com.png',
    Voucherify: '/static/services/voucherify.io.png',
    Voyage: '/static/services/voyagesms.com.png',
    VWO: '/static/services/vwo.com.png',
    Xtremepush: '/static/services/xtremepush.com.png',
    Zapier: '/static/services/zapier.png',
    Zendesk: '/static/services/zendesk.png',
    // External logos (absolute URLs — not on PostHog CDN)
    Convex: 'https://cdn.simpleicons.org/convex',
    OpenRouter: 'https://openrouter.ai/favicon.ico',
    Vercel: 'https://cdn.simpleicons.org/vercel/FFFFFF',
}

export interface Integration {
    name: string
    categories: string[]
    posthogProducts: string[]
    integrationTypes: string[]
    useCase: string
    domain: string
}

export const POSTHOG_PRODUCT_COLORS: Record<string, string> = {
    'Product Analytics': 'blue',
    CDP: 'seagreen',
    'Data Warehouse': 'purple',
    'Feature Flags': 'teal',
    Experiments: 'teal',
    'Error Tracking': 'salmon',
    'LLM Analytics': 'sky-blue',
    Workflows: 'yellow',
}

export const integrations: Integration[] = [
    {
        name: 'ABsmartly',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to ABsmartly for A/B testing analysis.',
        domain: 'absmartly.com',
    },
    {
        name: 'Accoil',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Pipe PostHog data for account scoring and churn insights.',
        domain: 'accoil.com',
    },
    {
        name: 'Acoustic',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Acoustic for marketing campaigns.',
        domain: 'acoustic.com',
    },
    {
        name: 'ActiveCampaign',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Sync user data to ActiveCampaign for marketing automation.',
        domain: 'activecampaign.com',
    },
    {
        name: 'Airship',
        categories: ['Messaging & Notifications'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Airship for push notifications.',
        domain: 'airship.com',
    },
    {
        name: 'Airtable',
        categories: ['Productivity'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Create Airtable records from PostHog event data.',
        domain: 'airtable.com',
    },
    {
        name: 'Algolia Insights',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Algolia Insights for search analytics.',
        domain: 'algolia.com',
    },
    {
        name: 'Amazon S3',
        categories: ['Data Warehousing'],
        posthogProducts: ['Data Warehouse', 'CDP'],
        integrationTypes: ['Native'],
        useCase: 'Export event data to Amazon S3 for storage, warehouse sync, and downstream processing.',
        domain: 'aws.amazon.com',
    },
    {
        name: 'Amplitude',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Mirror PostHog events to Amplitude for parallel analysis.',
        domain: 'amplitude.com',
    },
    {
        name: 'Angler AI',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Angler AI.',
        domain: 'angler.ai',
    },
    {
        name: 'Attentive',
        categories: ['Messaging & Notifications'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Attentive for SMS and email marketing.',
        domain: 'attentive.com',
    },
    {
        name: 'Attio',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Create and update contacts in Attio based on PostHog events.',
        domain: 'attio.com',
    },
    {
        name: 'Avo',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Avo for tracking plan validation.',
        domain: 'avo.app',
    },
    {
        name: 'AWS Kinesis',
        categories: ['Data Warehousing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Put PostHog event data into an AWS Kinesis stream.',
        domain: 'aws.amazon.com',
    },
    {
        name: 'BigQuery',
        categories: ['Data Warehousing'],
        posthogProducts: ['Data Warehouse'],
        integrationTypes: ['Native', 'Source'],
        useCase: 'Export PostHog events into BigQuery for analysis, or query BigQuery data within PostHog.',
        domain: 'cloud.google.com',
    },
    {
        name: 'Blend AI',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Blend AI.',
        domain: 'blendai.com',
    },
    {
        name: 'Braze',
        categories: ['Support & CX'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Braze for customer engagement.',
        domain: 'braze.com',
    },
    {
        name: 'Brevo',
        categories: ['Messaging & Notifications', 'CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Sync contacts and events to Brevo for email campaigns.',
        domain: 'brevo.com',
    },
    {
        name: 'Calliper Cloud',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Calliper Cloud.',
        domain: 'calliper.co',
    },
    {
        name: 'Canny',
        categories: ['Support & CX'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send user feedback and event data to Canny boards.',
        domain: 'canny.io',
    },
    {
        name: 'Canvas',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Canvas.',
        domain: 'canvas.com',
    },
    {
        name: 'Clearbit',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Enrich person profiles using Clearbit data.',
        domain: 'clearbit.com',
    },
    {
        name: 'CleverTap',
        categories: ['User Engagement Platforms'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to CleverTap for user engagement.',
        domain: 'clevertap.com',
    },
    {
        name: 'ClickUp',
        categories: ['Productivity'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Create ClickUp tasks from PostHog event data.',
        domain: 'clickup.com',
    },
    {
        name: 'Convex',
        categories: ['Developer Tools'],
        posthogProducts: ['Product Analytics'],
        integrationTypes: [],
        useCase: 'Track events from your Convex application in PostHog.',
        domain: 'convex.dev',
    },
    {
        name: 'Customer.io',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Identify and track customers in Customer.io based on PostHog events.',
        domain: 'customer.io',
    },
    {
        name: 'Discord',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send messages to a Discord channel based on PostHog events.',
        domain: 'discord.com',
    },
    {
        name: 'Drip',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Drip for e-commerce marketing.',
        domain: 'drip.com',
    },
    {
        name: 'Encharge',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Encharge for behavior-driven emails.',
        domain: 'encharge.io',
    },
    {
        name: 'Engage.so',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Engage.so for messaging automation.',
        domain: 'engage.so',
    },
    {
        name: 'Fullstory',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Fullstory for session analytics.',
        domain: 'fullstory.com',
    },
    {
        name: 'Gameball',
        categories: ['Support & CX'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Gameball for customer loyalty programs.',
        domain: 'gameball.co',
    },
    {
        name: 'GitHub',
        categories: ['Developer Tools'],
        posthogProducts: ['Error Tracking'],
        integrationTypes: ['Native'],
        useCase: 'Create GitHub issues directly from PostHog errors.',
        domain: 'github.com',
    },
    {
        name: 'GitLab',
        categories: ['Developer Tools'],
        posthogProducts: ['Error Tracking'],
        integrationTypes: ['Native'],
        useCase: 'Create GitLab issues directly from PostHog errors.',
        domain: 'gitlab.com',
    },
    {
        name: 'Gleap',
        categories: ['Support & CX'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Update contacts in Gleap based on PostHog events.',
        domain: 'gleap.io',
    },
    {
        name: 'Google Ads Conversions',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send conversion events to Google Ads.',
        domain: 'google.com',
    },
    {
        name: 'Google Cloud Storage',
        categories: ['Data Warehousing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Google Cloud Storage.',
        domain: 'cloud.google.com',
    },
    {
        name: 'Google Pub/Sub',
        categories: ['Data Warehousing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Stream PostHog events to Google Pub/Sub in real time.',
        domain: 'cloud.google.com',
    },
    {
        name: 'HubSpot',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Source', 'Realtime Destination'],
        useCase: 'Sync contacts and events with HubSpot for marketing automation.',
        domain: 'hubspot.com',
    },
    {
        name: 'Hyperengage',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Hyperengage.',
        domain: 'hyperengage.io',
    },
    {
        name: 'Inleads AI',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Inleads AI for lead scoring.',
        domain: 'inleads.ai',
    },
    {
        name: 'Insider',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Insider for cross-channel marketing.',
        domain: 'useinsider.com',
    },
    {
        name: 'Intercom',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send and update contacts in Intercom based on PostHog events.',
        domain: 'intercom.com',
    },
    {
        name: 'Iterable',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Iterable for lifecycle marketing.',
        domain: 'iterable.com',
    },
    {
        name: 'Jira',
        categories: ['Developer Tools'],
        posthogProducts: ['Error Tracking'],
        integrationTypes: ['Native'],
        useCase: 'Create Jira tickets directly from PostHog error events.',
        domain: 'atlassian.com',
    },
    {
        name: 'June.so',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to June.so for B2B analytics.',
        domain: 'june.so',
    },
    {
        name: 'Kameleoon',
        categories: ['Developer Tools'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Kameleoon for A/B testing.',
        domain: 'kameleoon.com',
    },
    {
        name: 'Klaviyo',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send and update contacts in Klaviyo for email and SMS marketing.',
        domain: 'klaviyo.com',
    },
    {
        name: 'Knock',
        categories: ['Messaging & Notifications'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Knock to trigger notifications.',
        domain: 'knock.app',
    },
    {
        name: 'Koala',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Koala for sales intelligence.',
        domain: 'getkoala.com',
    },
    {
        name: 'Kudosity SMS',
        categories: ['Messaging & Notifications'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send SMS alerts based on PostHog events.',
        domain: 'kudosity.com',
    },
    {
        name: 'LaunchDarkly',
        categories: ['Developer Tools'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to LaunchDarkly for feature flag analytics.',
        domain: 'launchdarkly.com',
    },
    {
        name: 'Launchpad',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Launchpad.',
        domain: 'launchpad.build',
    },
    {
        name: 'Linear',
        categories: ['Developer Tools'],
        posthogProducts: ['Error Tracking'],
        integrationTypes: ['Native'],
        useCase: 'Create Linear issues directly from PostHog errors.',
        domain: 'linear.app',
    },
    {
        name: 'LinkedIn Ads Conversions',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send conversion events to LinkedIn Ads.',
        domain: 'linkedin.com',
    },
    {
        name: 'LiveLike',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to LiveLike for fan engagement.',
        domain: 'livelike.com',
    },
    {
        name: 'Loops',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send and update contacts in Loops for SaaS email campaigns.',
        domain: 'loops.so',
    },
    {
        name: 'm3ter',
        categories: ['Payments & Billing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to m3ter for usage-based billing.',
        domain: 'm3ter.com',
    },
    {
        name: 'Mailgun',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send emails using the Mailgun API based on PostHog events.',
        domain: 'mailgun.com',
    },
    {
        name: 'Mailjet',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Add and update Mailjet contacts from PostHog events.',
        domain: 'mailjet.com',
    },
    {
        name: 'Make',
        categories: ['Productivity'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Trigger Make (formerly Integromat) scenarios via webhook.',
        domain: 'make.com',
    },
    {
        name: 'Meta Ads Conversions',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send conversion events to Meta Ads for ad optimization.',
        domain: 'meta.com',
    },
    {
        name: 'Metronome',
        categories: ['Payments & Billing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Metronome for usage-based billing.',
        domain: 'metronome.com',
    },
    {
        name: 'Microsoft Teams',
        categories: ['Productivity'],
        posthogProducts: ['Error Tracking', 'CDP'],
        integrationTypes: ['Native', 'Realtime Destination'],
        useCase: 'Send error alerts and event notifications to Microsoft Teams channels.',
        domain: 'microsoft.com',
    },
    {
        name: 'Mixpanel',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Mirror PostHog events to Mixpanel for parallel analysis.',
        domain: 'mixpanel.com',
    },
    {
        name: 'Moloco MCM',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Moloco MCM for ad monetization.',
        domain: 'moloco.com',
    },
    {
        name: 'MSSQL',
        categories: ['Data Warehousing'],
        posthogProducts: ['Data Warehouse'],
        integrationTypes: ['Native'],
        useCase: 'Query external Microsoft SQL Server data within PostHog.',
        domain: 'microsoft.com',
    },
    {
        name: 'MySQL',
        categories: ['Data Warehousing'],
        posthogProducts: ['Data Warehouse'],
        integrationTypes: ['Native', 'Source'],
        useCase: 'Query external MySQL data within PostHog.',
        domain: 'mysql.com',
    },
    {
        name: 'OneSignal',
        categories: ['Messaging & Notifications'],
        posthogProducts: ['CDP', 'Workflows'],
        integrationTypes: ['Realtime Destination', 'Via Workflows'],
        useCase:
            'Send user events to trigger push notifications in OneSignal. Conditionally send messages based on user behavior.',
        domain: 'onesignal.com',
    },
    {
        name: 'OpenRouter',
        categories: ['AI & LLM'],
        posthogProducts: ['LLM Analytics'],
        integrationTypes: ['Native'],
        useCase: 'Track LLM calls made via OpenRouter in PostHog.',
        domain: 'openrouter.ai',
    },
    {
        name: 'Optimizely',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Optimizely Data Platform for experimentation.',
        domain: 'optimizely.com',
    },
    {
        name: 'Outfunnel',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Outfunnel for sales-focused marketing.',
        domain: 'outfunnel.com',
    },
    {
        name: 'Pipedrive',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Pipedrive for CRM updates.',
        domain: 'pipedrive.com',
    },
    {
        name: 'Pinterest Conversions API',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send conversion events to Pinterest for ad optimization.',
        domain: 'pinterest.com',
    },
    {
        name: 'PlayerZero',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to PlayerZero for product monitoring.',
        domain: 'playerzero.app',
    },
    {
        name: 'Postgres',
        categories: ['Data Warehousing'],
        posthogProducts: ['Data Warehouse'],
        integrationTypes: ['Native', 'Source'],
        useCase: 'Query external Postgres data within PostHog.',
        domain: 'postgresql.org',
    },
    {
        name: 'PostHog',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send data to another PostHog instance for mirroring or staging.',
        domain: 'posthog.com',
    },
    {
        name: 'Prodeology',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Prodeology.',
        domain: 'prodeology.com',
    },
    {
        name: 'Pushwoosh',
        categories: ['Messaging & Notifications'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Pushwoosh for push notifications.',
        domain: 'pushwoosh.com',
    },
    {
        name: 'Recombee',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Recombee for AI-powered recommendations.',
        domain: 'recombee.com',
    },
    {
        name: 'Reddit Conversions API',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send conversion events to Reddit for ad optimization.',
        domain: 'reddit.com',
    },
    {
        name: 'RevX Cloud',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to RevX Cloud for retargeting.',
        domain: 'revx.io',
    },
    {
        name: 'Ripe',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Ripe for pipeline intelligence.',
        domain: 'getripe.com',
    },
    {
        name: 'RudderStack',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Native'],
        useCase: 'Send and receive event data between RudderStack and PostHog.',
        domain: 'rudderstack.com',
    },
    {
        name: 'Salesforce',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Source', 'Realtime Destination'],
        useCase: 'Sync objects and contacts with Salesforce CRM.',
        domain: 'salesforce.com',
    },
    {
        name: 'Saleswings',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Saleswings for lead scoring.',
        domain: 'saleswings.app',
    },
    {
        name: 'Schematic',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Schematic for feature entitlements.',
        domain: 'schematichq.com',
    },
    {
        name: 'Segment',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Native'],
        useCase: 'Send and receive event data between Segment and PostHog.',
        domain: 'segment.com',
    },
    {
        name: 'Sendgrid',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Update marketing contacts in Sendgrid based on PostHog events.',
        domain: 'sendgrid.com',
    },
    {
        name: 'Slack',
        categories: ['Productivity'],
        posthogProducts: ['Error Tracking', 'Workflows', 'CDP'],
        integrationTypes: ['Native', 'Via Workflows', 'Realtime Destination'],
        useCase: 'Send error alerts, trigger workflow notifications, or forward event data to Slack.',
        domain: 'slack.com',
    },
    {
        name: 'Snapchat Ads Conversions',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send conversion events to Snapchat Ads for ad optimization.',
        domain: 'snap.com',
    },
    {
        name: 'Snowflake',
        categories: ['Data Warehousing'],
        posthogProducts: ['Data Warehouse'],
        integrationTypes: ['Native', 'Source'],
        useCase: 'Export event data into Snowflake for advanced analysis, or query Snowflake data within PostHog.',
        domain: 'snowflake.com',
    },
    {
        name: 'Sprig',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Sprig for in-product surveys.',
        domain: 'sprig.com',
    },
    {
        name: 'StackAdapt',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to StackAdapt for programmatic advertising.',
        domain: 'stackadapt.com',
    },
    {
        name: 'Stripe',
        categories: ['Payments & Billing'],
        posthogProducts: ['Product Analytics'],
        integrationTypes: ['API-based', 'Source'],
        useCase: 'Track subscription and payment events in PostHog.',
        domain: 'stripe.com',
    },
    {
        name: 'TikTok Ads Conversions',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send conversion events to TikTok Ads for ad optimization.',
        domain: 'tiktok.com',
    },
    {
        name: 'Topsort',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Topsort for retail media.',
        domain: 'topsort.com',
    },
    {
        name: 'Userlist',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send user and event data to Userlist for SaaS email automation.',
        domain: 'userlist.com',
    },
    {
        name: 'Usermaven',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Usermaven for product analytics.',
        domain: 'usermaven.com',
    },
    {
        name: 'UserMotion',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to UserMotion for PLG intelligence.',
        domain: 'usermotion.com',
    },
    {
        name: 'Userpilot',
        categories: ['CRM & Marketing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Userpilot for product adoption.',
        domain: 'userpilot.com',
    },
    {
        name: 'Vercel',
        categories: ['Developer Tools', 'AI & LLM'],
        posthogProducts: ['Feature Flags', 'Experiments'],
        integrationTypes: ['Native', 'MCP'],
        useCase: 'Sync PostHog feature flags into Vercel. Run experiments defined in PostHog in a Vercel app.',
        domain: 'vercel.com',
    },
    {
        name: 'Voucherify',
        categories: ['Payments & Billing'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Voucherify for promotions and loyalty.',
        domain: 'voucherify.io',
    },
    {
        name: 'Voyage',
        categories: ['Analytics'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Voyage.',
        domain: 'voyage.ai',
    },
    {
        name: 'VWO',
        categories: ['Developer Tools'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to VWO for A/B testing.',
        domain: 'vwo.com',
    },
    {
        name: 'Xtremepush',
        categories: ['Messaging & Notifications'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Send event data to Xtremepush for omnichannel marketing.',
        domain: 'xtremepush.com',
    },
    {
        name: 'Zapier',
        categories: ['Productivity'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Trigger Zaps based on PostHog events to automate workflows.',
        domain: 'zapier.com',
    },
    {
        name: 'Zendesk',
        categories: ['Support & CX'],
        posthogProducts: ['CDP'],
        integrationTypes: ['Realtime Destination'],
        useCase: 'Sync user data to Zendesk to enrich support conversations.',
        domain: 'zendesk.com',
    },
]

export function integrationSlug(name: string): string {
    return name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '')
}

export const DOCS_URL_OVERRIDES: Record<string, string> = {
    // Error Tracking integrations
    GitHub: '/docs/error-tracking/integrations',
    GitLab: '/docs/error-tracking/integrations',
    Jira: '/docs/error-tracking/integrations',
    Linear: '/docs/error-tracking/integrations',

    // LLM Analytics — individual installation guides
    OpenRouter: '/docs/llm-analytics/installation/openrouter',

    // Feature Flags / Experiments
    Vercel: '/docs/feature-flags',

    // Data Warehouse sources
    BigQuery: '/docs/data-warehouse/sources/bigquery',
    'Amazon S3': '/docs/data-warehouse/sources/s3',
    Postgres: '/docs/data-warehouse/sources/postgres',
    MySQL: '/docs/data-warehouse/sources/mysql',
    MSSQL: '/docs/data-warehouse/sources/azure-db',
    Snowflake: '/docs/data-warehouse/sources/snowflake',

    // CDP destinations — only those with verified docs pages
    ActiveCampaign: '/docs/cdp/destinations/activecampaign',
    Airtable: '/docs/cdp/destinations/airtable',
    Attio: '/docs/cdp/destinations/attio',
    Avo: '/docs/cdp/destinations/avo',
    'AWS Kinesis': '/docs/cdp/destinations/aws-kinesis',
    Braze: '/docs/cdp/destinations/braze',
    Brevo: '/docs/cdp/destinations/brevo',
    'Customer.io': '/docs/cdp/destinations/customerio',
    Discord: '/docs/cdp/destinations/discord',
    'Engage.so': '/docs/cdp/destinations/engage',
    Gleap: '/docs/cdp/destinations/gleap',
    'Google Ads Conversions': '/docs/cdp/destinations/google-ads',
    'Google Cloud Storage': '/docs/cdp/destinations/google-cloud-storage',
    'Google Pub/Sub': '/docs/cdp/destinations/google-pubsub',
    HubSpot: '/docs/cdp/destinations/hubspot',
    Intercom: '/docs/cdp/destinations/intercom',
    'June.so': '/docs/cdp/destinations/june',
    Klaviyo: '/docs/cdp/destinations/klaviyo',
    Knock: '/docs/cdp/destinations/knock',
    Loops: '/docs/cdp/destinations/loops',
    Mailchimp: '/docs/cdp/destinations/mailchimp',
    Mailgun: '/docs/cdp/destinations/mailgun',
    Mailjet: '/docs/cdp/destinations/mailjet',
    Make: '/docs/cdp/destinations/make',
    'Meta Ads Conversions': '/docs/cdp/destinations/meta-ads',
    'Microsoft Teams': '/docs/cdp/destinations/microsoft-teams',
    PostHog: '/docs/cdp/destinations/posthog',
    'Reddit Conversions API': '/docs/cdp/destinations/reddit-ads-conversion-api',
    RudderStack: '/docs/cdp/destinations/rudderstack',
    Salesforce: '/docs/cdp/destinations/salesforce',
    Sendgrid: '/docs/cdp/destinations/sendgrid',
    Slack: '/docs/cdp/destinations/slack',
    'Snapchat Ads Conversions': '/docs/cdp/destinations/snapchat-ads',
    'TikTok Ads Conversions': '/docs/cdp/destinations/tiktok-ads',
    Zapier: '/docs/cdp/destinations/zapier',
}

export const ALL_CATEGORIES = 'All categories'
export const ALL_PRODUCTS = 'All products'
export const ALL_TYPES = 'All types'

export const INTEGRATION_CATEGORIES: string[] = Array.from(new Set(integrations.flatMap((i) => i.categories))).sort()

export const POSTHOG_PRODUCTS: string[] = Array.from(new Set(integrations.flatMap((i) => i.posthogProducts))).sort()

// Ordered by most common first
export const INTEGRATION_TYPES: string[] = [
    'Realtime Destination',
    'Native',
    'Source',
    'Via Workflows',
    'API-based',
    'MCP',
]
