// Row configuration for feature flags feature comparison slide
export const featureFlagsComparisonRows = [
    { type: 'header', label: 'Core Features' },
    {
        type: 'feature',
        product: 'feature_flags',
        feature: 'target_by_percentage',
        label: 'Target by percentage',
        description: 'Target features to a percentage of users',
    },
    {
        type: 'feature',
        product: 'feature_flags',
        feature: 'target_by_person_properties',
        label: 'Target by person properties',
        description: 'Target features based on user properties and attributes',
    },
    {
        type: 'feature',
        product: 'feature_flags',
        feature: 'flag_scheduling',
        label: 'Flag scheduling',
        description: 'Schedule flags to turn on or off automatically',
    },
    {
        type: 'feature',
        product: 'feature_flags',
        feature: 'experimentation',
        label: 'Experimentation',
        description: 'Run A/B tests with feature flags',
    },
    {
        type: 'feature',
        product: 'feature_flags',
        feature: 'multivariate_flags',
        label: 'Multivariate flags',
        description: 'Test multiple variants of a feature',
    },
    { type: 'header', label: 'Platform Features' },
    { type: 'platform', feature: 'open_source' },
    { type: 'platform', feature: 'self_host' },
    { type: 'platform', feature: 'usage_based_pricing' },
    { type: 'platform', feature: 'transparent_pricing' },
    { type: 'platform', feature: 'free_tier' },
    { type: 'platform', feature: 'built_in_analytics' },
]
