// Feature configuration for product analytics feature comparison slide
export const productAnalyticsProductFeatures = [
    { type: 'header', label: 'Core insights' },
    {
        type: 'feature',
        product: 'product_analytics',
        feature: 'ready_made_insight_types',
        label: 'Ready-made insight types',
    },
    { type: 'feature', product: 'product_analytics', feature: 'sql_mode', label: 'SQL mode' },
    { type: 'header', label: 'Funnels' },
    { type: 'feature', product: 'product_analytics', feature: 'conversion_funnels', label: 'Conversion funnels' },
    { type: 'feature', product: 'product_analytics', feature: 'historical_trends', label: 'Historical trends' },
    {
        type: 'feature',
        product: 'product_analytics',
        feature: 'time_to_convert_insights',
        label: 'Time to convert insights',
    },
    { type: 'feature', product: 'product_analytics', feature: 'sequential_step_order', label: 'Sequential step order' },
    { type: 'feature', product: 'product_analytics', feature: 'strict_step_order', label: 'Strict step order' },
    { type: 'feature', product: 'product_analytics', feature: 'any_step_order', label: 'Any step order' },
    { type: 'feature', product: 'product_analytics', feature: 'exclusion_events', label: 'Exclusion events' },
    { type: 'feature', product: 'product_analytics', feature: 'conversion_windows', label: 'Conversion windows' },
    {
        type: 'feature',
        product: 'product_analytics',
        feature: 'reveal_user_paths_between_steps',
        label: 'Reveal user paths between steps',
    },
    { type: 'feature', product: 'product_analytics', feature: 'anomaly_detection', label: 'Anomaly detection' },
    { type: 'header', label: 'Filtering & analysis' },
    {
        type: 'feature',
        product: 'product_analytics',
        feature: 'filter_internal_and_test_users',
        label: 'Filter internal and test users',
    },
    { type: 'feature', product: 'product_analytics', feature: 'filter_by_cohort', label: 'Filter by cohort' },
    {
        type: 'feature',
        product: 'product_analytics',
        feature: 'filter_by_person_property',
        label: 'Filter by person property',
    },
    {
        type: 'feature',
        product: 'product_analytics',
        feature: 'breakdown_by_person_property',
        label: 'Breakdown by person property',
    },
    { type: 'feature', product: 'product_analytics', feature: 'correlation_analysis', label: 'Correlation analysis' },
    { type: 'header', label: 'Path analysis' },
    {
        type: 'feature',
        product: 'product_analytics',
        feature: 'reveal_paths_from_a_start_point',
        label: 'Reveal paths from a start point',
    },
    {
        type: 'feature',
        product: 'product_analytics',
        feature: 'reveal_paths_from_an_end_point',
        label: 'Reveal paths from an end point',
    },
    {
        type: 'feature',
        product: 'product_analytics',
        feature: 'reveal_paths_between_points',
        label: 'Reveal paths between points',
    },
    {
        type: 'feature',
        product: 'product_analytics',
        feature: 'reveal_paths_within_funnels',
        label: 'Reveal paths within funnels',
    },
    { type: 'feature', product: 'product_analytics', feature: 'zoom_in_out', label: 'Zoom in/out' },
    { type: 'header', label: 'Dashboards' },
    {
        type: 'feature',
        product: 'product_analytics',
        feature: 'user_level_permissions',
        label: 'User-level permissions',
    },
    {
        type: 'feature',
        product: 'product_analytics',
        feature: 'project_level_permissions',
        label: 'Project-level permissions',
    },
    { type: 'feature', product: 'product_analytics', feature: 'pinned_dashboards', label: 'Pinned dashboards' },
    {
        type: 'feature',
        product: 'product_analytics',
        feature: 'share_dashboards_externally',
        label: 'Share dashboards externally',
    },
    {
        type: 'feature',
        product: 'product_analytics',
        feature: 'subscribe_to_dashboards',
        label: 'Subscribe to dashboards',
    },
    {
        type: 'feature',
        product: 'product_analytics',
        feature: 'embed_dashboards_anywhere',
        label: 'Embed dashboards anywhere',
    },
    { type: 'feature', product: 'product_analytics', feature: 'annotations', label: 'Annotations' },
    { type: 'header', label: 'Platform features' },
    { type: 'platform', feature: 'open_source' },
    { type: 'platform', feature: 'self_host' },
    { type: 'platform', feature: 'usage_based_pricing' },
    { type: 'platform', feature: 'transparent_pricing' },
    { type: 'platform', feature: 'free_tier' },
]
