import React from 'react'
import { IconPiggyBank } from '@posthog/icons'
import Link from 'components/Link'

export const revenueAnalytics = {
    name: 'Revenue Analytics',
    Icon: IconPiggyBank,
    handle: 'revenue_analytics',
    slug: 'revenue-analytics',
    color: 'green',
    colorSecondary: 'green-2',
    category: 'analytics',
    status: 'beta',
    seo: {
        title: 'Revenue Analytics - PostHog',
        description:
            'Track revenue from events or payment platforms. See revenue attribution by marketing channel, deferred revenue recognition, and multi-currency support.',
    },
    overview: {
        title: 'Track revenue alongside product metrics',
        description:
            'Connect revenue data from events or payment platforms like Stripe. See revenue attribution, deferred recognition for subscriptions, and multi-currency support all in one place.',
        textColor: 'text-white',
        layout: 'columns',
    },
    screenshots: {
        overview: {
            src: 'https://res.cloudinary.com/dmukukwp6/image/upload/Screenshot_2025_06_25_at_19_51_33_9f5267a861.png',
            alt: 'Revenue Analytics dashboard',
            classes: 'absolute max-w-[95%] @2xl:max-w-[525px] rounded-md overflow-hidden shadow-2xl',
        },
    },
    hog: {
        src: 'https://res.cloudinary.com/dmukukwp6/image/upload/posthog.com/src/components/Product/hogs/product-analytics-hog.png',
        alt: 'Hedgehog counting money',
        classes: 'absolute bottom-0 right-4 max-w-lg',
    },
    customers: {
        // assemblyai: {
        //     headline: 'tracks revenue per customer segment',
        //     description: 'We can see exactly which features drive revenue and which customer segments are most valuable.',
        // },
        // hasura: {
        //     headline: 'connects Stripe data with product usage',
        //     description: 'Revenue analytics shows us the direct impact of product changes on our bottom line.',
        // },
        // contra: {
        //     headline: 'attributes revenue to marketing channels',
        //     description: 'Finally we can see which campaigns actually generate revenue, not just clicks.',
        // },
        // ycombinator: {
        //     headline: 'monitors portfolio company metrics',
        //     description: 'Revenue tracking alongside product metrics gives us a complete picture of company health.',
        // },
    },
    features: [
        {
            title: 'Revenue data sources',
            headline: 'Flexible ways to track revenue',
            description:
                'Send revenue data via events or connect payment platforms directly through our data warehouse.',
            images: [
                {
                    src: 'https://res.cloudinary.com/dmukukwp6/image/upload/revenue_light_d1249bb62b.png',
                    alt: 'Revenue data sources',
                },
            ],
            features: [
                {
                    title: 'Event properties',
                    description: 'Add value and currency properties to any revenue-generating event',
                },
                {
                    title: 'Stripe integration',
                    description: 'Connect Stripe directly for automatic revenue tracking',
                },
                {
                    title: 'Backend events',
                    description: 'Track server-side purchases with session association',
                },
                {
                    title: 'Multi-currency support',
                    description: 'Handle payments in any currency with automatic conversion',
                },
                {
                    title: 'Coming soon',
                    description: 'Chargebee and other payment platform integrations',
                },
            ],
        },
        {
            title: 'Revenue attribution',
            headline: 'See where your revenue really comes from',
            description:
                'Attribute revenue to marketing channels, campaigns, and customer segments for true ROI analysis.',
            features: [
                {
                    title: 'Channel attribution',
                    description: 'Track revenue by direct, organic, paid, social, and custom channels',
                },
                {
                    title: 'Campaign tracking',
                    description: 'See revenue generated by each marketing campaign via UTMs',
                },
                {
                    title: 'Customer segmentation',
                    description: 'Break down revenue by user properties and cohorts',
                },
                {
                    title: 'Product attribution',
                    description: 'Connect revenue to specific features and user actions',
                },
                {
                    title: 'Geographic analysis',
                    description: 'Understand revenue distribution by location',
                },
            ],
        },
        {
            title: 'Subscription analytics',
            headline: 'Built for recurring revenue',
            description: 'Automatic deferred revenue recognition and subscription metrics for SaaS businesses.',
            features: [
                {
                    title: 'Deferred revenue',
                    description: 'Automatically spread subscription revenue across service periods',
                },
                {
                    title: 'MRR/ARR tracking',
                    description: 'Monitor monthly and annual recurring revenue trends',
                },
                {
                    title: 'Churn analysis',
                    description: 'See revenue churn alongside user churn metrics',
                },
                {
                    title: 'Expansion revenue',
                    description: 'Track upgrades, downgrades, and expansion revenue',
                },
                {
                    title: 'Future revenue',
                    description: 'Visualize committed revenue from existing subscriptions',
                },
            ],
        },
        {
            title: 'Product analytics integration',
            headline: 'Revenue data everywhere',
            description: 'Use revenue data in funnels, cohorts, and custom insights for deeper product analysis.',
            features: [
                {
                    title: 'Revenue funnels',
                    description: 'Build conversion funnels that show revenue at each step',
                },
                {
                    title: 'User journey analysis',
                    description: 'See paths that lead to high-value purchases',
                },
                {
                    title: 'Cohort segmentation',
                    description: 'Create cohorts based on revenue contribution',
                },
                {
                    title: 'SQL access',
                    description: 'Query revenue data with HogQL for custom analysis',
                },
                {
                    title: 'Dashboard integration',
                    description: 'Add revenue metrics to any dashboard',
                },
            ],
        },
        {
            title: 'Coming soon',
            headline: 'Roadmap for revenue analytics',
            description: "We're actively developing new features based on user feedback.",
            features: [
                {
                    title: 'CAC & CPC metrics',
                    description: 'Customer acquisition cost and cost per click tracking',
                },
                {
                    title: 'More integrations',
                    description: 'Chargebee, PayPal, and custom payment platforms',
                },
                {
                    title: 'Advanced forecasting',
                    description: 'Revenue predictions based on historical data',
                },
                {
                    title: 'Profit tracking',
                    description: 'Connect cost data for margin analysis',
                },
                {
                    title: 'Invoice management',
                    description: 'Track invoice status and payment timelines',
                },
            ],
        },
    ],
    questions: [
        {
            question: 'Which marketing channels generate the most revenue?',
        },
        {
            question: "What's our MRR growth rate?",
        },
        {
            question: 'Which features do our highest-paying customers use?',
        },
        {
            question: 'How much revenue comes from each customer segment?',
        },
        {
            question: "What's the revenue impact of our latest product change?",
        },
        {
            question: 'Which countries generate the most revenue per user?',
        },
        {
            question: 'How much expansion revenue are we generating?',
        },
        {
            question: "What's our revenue churn rate by cohort?",
        },
    ],
    comparison: {
        summary: {
            them: [
                {
                    title: 'Separate revenue and product analytics',
                    subtitle: 'Most tools require switching between platforms',
                },
                {
                    title: 'Limited attribution options',
                    subtitle: 'Basic channel tracking without product context',
                },
                {
                    title: 'Manual data export and analysis',
                    subtitle: 'Export data to spreadsheets for custom analysis',
                },
            ],
            us: [
                {
                    title: 'Unified revenue and product data',
                    subtitle: 'See revenue alongside user behavior in one platform',
                },
                {
                    title: 'Full attribution stack',
                    subtitle: 'Connect revenue to channels, features, and user actions',
                },
                {
                    title: 'Automatic deferred recognition',
                    subtitle: 'Built-in support for subscription revenue accounting',
                },
                {
                    title: 'Multi-currency with conversion',
                    subtitle: 'Handle global payments with automatic currency conversion',
                },
                {
                    title: 'SQL access to all data',
                    subtitle: 'Query revenue data directly with HogQL',
                },
            ],
        },
        features: [
            {
                feature: 'Revenue tracking',
                companies: {
                    Stripe: true,
                    Mixpanel: true,
                    Amplitude: true,
                    PostHog: true,
                },
            },
            {
                feature: 'Channel attribution',
                companies: {
                    Stripe: false,
                    Mixpanel: false,
                    Amplitude: false,
                    PostHog: true,
                },
            },
            {
                feature: 'Deferred revenue',
                companies: {
                    Stripe: true,
                    Mixpanel: false,
                    Amplitude: false,
                    PostHog: true,
                },
            },
            {
                feature: 'Product analytics integration',
                companies: {
                    Stripe: false,
                    Mixpanel: true,
                    Amplitude: true,
                    PostHog: true,
                },
            },
            {
                feature: 'Multi-currency support',
                companies: {
                    Stripe: true,
                    Mixpanel: false,
                    Amplitude: false,
                    PostHog: true,
                },
            },
            {
                feature: 'SQL access',
                companies: {
                    Stripe: false,
                    Mixpanel: false,
                    Amplitude: false,
                    PostHog: true,
                },
            },
            {
                feature: 'Free during beta',
                companies: {
                    Stripe: false,
                    Mixpanel: false,
                    Amplitude: false,
                    PostHog: true,
                },
            },
        ],
    },
    pairsWith: [
        {
            slug: 'product-analytics',
            description: 'Analyze revenue alongside user behavior and product usage',
        },
        {
            slug: 'web-analytics',
            description: 'See revenue attribution by traffic source and campaign',
        },
        {
            slug: 'data-warehouse',
            description: 'Connect payment platforms for automatic revenue tracking',
        },
        {
            slug: 'dashboards',
            description: 'Add revenue metrics to any dashboard',
        },
    ],
    worksWith: ['product_analytics', 'web_analytics', 'data_warehouse', 'dashboards'],
}
