// Feature configuration for session replay feature comparison slide
export const sessionReplayProductFeatures = [
    { label: 'Core features' },
    { product: 'session_replay', feature: 'ai_summaries' },
    { product: 'session_replay', feature: 'single_page_app' },
    { product: 'session_replay', feature: 'identity_detection' },
    { label: 'Mobile support' },
    { product: 'session_replay', feature: 'ios_recordings' },
    { product: 'session_replay', feature: 'android_recordings' },
    { product: 'session_replay', feature: 'react_native_recordings' },
    { product: 'session_replay', feature: 'flutter_recordings' },
    { label: 'Targeting & filtering' },
    { product: 'session_replay', feature: 'target_by_url' },
    { product: 'session_replay', feature: 'target_by_sample' },
    { product: 'session_replay', feature: 'filter_by_user_or_event' },
    { product: 'session_replay', feature: 'search_by_network' },
    { label: 'Detection & privacy' },
    { product: 'session_replay', feature: 'rage_click_detection' },
    { product: 'session_replay', feature: 'privacy_masking' },
    { label: 'Export & storage' },
    { product: 'session_replay', feature: 'export_to_json' },
    { product: 'session_replay', feature: 'export_to_video' },
    { product: 'session_replay', feature: 'retention_policy' },
    { label: 'Platform features' },
    { feature: 'open_source' },
    { feature: 'self_host' },
    { feature: 'usage_based_pricing' },
    { feature: 'transparent_pricing' },
    { feature: 'free_tier' },
]
