// Feature configuration for web analytics feature comparison slide
export const webAnalyticsProductFeatures = [
    { type: 'header', label: 'Core analytics' },
    {
        type: 'feature',
        product: 'web_analytics',
        feature: 'pre_configured_dashboards',
        label: 'Pre-configured dashboards',
    },
    {
        type: 'feature',
        product: 'web_analytics',
        feature: 'visitor_and_view_tracking',
        label: 'Visitor and view tracking',
    },
    {
        type: 'feature',
        product: 'web_analytics',
        feature: 'session_and_duration_tracking',
        label: 'Session and duration tracking',
    },
    { type: 'feature', product: 'web_analytics', feature: 'bounce_rate_tracking', label: 'Bounce rate tracking' },
    { type: 'header', label: 'Breakdowns & reporting' },
    { type: 'feature', product: 'web_analytics', feature: 'breakdown_by_geoip', label: 'Breakdown by GeoIP' },
    {
        type: 'feature',
        product: 'web_analytics',
        feature: 'breakdown_by_device_and_browser',
        label: 'Breakdown by device and browser',
    },
    { type: 'feature', product: 'web_analytics', feature: 'web_vitals_reporting', label: 'Web Vitals reporting' },
    { type: 'feature', product: 'web_analytics', feature: 'revenue_tracking', label: 'Revenue tracking' },
    { type: 'feature', product: 'web_analytics', feature: 'real_time_reporting', label: 'Real-time reporting' },
    { type: 'header', label: 'Privacy & compliance' },
    { type: 'feature', product: 'web_analytics', feature: 'open_source', label: 'Open source' },
    { type: 'feature', product: 'web_analytics', feature: 'first_party_cookies', label: '1st party cookies' },
    { type: 'feature', product: 'web_analytics', feature: 'cookieless_tracking', label: 'Cookieless tracking' },
    { type: 'feature', product: 'web_analytics', feature: 'hipaa_compliance', label: 'HIPAA compliance' },
    { type: 'feature', product: 'web_analytics', feature: 'gdpr_compliance', label: 'GDPR compliance' },
    { type: 'feature', product: 'web_analytics', feature: 'no_data_sampling', label: 'No data sampling' },
    { type: 'header', label: 'Advanced features' },
    { type: 'feature', product: 'web_analytics', feature: 'scroll_depth_tracking', label: 'Scroll depth tracking' },
    { type: 'feature', product: 'web_analytics', feature: 'custom_channel_types', label: 'Custom channel types' },
    { type: 'header', label: 'Integration' },
    {
        type: 'feature',
        product: 'web_analytics',
        feature: 'integration_with_feature_flags',
        label: 'Integration with feature flags',
    },
    {
        type: 'feature',
        product: 'web_analytics',
        feature: 'integration_with_session_replay',
        label: 'Integration with session replay',
    },
    {
        type: 'feature',
        product: 'web_analytics',
        feature: 'integration_with_surveys',
        label: 'Integration with surveys',
    },
]
