import React from 'react'
import {
    IconApp,
    IconApps,
    IconBadge,
    IconBell,
    IconBook,
    IconBrain,
    IconBug,
    IconBuilding,
    IconCalendar,
    IconCameraFrame,
    IconComment,
    IconCursor,
    IconDatabase,
    IconDay,
    IconDocument,
    IconEllipsis,
    IconGear,
    IconGitBranch,
    IconGlobe,
    IconGraph,
    IconLetter,
    IconListCheck,
    IconLock,
    IconMagic,
    IconMegaphone,
    IconPeople,
    IconPerson,
    IconPiggyBank,
    IconPullRequest,
    IconSend,
    IconServer,
    IconShare,
    IconShieldLock,
    IconStethoscope,
    IconStore,
    IconThumbsUp,
    IconUpload,
    IconWrench,
} from '@posthog/icons'

// What each MCP tool category is about: a PostHog product handle (its icon and color come from
// `useProduct`), or an icon and a color, plus the docs page the category label links to. Categories
// come from `src/data/mcp-tools.json`. Categories without a docs page of their own link to the MCP
// tools reference.
export const CATEGORIES: Record<
    string,
    { docs: string; product?: string; Icon?: React.ComponentType<{ className?: string }>; color?: string }
> = {
    'Access control': { Icon: IconLock, color: 'purple', docs: '/docs/settings/access-control' },
    Actions: { Icon: IconCursor, color: 'orange', docs: '/docs/data/actions' },
    'AI observability': { product: 'ai_observability', docs: '/docs/ai-observability' },
    Alerts: { Icon: IconBell, color: 'red', docs: '/docs/alerts' },
    Annotations: { Icon: IconComment, color: 'yellow', docs: '/docs/data/annotations' },
    Autoresearch: { Icon: IconBrain, color: 'purple', docs: '/docs/model-context-protocol/tools' },
    Billing: { Icon: IconPiggyBank, color: 'green', docs: '/docs/billing/estimating-usage-costs' },
    'Billing alerts': { Icon: IconBell, color: 'green', docs: '/docs/billing/limits-alerts' },
    'Business knowledge': { Icon: IconBook, color: 'salmon', docs: '/docs/self-driving/context' },
    Canvas: { Icon: IconGraph, color: 'purple', docs: '/docs/posthog-desktop/canvases' },
    Cohorts: { Icon: IconPeople, color: 'blue', docs: '/docs/data/cohorts' },
    'Context wiki': { Icon: IconDocument, color: 'teal', docs: '/docs/self-driving/context' },
    Conversations: { product: 'support', docs: '/docs/support' },
    Core: { Icon: IconGear, color: 'seagreen', docs: '/docs/settings/projects' },
    'Cross-project dashboards': { product: 'dashboards', docs: '/docs/product-analytics/dashboards' },
    'Customer analytics': { Icon: IconPeople, color: 'salmon', docs: '/docs/customer-analytics' },
    Dashboards: { product: 'dashboards', docs: '/docs/product-analytics/dashboards' },
    'Data catalog': { Icon: IconListCheck, color: 'purple', docs: '/docs/semantic-layer' },
    'Data pipelines': { Icon: IconShare, color: 'purple', docs: '/docs/cdp/batch-exports' },
    'Data quality': { Icon: IconListCheck, color: 'red', docs: '/docs/data-warehouse/data-quality' },
    'Data schema': { Icon: IconDatabase, color: 'blue', docs: '/docs/data' },
    'Data warehouse': { product: 'data_warehouse', docs: '/docs/data-warehouse' },
    Debug: { Icon: IconBug, color: 'red', docs: '/docs/model-context-protocol/tools' },
    Docs: { Icon: IconBook, color: 'blue', docs: '/docs' },
    'Early access features': { product: 'early_access', docs: '/docs/feature-flags/early-access-feature-management' },
    Endpoints: { product: 'endpoints', docs: '/docs/endpoints' },
    'Engineering analytics': { Icon: IconGitBranch, color: 'orange', docs: '/docs/model-context-protocol/tools' },
    'Error tracking': { product: 'error_tracking', docs: '/docs/error-tracking' },
    'Error tracking alerts': { product: 'error_tracking', docs: '/docs/error-tracking/alerts' },
    'Events & properties': { Icon: IconSend, color: 'orange', docs: '/docs/product-analytics/schema-management' },
    Experiments: { product: 'experiments', docs: '/docs/experiments' },
    'Feature flags': { product: 'feature_flags', docs: '/docs/feature-flags' },
    Feedback: { Icon: IconThumbsUp, color: 'yellow', docs: '/docs/model-context-protocol/tools' },
    'Field notes': { product: 'toolbar', docs: '/docs/toolbar' },
    'Function templates': { product: 'cdp', docs: '/docs/cdp/destinations' },
    Functions: { product: 'cdp', docs: '/docs/cdp' },
    Health: { Icon: IconStethoscope, color: 'seagreen', docs: '/docs/health-checks' },
    'Insights & analytics': { product: 'product_analytics', docs: '/docs/product-analytics/insights' },
    Integrations: { Icon: IconApps, color: 'yellow', docs: '/docs/error-tracking/integrations' },
    Logs: { product: 'logs', docs: '/docs/logs' },
    'Managed migrations': { Icon: IconUpload, color: 'blue', docs: '/docs/migrate/managed-migrations' },
    'Marketing analytics': { Icon: IconMegaphone, color: 'orange', docs: '/docs/web-analytics/marketing-analytics' },
    'MCP analytics': { product: 'mcp_analytics', docs: '/docs/mcp-analytics' },
    'MCP registry': { Icon: IconServer, color: 'purple', docs: '/docs/posthog-desktop/mcp-servers' },
    'MCP Store': { Icon: IconStore, color: 'purple', docs: '/docs/posthog-desktop/mcp-servers' },
    Messaging: { Icon: IconShieldLock, color: 'green', docs: '/docs/workflows/opt-outs' },
    Metrics: { product: 'metrics', docs: '/docs/metrics' },
    Notebooks: { product: 'notebooks', docs: '/docs/notebooks' },
    'Organization & project management': { Icon: IconBuilding, color: 'blue', docs: '/docs/settings/organizations' },
    Persons: { Icon: IconPerson, color: 'seagreen', docs: '/docs/data/persons' },
    'Platform Features': { product: 'platform_packages', docs: '/docs/settings/activity-logs' },
    'PostHog AI': { product: 'posthog_ai', docs: '/docs/posthog-ai' },
    'Product analytics': { product: 'product_analytics', docs: '/docs/product-analytics' },
    'Query wrappers': { product: 'product_analytics', docs: '/docs/product-analytics/trends/overview' },
    Reminders: { Icon: IconCalendar, color: 'yellow', docs: '/docs/model-context-protocol/tools' },
    'Replay vision': { product: 'replay_vision', docs: '/docs/replay-vision' },
    'Reverse proxy': { Icon: IconGlobe, color: 'teal', docs: '/docs/advanced/proxy' },
    ReviewHog: { Icon: IconPullRequest, color: 'purple', docs: '/docs/model-context-protocol/tools' },
    'Session replays': { product: 'session_replay', docs: '/docs/session-replay' },
    Signals: { product: 'inbox', docs: '/docs/self-driving/signals' },
    Skills: { Icon: IconMagic, color: 'purple', docs: '/docs/skills' },
    SQL: { product: 'sql_editor', docs: '/docs/sql' },
    Stamphog: { Icon: IconBadge, color: 'seagreen', docs: '/docs/model-context-protocol/tools' },
    'Streamlit apps': { Icon: IconApp, color: 'red', docs: '/docs/model-context-protocol/tools' },
    Subscriptions: { Icon: IconLetter, color: 'blue', docs: '/docs/product-analytics/subscriptions' },
    Surveys: { product: 'surveys', docs: '/docs/surveys' },
    Tasks: { product: 'posthog_code', docs: '/docs/posthog-desktop/tasks' },
    Today: { Icon: IconDay, color: 'yellow', docs: '/docs/self-driving' },
    Tracing: { product: 'traces', docs: '/docs/distributed-tracing' },
    Utilities: { Icon: IconWrench, color: 'blue', docs: '/docs/model-context-protocol/tools' },
    'Visual review': { Icon: IconCameraFrame, color: 'salmon', docs: '/docs/model-context-protocol/tools' },
    'Warehouse sources': { product: 'data_in', docs: '/docs/data-warehouse/sources' },
    'Web analytics': { product: 'web_analytics', docs: '/docs/web-analytics' },
    Workflows: { product: 'workflows_emails', docs: '/docs/workflows' },
    Uncategorized: { Icon: IconEllipsis, color: 'muted', docs: '/docs/model-context-protocol/tools' },
    Other: { Icon: IconEllipsis, color: 'muted', docs: '/docs/model-context-protocol/tools' },
}
