import { FeatureComparisonData } from 'types'

const featuresComparisonData: FeatureComparisonData[] = [
    {
        title: 'Open Source',
        posthog: true,
        amplitude: false,
        mixpanel: false,
        heap: false,
    },
    {
        title: 'Self-Hosting Available',
        posthog: true,
        amplitude: false,
        mixpanel: false,
        heap: false,
    },
    {
        title: 'API',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Data Import',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Direct SQL Access',
        posthog: true,
        amplitude: false,
        mixpanel: false,
        heap: false,
    },
    {
        title: 'Full Data History',
        posthog: true,
        amplitude: false,
        mixpanel: false,
        heap: false,
    },
    {
        title: 'Event Tracking',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Event Autocapture',
        posthog: true,
        amplitude: false,
        mixpanel: false,
        heap: true,
    },
    {
        title: 'Heatmap',
        posthog: true,
        amplitude: false,
        mixpanel: false,
        heap: false,
    },
    {
        title: 'Recordings',
        posthog: true,
        amplitude: false,
        mixpanel: false,
        heap: false,
    },
    {
        title: 'External Integrations',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Custom Plugins',
        posthog: true,
        amplitude: false,
        mixpanel: false,
        heap: false,
    },
    {
        title: 'A/B Testing',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Feature Flags',
        posthog: true,
        amplitude: false,
        mixpanel: false,
        heap: false,
    },
    {
        title: 'Funnel Analysis',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Cohort Analysis',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Conversion Tracking',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Retention Tracking',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Revenue Tracking',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'UTM Tracking',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Email Link Tracking',
        posthog: false,
        amplitude: false,
        mixpanel: true,
        heap: false,
    },
    {
        title: 'Ad Campaign Tracking',
        posthog: false,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Dashboards',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Multi-Site',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Multi-User',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Push Notifications',
        posthog: false,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Toolbar',
        posthog: true,
        amplitude: false,
        mixpanel: false,
        heap: true,
    },
]

export default featuresComparisonData
