const featuresComparisonData = [
    {
        title: 'Self-Hosted',
        posthog: true,
        amplitude: false,
        mixpanel: false,
        heap: false,
    },
    {
        title: 'Managed Hosting',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Heatmap',
        posthog: true,
        amplitude: false,
        mixpanel: false,
        heap: false,
    },
    {
        title: 'API',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Event Tracking',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Conversion Tracking',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Dashboards',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Data Visualization',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: false,
    },
    {
        title: 'Cohort Analysis',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Funnel Analysis',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Push Notifications',
        posthog: false,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Retention Tracking',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Engagement Tracking',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Revenue Tracking',
        posthog: false,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Data Import',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: false,
    },
    {
        title: 'External Integrations',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'UTM Tracking',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Email Link Tracking',
        posthog: false,
        amplitude: false,
        mixpanel: true,
        heap: false,
    },
    {
        title: 'Multi-Site',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'Multi-User',
        posthog: true,
        amplitude: true,
        mixpanel: true,
        heap: true,
    },
    {
        title: 'A/B Testing',
        posthog: false,
        amplitude: true,
        mixpanel: true,
        heap: false,
    },
    {
        title: 'Direct SQL Access',
        posthog: true,
        amplitude: false,
        mixpanel: false,
        heap: true,
    },
    {
        title: 'Full Data History',
        posthog: true,
        amplitude: false,
        mixpanel: false,
        heap: false,
    },
]

export default featuresComparisonData
