export { default as SlidesTemplate } from './SlidesTemplate'
export { createSlideConfig, defaultSlides } from './createSlideConfig'
export type { SlideConfig, SlideConfigOptions, SlideConfigResult } from './createSlideConfig'
export { default as SlideThumbnails } from './SlideThumbnails'
export { default as OverviewSlide } from './OverviewSlide'
export { default as CustomersSlide } from './CustomersSlide'
export { default as FeaturesSlide } from './FeaturesSlide'
export { default as FeaturesGrid } from './FeaturesGrid'
export { default as FeaturesSplitWithImage } from './FeaturesSplitWithImage'
export { default as QuestionsSlide } from './QuestionsSlide'
export { default as PlanComparison } from './PlanComparison'
export { default as ComparisonSummarySlide } from './ComparisonSummarySlide'
export { default as FeatureComparisonSlide } from './FeatureComparisonSlide'
export { default as DocsSlide } from './DocsSlide'
export { default as PairsWithSlide } from './PairsWithSlide'
export { default as GettingStartedSlide } from './GettingStartedSlide'
