/**
 * Keeps the locale files in src/i18n/locales in step with en.yml. See src/i18n/README.md.
 *
 * Each locale has a snapshot in locales/.source/<code>.yml: the English text that its translations came from.
 * A key whose English differs from the snapshot is out of date. The script sends only those keys to Claude.
 *
 *   pnpm i18n:sync [--locale <code>] [--dry-run] [--summary <file>]   translate what changed
 *   pnpm i18n:sync --init                                              write missing snapshots, no API calls
 *   pnpm i18n:sync --check                                             validate the locale files
 *   pnpm i18n:sync --report <git ref> --locale <code>                  print a PR body for the locale
 */
import fs from 'node:fs'
import path from 'node:path'
import { execFileSync } from 'node:child_process'
import { parseArgs } from 'node:util'
import { isMap, parse, parseDocument, stringify, type Document, type YAMLMap } from 'yaml'
import { flattenMessages, type Messages } from '../src/i18n/flatten.ts'

const LOCALES_DIR = path.resolve(import.meta.dirname, '../src/i18n/locales')
const SOURCE_DIR = path.join(LOCALES_DIR, '.source')
const README_URL = 'https://github.com/PostHog/posthog.com/blob/master/src/i18n/README.md#how-to-review-a-translation'
const MODEL = 'claude-opus-5'
const BATCH_SIZE = 50

const { values: args } = parseArgs({
    options: {
        locale: { type: 'string' },
        'dry-run': { type: 'boolean', default: false },
        init: { type: 'boolean', default: false },
        check: { type: 'boolean', default: false },
        report: { type: 'string' },
        summary: { type: 'string' },
    },
})

const localeFile = (code: string) => path.join(LOCALES_DIR, `${code}.yml`)
const sourceFile = (code: string) => path.join(SOURCE_DIR, `${code}.yml`)

const english = parse(fs.readFileSync(localeFile('en'), 'utf8'))
const englishMessages = flattenMessages(english.messages)
const englishKeys = Object.keys(englishMessages)
// Keys that stay in English in every locale, such as the "View in English" button.
const untranslated = new Set<string>(english.untranslated ?? [])
const translatable = englishKeys.filter((key) => !untranslated.has(key))

const codes = fs
    .readdirSync(LOCALES_DIR)
    .filter((file) => file.endsWith('.yml') && file !== 'en.yml')
    .map((file) => path.basename(file, '.yml'))
    .filter((code) => !args.locale || code === args.locale)

if (args.locale && !codes.length) fail(`src/i18n/locales/${args.locale}.yml does not exist`)

// The distinct tags and {placeholders} in a string. A translation must have the same set as its English text.
// It can use a tag more than once, for example to bold two words where English bolds one.
function markup(text: string): string {
    const found = text.matchAll(/<\/?[a-zA-Z][\w-]*\s*\/?>|\{[a-zA-Z_]\w*\}/g)
    return [...new Set([...found].map(([match]) => match.replace(/\s/g, '')))].sort().join(' ')
}

function readLocale(code: string) {
    const doc = parseDocument(fs.readFileSync(localeFile(code), 'utf8'))
    const { name, lang, messages } = doc.toJS()
    return { doc, name: name as string, lang: (lang || code) as string, messages: flattenMessages(messages ?? {}) }
}

// With no snapshot, assume the current translations match the current English. A new locale starts empty.
function readSnapshot(code: string, messages: Messages): Messages {
    if (fs.existsSync(sourceFile(code))) return parse(fs.readFileSync(sourceFile(code), 'utf8')) ?? {}
    return Object.fromEntries(Object.keys(messages).map((key) => [key, englishMessages[key]]))
}

function writeSnapshot(code: string, snapshot: Messages) {
    const ordered = Object.fromEntries(englishKeys.filter((key) => key in snapshot).map((key) => [key, snapshot[key]]))
    fs.mkdirSync(SOURCE_DIR, { recursive: true })
    fs.writeFileSync(
        sourceFile(code),
        `# Generated by scripts/i18n-sync.ts. Do not edit.\n# The English text that each key in ${code}.yml was translated from.\n` +
            stringify(ordered, { lineWidth: 0, singleQuote: true })
    )
}

// "hero.cta.body.1" -> ['messages', 'hero', 'cta', 'body', 1]. YAML reads `1:` as a number key.
const yamlPath = (key: string) => [
    'messages',
    ...key.split('.').map((part) => (/^\d+$/.test(part) ? Number(part) : part)),
]

// Document.setIn would make a list for a number key such as `section.7`, so make the maps here.
function setKey(doc: Document, key: string, value: string) {
    const parts = yamlPath(key)
    let map = doc.contents as YAMLMap
    for (const part of parts.slice(0, -1)) {
        let child = map.get(part, true)
        if (!isMap(child)) {
            child = doc.createNode({})
            map.set(part, child)
        }
        child.flow = false
        map = child
    }
    map.set(parts[parts.length - 1], value)
}

// Position in en.yml of a key, or of the first key under a map.
function position(key: string): number {
    const index = englishKeys.findIndex((k) => k === key || k.startsWith(`${key}.`))
    return index === -1 ? Infinity : index
}

// Drops maps that no longer have keys. Moves each new key next to its neighbors in en.yml, and leaves the
// other keys where they are, so a translator's own order stays.
function tidy(map: YAMLMap, existing: Set<string>, prefix = '') {
    map.items = map.items.filter(
        (pair) => !isMap(pair.value) || (tidy(pair.value, existing, keyOf(prefix, pair)), pair.value.items.length)
    )
    for (const pair of map.items.filter((pair) => !existing.has(keyOf(prefix, pair)))) {
        map.items.splice(map.items.indexOf(pair), 1)
        const next = map.items.findIndex((other) => position(keyOf(prefix, other)) > position(keyOf(prefix, pair)))
        map.items.splice(next === -1 ? map.items.length : next, 0, pair)
    }
}

function keyOf(prefix: string, pair: { key: unknown }): string {
    const key = String((pair.key as { value?: unknown })?.value ?? pair.key)
    return prefix ? `${prefix}.${key}` : key
}

type Item = { key: string; english: string; previous_english?: string; current_translation?: string }

const OUTPUT_SCHEMA = {
    type: 'object',
    properties: {
        translations: {
            type: 'array',
            items: {
                type: 'object',
                properties: { key: { type: 'string' }, text: { type: 'string' } },
                required: ['key', 'text'],
                additionalProperties: false,
            },
        },
    },
    required: ['translations'],
    additionalProperties: false,
}

async function translate(apiKey: string, locale: { name: string; lang: string; messages: Messages }, items: Item[]) {
    const system = `You translate the PostHog home page from English into ${locale.name} (${locale.lang}).

Rules:
- Keep product names in English, for example "Product analytics", "Session replay", "Feature flags", and "Error tracking". Also keep brand names, code, commands, file names, and URLs in English.
- Keep every tag, such as <highlight>…</highlight> or <logo/>. Move a tag with its words, because word order is different in each language. Do not add or remove tags.
- Keep every {placeholder} as it is.
- Match the tone and the terms of the current translation below. PostHog's voice is casual, direct, and a little funny.
- An item with "previous_english" and "current_translation" has new English text. Change the current translation only as much as the English change needs.
- Return one translation for each item, with the same key.

Current translation, for tone and terms:
${stringify(locale.messages, { lineWidth: 0 })}`

    const translations: Messages = {}
    for (let i = 0; i < items.length; i += BATCH_SIZE) {
        const response = await createMessage(apiKey, {
            model: MODEL,
            max_tokens: 16000,
            // If a safety classifier declines the request, the API runs it again on a fallback model.
            fallbacks: 'default',
            system: [{ type: 'text', text: system, cache_control: { type: 'ephemeral' } }],
            messages: [{ role: 'user', content: JSON.stringify(items.slice(i, i + BATCH_SIZE), null, 2) }],
            output_config: { format: { type: 'json_schema', schema: OUTPUT_SCHEMA } },
        })

        if (response.stop_reason === 'refusal') throw new Error(`Claude declined the ${locale.lang} request`)
        const text = response.content.find((block: { type: string }) => block.type === 'text')?.text
        if (!text) throw new Error(`Claude returned no text for ${locale.lang} (stop reason: ${response.stop_reason})`)
        for (const { key, text: translation } of JSON.parse(text).translations) translations[key] = translation
    }
    return translations
}

// Plain fetch keeps the script free of new dependencies. Retries rate limits and server errors.
async function createMessage(apiKey: string, body: Record<string, unknown>) {
    for (let attempt = 1; ; attempt++) {
        const response = await fetch('https://api.anthropic.com/v1/messages', {
            method: 'POST',
            headers: {
                'content-type': 'application/json',
                'x-api-key': apiKey,
                'anthropic-version': '2023-06-01',
                'anthropic-beta': 'server-side-fallback-2026-07-01',
            },
            body: JSON.stringify(body),
        })
        if (response.ok) return response.json()
        const retry = response.status === 429 || response.status >= 500
        if (!retry || attempt === 4) throw new Error(`Anthropic API ${response.status}: ${await response.text()}`)
        await new Promise((resolve) => setTimeout(resolve, 2 ** attempt * 5000))
    }
}

async function sync(code: string, apiKey: string | null) {
    const locale = readLocale(code)
    const snapshot = readSnapshot(code, locale.messages)

    const removed = Object.keys(locale.messages).filter((key) => !(key in englishMessages))
    const todo = translatable.filter((key) => !(key in locale.messages) || snapshot[key] !== englishMessages[key])
    const log = (message: string) => console.log(`[${code}] ${message}`)
    log(`${todo.length} to translate, ${removed.length} to remove`)
    todo.forEach((key) => log(`  ~ ${key}`))
    removed.forEach((key) => log(`  - ${key}`))
    if (!apiKey) return

    // A renamed or moved key keeps its translation when its English text is the same.
    const known = new Map<string, string>()
    for (const [key, translation] of Object.entries(locale.messages)) {
        if (snapshot[key] !== undefined) known.set(snapshot[key], translation)
    }

    const done: Messages = {}
    let pending: Item[] = []
    for (const key of todo) {
        const reused = known.get(englishMessages[key])
        if (reused !== undefined && markup(reused) === markup(englishMessages[key])) {
            done[key] = reused
        } else {
            const changed = key in locale.messages && snapshot[key] !== undefined
            pending.push({
                key,
                english: englishMessages[key],
                ...(changed && { previous_english: snapshot[key], current_translation: locale.messages[key] }),
            })
        }
    }

    // One retry for translations that lose or add a tag or placeholder.
    for (let attempt = 0; attempt < 2 && pending.length; attempt++) {
        const translations = await translate(apiKey, locale, pending)
        pending = pending.filter(({ key }) => {
            const translation = translations[key]
            if (translation === undefined || markup(translation) !== markup(englishMessages[key])) return true
            done[key] = translation
            return false
        })
    }
    const failed = pending.map(({ key }) => key)

    const { doc } = locale
    for (const [key, translation] of Object.entries(done)) setKey(doc, key, translation)
    // A failed key shows English until the next run tries it again.
    for (const key of [...removed, ...failed]) doc.deleteIn(yamlPath(key))
    // Every key and map that the file had before this run.
    const existing = new Set(
        Object.keys(locale.messages).flatMap((key) =>
            key.split('.').map((_, i, parts) => parts.slice(0, i + 1).join('.'))
        )
    )
    tidy(doc.get('messages') as YAMLMap, existing)
    fs.writeFileSync(localeFile(code), doc.toString({ indent: 4, lineWidth: 0, singleQuote: true }))

    const next: Messages = {
        ...snapshot,
        ...Object.fromEntries(Object.keys(done).map((key) => [key, englishMessages[key]])),
    }
    Object.keys(next).forEach((key) => (!(key in englishMessages) || failed.includes(key)) && delete next[key])
    writeSnapshot(code, next)

    log(`${Object.keys(done).length} translated, ${removed.length} removed, ${failed.length} failed`)
    if (args.summary) {
        const lines = [
            ...Object.keys(done).map((key) => `- \`${key}\``),
            ...removed.map((key) => `- \`${key}\` (removed)`),
            ...failed.map((key) => `- \`${key}\` (not translated: the tags or placeholders did not match)`),
        ]
        fs.writeFileSync(args.summary, lines.join('\n') + '\n')
    }
}

function check(): boolean {
    let ok = true
    for (const code of codes) {
        const { messages } = readLocale(code)
        for (const [key, translation] of Object.entries(messages)) {
            if (!(key in englishMessages)) {
                console.error(`${code}.yml: ${key} is not in en.yml`)
                ok = false
            } else if (markup(translation) !== markup(englishMessages[key])) {
                console.error(
                    `${code}.yml: ${key} has "${markup(translation)}" but en.yml has "${markup(englishMessages[key])}"`
                )
                ok = false
            }
        }
    }
    return ok
}

function report(ref: string, code: string): string {
    const { name, messages } = readLocale(code)
    let base: Messages = {}
    try {
        const raw = execFileSync('git', ['show', `${ref}:src/i18n/locales/${code}.yml`], { encoding: 'utf8' })
        base = flattenMessages(parse(raw).messages ?? {})
    } catch {
        // The locale is new on this branch.
    }

    const cell = (text = '') => (text ? `\`${text.replace(/\|/g, '\\|').replace(/`/g, "'")}\`` : '')
    const changed = englishKeys.filter((key) => key in messages && messages[key] !== base[key])
    const removed = Object.keys(base).filter((key) => !(key in messages))
    const missing = translatable.filter((key) => !(key in messages))

    // GitHub rejects a PR body over 65,536 characters. A home page revamp can change every key.
    const rows = changed.map(
        (key) => `| \`${key}\` | ${cell(englishMessages[key])} | ${cell(base[key])} | ${cell(messages[key])} |`
    )
    while (rows.join('\n').length > 50000) rows.pop()
    if (rows.length < changed.length) {
        rows.push(`| … | ${changed.length - rows.length} more keys. See **Files changed**. | | |`)
    }

    return [
        `This PR updates the ${name} (\`${code}\`) translation of the home page to match \`en.yml\`. A workflow opens it after the English text changes. An AI agent wrote the new text, so **a native speaker must review it before it merges.**`,
        '',
        '### How to review',
        '',
        `1. Open **Files changed** and go to \`src/i18n/locales/${code}.yml\`.`,
        '2. On a line that is wrong, click **+**, then **Add a suggestion**, and write the correct text.',
        '3. When you are done, click **Review changes**, then **Comment** or **Approve**.',
        '',
        `Keep product names, brand names, code, and URLs in English. Keep the tags, such as \`<highlight>…</highlight>\`, and the \`{placeholders}\`. [Full guide](${README_URL}).`,
        '',
        `### Changed keys (${changed.length})`,
        '',
        '| Key | English | Before | After |',
        '|---|---|---|---|',
        ...rows,
        ...(removed.length
            ? ['', `### Removed keys (${removed.length})`, '', ...removed.map((key) => `- \`${key}\``)]
            : []),
        ...(missing.length
            ? [
                  '',
                  `### Not translated (${missing.length})`,
                  '',
                  'The page shows English for these keys. The workflow tries them again after the next change to `en.yml`.',
                  '',
                  ...missing.map((key) => `- \`${key}\``),
              ]
            : []),
    ].join('\n')
}

function fail(message: string): never {
    console.error(message)
    process.exit(1)
}

if (args.check) {
    if (!check()) fail('i18n check failed. See src/i18n/README.md.')
    console.log(`i18n check passed for ${codes.join(', ')}`)
} else if (args.report) {
    if (!args.locale) fail('--report needs --locale')
    console.log(report(args.report, args.locale))
} else if (args.init) {
    for (const code of codes.filter((code) => !fs.existsSync(sourceFile(code)))) {
        writeSnapshot(code, readSnapshot(code, readLocale(code).messages))
        console.log(`[${code}] wrote .source/${code}.yml`)
    }
} else {
    const apiKey = args['dry-run']
        ? null
        : process.env.ANTHROPIC_API_KEY || fail('Set ANTHROPIC_API_KEY, or use --dry-run')
    for (const code of codes) await sync(code, apiKey)
}
