export const amplitude = {
    name: 'Amplitude',
    key: 'amplitude',
    assets: {
        icon: '/images/competitors/amplitude.svg',
        comparisonArticle: '/blog/posthog-vs-amplitude',
    },
    products: {
        product_analytics: {
            available: true,
            features: {
                ready_made_insight_types: true,
                sql_mode: 'Exports only',
                conversion_funnels: true,
                historical_trends: true,
                time_to_convert_insights: true,
                sequential_step_order: true,
                strict_step_order: true,
                any_step_order: true,
                exclusion_events: true,
                conversion_windows: true,
                reveal_user_paths_between_steps: true,
                anomaly_detection: true,
                filter_internal_and_test_users: false,
                filter_by_cohort: true,
                filter_by_person_property: true,
                breakdown_by_person_property: true,
                correlation_analysis: true,
                reveal_paths_from_a_start_point: true,
                reveal_paths_from_an_end_point: true,
                reveal_paths_between_points: false,
                reveal_paths_within_funnels: true,
                zoom_in_out: true,
                track_pageviews: true,
                track_custom_events: true,
                filter_by_events_or_person_property: true,
                hide_repeating_steps: true,
                max_number_of_steps: '50',
                user_level_permissions: true,
                project_level_permissions: true,
                dashboard_level_permissions: true,
                pinned_dashboards: true,
                share_dashboards_externally: false,
                subscribe_to_dashboards: false,
                embed_dashboards_anywhere: false,
                annotations: true,
                dashboard_insight_tags: true,
                private_insights: false,
            },
        },
        web_analytics: {
            available: true,
        },
        session_replay: {
            available: true,
        },
        feature_flags: {
            available: true,
        },
        experiments: {
            available: true,
            features: {
                unlimited_experiments: true,
                multivariate_experiments: true,
                secondary_metrics: true,
                minimum_metrics: true,
                duration_prediction: false,
                cross_domain_experiments: false,
                traffic_allocation: false,
                target_by_cohort: true,
                target_by_person_property: true,
                bayesian_statistics: false,
                check_results_anytime: false,
                group_level_experiments: false,
                integrated_session_replay: false,
                shared_metrics_library: false,
            },
        },
        surveys: {
            available: true,
        },
        revenue_analytics: {
            available: true,
            features: {
                revenue_tracking: true,
                event_based_revenue_tracking: true,
                native_multi_source_revenue_tracking: false,
                deferred_revenue: false,
                product_analytics_integration: true,
                multi_currency_support: false,
                revenue_prediction: false,
                sql_access: false,
            },
        },
        product_tours: {
            available: true,
        },
    },
    platform: {
        open_source: false,
        self_host: false,
        usage_based_pricing: true,
        transparent_pricing: false,
        free_tier: true,
        built_in_analytics: true,
    },
    pricing: {
        model: 'Usage-based + taxes',
    },
}
