export const amplitude = {
    name: 'Amplitude',
    key: 'amplitude',
    assets: {
        icon: '/images/competitors/amplitude.svg',
        comparisonArticle: '/blog/posthog-vs-amplitude',
    },
    products: {
        product_analytics: {
            pricing: {
                free_tier: '50k tracked users (Starter plan only)',
            },
            available: true,
            features: {
                anomaly_detection: true,
                any_step_order: true,
                autocapture: true,
                breakdown_by_person_property: true,
                conversion_funnels: true,
                conversion_windows: true,
                correlation_analysis: true,
                exclusion_events: true,
                filter_by_cohort: true,
                filter_by_events_or_person_property: true,
                filter_by_person_property: true,
                filter_internal_and_test_users: false,
                hide_repeating_steps: true,
                historical_trends: true,
                max_number_of_steps: '50',
                private_insights: false,
                project_level_permissions: true,
                ready_made_insight_types: true,
                reveal_paths_between_points: false,
                reveal_paths_from_a_start_point: true,
                reveal_paths_from_an_end_point: true,
                reveal_paths_within_funnels: true,
                reveal_user_paths_between_steps: true,
                sequential_step_order: true,

                strict_step_order: true,
                time_to_convert_insights: true,
                track_custom_events: true,
                track_pageviews: true,
                user_level_permissions: true,
                zoom_in_out: true,
                insights: {
                    available: true,
                    features: {
                        // ready_made_insight_types: true,
                        sql_editor: 'Add-on',
                        formula_mode: 'Growth plan or higher',
                        // sampling: true,
                    },
                },
                trends: {
                    available: true,
                    features: {
                        visualization_options: false,
                        another_feature: true,
                    },
                },
                funnels: {
                    available: true,
                    features: {},
                    conversion_funnels: true,
                    conversion_windows: true,
                    correlation_analysis: true,
                    exclusion_events: true,
                    filter_by_cohort: true,
                    filter_by_events_or_person_property: true,
                    filter_by_person_property: true,
                    filter_internal_and_test_users: false,
                    hide_repeating_steps: true,
                    historical_trends: true,
                    max_number_of_steps: '50',
                    private_insights: false,
                    project_level_permissions: true,
                    ready_made_insight_types: true,
                    reveal_paths_between_points: false,
                    reveal_paths_from_a_start_point: true,
                    reveal_paths_from_an_end_point: true,
                    reveal_paths_within_funnels: true,
                    reveal_user_paths_between_steps: true,
                },
                user_paths: {
                    available: true,
                    features: {
                        reveal_paths_between_points: false,
                        reveal_paths_from_a_start_point: true,
                        reveal_paths_from_an_end_point: true,
                        reveal_paths_within_funnels: true,
                        reveal_user_paths_between_steps: true,
                    },
                },
                group_analytics: {
                    available: 'Paid add-on',
                    features: {},
                },
            },
        },
        dashboards: {
            available: true,
            features: {
                annotations: true,
                dashboard_level_permissions: true,
                dashboard_tags: true,
                embed_dashboards: false,
                pinned_dashboards: true,
                private_insights: false,
                project_level_permissions: true,
                share_dashboards_externally: false,
                subscribe_to_dashboards: false,
                user_level_permissions: true,
            },
        },
        web_analytics: {
            available: true,
        },
        session_replay: {
            available: true,
            pricing: {
                free_tier: '1,000 recordings',
            },
            features: {
                web_app_recordings: true,
                mobile_app_recordings: true,
                ios_recordings: true,
                android_recordings: true,
                react_native_recordings: false,
                flutter_recordings: false,
                heatmaps: true,
                console_logs: false,
                performance_monitoring: false,
                dom_explorer: false,
                ai_summaries: false,
                conditional_recording: false,
                target_by_url: true,
                target_by_sample: false,
                target_by_feature_flag: false,
                filter_by_user_or_event: true,
                search_by_network: false,
                playlists: false,
                rage_click_detection: true,
                privacy_masking: true,
                export_to_json: false,
                export_to_video: false,
                retention_policy: true,
                identity_detection: true,
            },
        },
        feature_flags: {
            available: true,
            pricing: {
                free_tier: '50k tracked users',
            },
            features: {
                boolean_flags: true,
                multivariate_flags: true,
                json_payloads: true,
                release_conditions: true,
                local_evaluation: true,
                bootstrapping: true,
                api_access: true,
                sdk_support: true,
                target_by_percentage: true,
                target_by_person_properties: true,
                target_by_cohorts: true,
                geographic_targeting: true,
                group_targeting: false,
                flag_scheduling: true,
                instant_rollbacks: true,
                history_activity: true,
                flag_administration: true,
                multi_environment: false,
                flag_overrides: false,
                toolbar_integration: false,
                user_assignment: false,
                experimentation: true,
                correlation_analysis: false,
                persist_across_auth: false,
                early_access_widget: false,
                automated_reports: false,
                ip_resolution: false,
            },
        },
        experiments: {
            available: true,
            pricing: {
                free_tier: 'None',
            },
            features: {
                funnel_metrics: true,
                count_value_metrics: true,
                ratio_metrics: false,
                custom_goals: true,
                secondary_metrics: true,
                primary_secondary_metrics: true,
                shared_metrics_library: false,
                ab_testing: true,
                aa_testing: false,
                abn_testing: true,
                holdout_testing: true,
                fake_door_testing: false,
                redirect_testing: false,
                cohort_integration: true,
                geographic_targeting: true,
                percentage_rollouts: true,
                group_level_experiments: false,
                holdouts: true,
                exclusion_rules: false,
                feature_flag_foundation: true,
                json_payloads: false,
                multivariate_testing: true,
                api_access: true,
                statistical_significance: true,
                results_visualization: true,
                side_effect_monitoring: true,
                statistics_engine: 'Sequential',
                web: true,
                mobile: true,
            },
        },
        surveys: {
            available: true,
            pricing: {
                free_tier: 'n/a',
            },
            features: {
                multiple_choice: true,
                multi_select: true,
                rating: true,
                emoji_reaction: true,
                embedded_links: false,
                freeform_text: true,
                survey_templates: true,
                nps_surveys: true,
                csat_surveys: false,
                user_interview_requests: false,
                display_conditions: true,
                event_triggered: true,
                custom_targeting: true,
                popover: true,
                feedback_button: true,
                hosted_surveys: true,
                custom_ui: true,
                iframe_embedding: true,
                multi_step_surveys: true,
                conditional_logic: true,
                link_to_webpage: true,
                calendar_invites: false,
                slack_integration: true,
                cdp_destinations: false,
                no_code: false,
                api_access: false,
                sdk_support: false,
                capture_partial_responses: false,
                completion_conditions: false,
                customizable_wait_periods: false,
                aggregated_results: false,
                automatic_nps_calculation: false,
            },
        },
        revenue_analytics: {
            available: true,
            features: {
                revenue_tracking: true,
                event_based_revenue_tracking: true,
                native_multi_source_revenue_tracking: false,
                deferred_revenue: false,
                product_analytics_integration: true,
                multi_currency_support: false,
                revenue_prediction: false,
                sql_access: false,
            },
        },
        product_tours: {
            available: true,
        },
    },
    platform: {
        deployment: {
            open_source: false,
            self_host: false,
        },
        pricing: {
            usage_based_pricing: true,
            transparent_pricing: false,
            free_tier: true,
        },
        integrations: {
            imports: true,
            exports: true,
            segment: true,
            zapier: false,
            sentry: false,
            zendesk: false,
            slack: true,
            microsoft_teams: true,
            community_integrations: false,
            google_ads: true,
            ci_cd_integrations: false,
        },
        analytics_integration: {
            built_in_analytics: true,
        },
        security: {
            user_privacy_options: true,
            history_audit_logs: true,
            gdpr_ready: true,
            hipaa_ready: true,
            soc2_certified: true,
            two_factor_auth: true,
            saml_sso: 'Enterprise',
        },
    },
    pricing: {
        model: 'Usage-based + taxes',
    },
}
