export const clarity = {
    name: 'Clarity',
    key: 'clarity',
    assets: {
        icon: '/images/competitors/clarity.svg',
    },
    products: {
        session_replay: {
            available: true,
            beta: false,
            pricing: {
                free_tier: true,
            },
            features: {
                ai_summaries: true,
                android_recordings: true,
                canvas_recording: false,
                chat_with_recordings: false,
                clickmaps: false,
                conditional_recording: false,
                console_logs: false,
                dom_explorer: false,
                event_timeline: false,
                export_to_json: false,
                export_to_video: false,
                filter_by_user_or_event: true,
                flutter_recordings: true,
                heatmaps: false,
                identity_detection: true,
                ios_recordings: true,
                iframe_recording: false,
                minimum_duration: false,
                mobile_app_recordings: true,
                movement_maps: false,
                network_monitor: false,
                notes_on_replays: false,
                performance_monitoring: false,
                playlists: false,
                privacy_masking: true,
                rage_click_detection: true,
                react_native_recordings: true,
                retention_policy: '30 days',
                screenshot_mode: false,
                scrollmaps: false,
                search_by_network: false,
                share_replays: false,
                single_page_app: true,
                target_by_feature_flag: false,
                target_by_sample: true,
                target_by_url: true,
                web_app_recordings: true,
                wireframe_mode: false,
            },
        },
    },
    platform: {
        deployment: {
            open_source: false,
            self_host: false,
        },
        pricing: {
            free_tier: true,
            transparent_pricing: true,
            usage_based_pricing: false,
        },
        integrations: {
            azure_blob: false,
            bigquery: false,
            community_integrations: false,
            customer_io: false,
            exports: false,
            gcs: false,
            google_ads: false,
            hubspot: false,
            imports: false,
            intercom: false,
            microsoft_teams: false,
            redshift: false,
            s3: false,
            salesforce: false,
            segment: false,
            slack: false,
            snowflake: false,
            sentry: false,
            zapier: false,
            zendesk: false,
        },
        security: {
            cookieless_tracking: false,
            data_anonymization: false,
            gdpr_ready: false,
            hipaa_ready: false,
            history_audit_logs: false,
            saml_sso: false,
            soc2_certified: false,
            two_factor_auth: false,
            user_privacy_options: false,
        },
    },
    pricing: {
        model: 'Free',
    },
}
