export const flagsmith = {
    name: 'Flagsmith',
    key: 'flagsmith',
    assets: {
        icon: '/images/competitors/flagsmith.svg',
    },
    products: {
        feature_flags: {
            available: true,
            pricing: {
                free_tier: true,
            },
            features: {
                activity_logs: true,
                api_access: false,
                automated_reports: false,
                boolean_flags: false,
                bootstrapping: false,
                correlation_analysis: false,
                custom_targeting: false,
                data_export: false,
                early_access_management: false,
                early_access_widget: false,
                experimentation: true,
                flag_administration: false,
                flag_overrides: false,
                flag_scheduling: false,
                free_third_party_plugins: true,
                geographic_targeting: false,
                group_targeting: false,
                history_activity: false,
                instant_rollbacks: false,
                ip_resolution: false,
                json_payloads: false,
                local_evaluation: false,
                multi_environment: false,
                multi_environment_support: true,
                multivariate_flags: true,
                percentage_rollouts: false,
                persist_across_auth: false,
                release_conditions: false,
                sdk_support: false,
                target_by_cohorts: false,
                target_by_percentage: true,
                target_by_person_properties: true,
                toolbar_integration: false,
                unlimited_flags_for_free: true,
                user_assignment: false,
            },
        },
    },
    platform: {
        deployment: {
            open_source: 'Open core',
            self_host: true,
        },
        pricing: {
            usage_based_pricing: true,
            transparent_pricing: true,
            free_tier: true,
        },
        developer: {
            sdks: false,
            native_data_sources: false,
            proxies: false,
            api: false,
            local_evaluation: false,
            sql: false,
        },
        integrations: {
            imports: false,
            exports: false,
            slack: false,
            microsoft_teams: false,
            zapier: false,
            sentry: false,
        },
        security: {
            user_privacy_options: false,
            history_audit_logs: false,
            gdpr_ready: false,
            hipaa_ready: false,
            soc2_certified: false,
            two_factor_auth: false,
            saml_sso: false,
        },
        analytics_integration: {
            built_in_analytics: false,
        },
    },
    pricing: {
        model: 'Usage-based',
    },
}
