export const ga4 = {
    name: 'GA4',
    key: 'ga4',
    assets: {
        icon: '/images/competitors/ga4.svg',
        comparisonArticle: '/blog/posthog-vs-ga4',
    },
    products: {
        product_analytics: {
            available: true,
            features: {
                advertising_analytics: true,
                ai_insight_builder: false,
                alerts: false,
                anomaly_detection: false,
                any_step_order: false,
                autocapture: false,
                breakdown_by_person_property: true,
                clickmaps: false,
                cohorts: true,
                conversion_funnels: true,
                conversion_windows: false,
                correlation_analysis: false,
                custom_events: true,
                custom_properties: true,
                dashboards: true,
                define_number_of_users_on_path: false,
                exclusion_events: false,
                filter_by_cohort: false,
                filter_by_events_or_person_property: false,
                filter_by_person_property: false,
                filter_internal_and_test_users: false,
                formula_mode: false,
                funnels: true,
                group_analytics: false,
                heatmaps: false,
                hide_repeating_steps: false,
                historical_trends: false,
                include_and_exclude_wildcards: false,
                lifecycle: false,
                max_number_of_steps: false,
                monetization_analytics: true,
                paths: true,
                predictive_insights: true,
                private_insights: false,
                project_level_permissions: false,
                ready_made_insight_types: true,
                real_time_view: true,
                regex_for_path_cleaning: false,
                retention: true,
                reveal_paths_between_points: false,
                reveal_paths_from_a_start_point: false,
                reveal_paths_from_an_end_point: false,
                reveal_paths_within_funnels: false,
                reveal_user_paths_between_steps: false,
                scrollmaps: false,
                sequential_step_order: false,
                sql_editor: false,
                stickiness: false,
                strict_step_order: false,
                time_to_convert_insights: false,
                toolbar: false,
                track_custom_events: true,
                track_pageviews: true,
                traffic_breakdown: true,
                trends: true,
                user_level_permissions: false,
                user_paths: true,
                user_profiles: true,
                utm_tracking: true,
                insights: {
                    available: true,
                    features: {
                        formula_mode: false,
                        ready_made_insight_types: true,
                        sampling: false,
                        sql_editor: false,
                    },
                },
            },
        },
        web_analytics: {
            available: true,
            features: {
                advertising_analytics: false,
                bounce_rate: false,
                bounce_rate_tracking: true,
                breakdown_by_device_and_browser: true,
                breakdown_by_geoip: true,
                clickmaps: false,
                conversions: false,
                cookieless_tracking: true,
                custom_channel_types: false,
                entry_exit_paths: false,
                first_party_cookies: true,
                heatmaps: false,
                hipaa_compliance: false,
                integration_with_feature_flags: false,
                integration_with_session_replay: false,
                integration_with_surveys: false,
                migration: false,
                movement_maps: false,
                open_source: false,
                outbound_clicks: false,
                pageviews: false,
                pre_configured_dashboards: true,
                real_time_reporting: true,
                revenue_tracking: true,
                script_size: false,
                scrollmaps: false,
                session_and_duration_tracking: true,
                sessions: false,
                snippet_install: false,
                traffic_breakdown: false,
                utm_tracking: false,
                visitor_and_view_tracking: true,
                web_vitals: false,
                web_vitals_reporting: true,
            },
        },
        session_replay: {
            available: false,
        },
        feature_flags: {
            available: false,
        },
        experiments: {
            available: false,
        },
        surveys: {
            available: false,
        },
        cdp: {
            available: false,
        },
        data_warehouse: {
            available: false,
        },
        dashboards: {
            available: true,
        },
    },
    platform: {
        analytics_integration: {
            built_in_analytics: false,
        },
        deployment: {
            eu_hosting: false,
            open_source: false,
            self_host: false,
        },
        developer: {
            api: false,
            mobile_sdks: false,
            server_side_sdks: false,
        },
        integrations: {
            bigquery: true,
            customer_io: false,
            google_ads: true,
            hubspot: false,
            intercom: false,
            salesforce: false,
            sentry: false,
            stripe: true,
            zapier: true,
        },
        pricing: {
            free_tier: true,
            transparent_pricing: false,
            usage_based_pricing: false,
        },
        security: {
            data_anonymization: true,
            gdpr_ready: false,
            hipaa_ready: false,
            saml_sso: true,
            soc2_certified: false,
            two_factor_auth: true,
        },
    },
    pricing: {
        model: 'Free',
    },
}
