export const growthbook = {
    name: 'GrowthBook',
    key: 'growthbook',
    assets: {
        icon: '/images/competitors/growthbook.svg',
        comparisonArticle: '/blog/posthog-vs-growthbook',
    },
    products: {
        feature_flags: {
            available: true,
            pricing: {
                free_tier: true,
            },
            features: {
                activity_logs: false,
                api_access: false,
                automated_reports: false,
                boolean_flags: true,
                bootstrapping: false,
                correlation_analysis: false,
                custom_targeting: true,
                data_export: true,
                early_access_management: false,
                early_access_widget: false,
                experimentation: true,
                flag_administration: false,
                flag_overrides: false,
                flag_scheduling: true,
                free_third_party_plugins: false,
                geographic_targeting: false,
                group_targeting: false,
                history_activity: false,
                instant_rollbacks: false,
                ip_resolution: false,
                json_payloads: true,
                local_evaluation: false,
                multi_environment: true,
                multi_environment_support: true,
                multivariate_flags: false,
                percentage_rollouts: true,
                persist_across_auth: false,
                release_conditions: false,
                sdk_support: false,
                target_by_cohorts: false,
                target_by_percentage: true,
                target_by_person_properties: true,
                toolbar_integration: false,
                unlimited_flags_for_free: true,
                user_assignment: false,
            },
        },
        experiments: {
            available: true,
            pricing: {
                free_tier: true,
            },
            features: {
                aa_testing: false,
                ab_testing: false,
                abn_testing: false,
                api_access: false,
                bayesian_statistics: true,
                check_results_anytime: false,
                cohort_integration: false,
                count_value_metrics: false,
                cross_domain_experiments: false,
                custom_goals: true,
                duration_prediction: false,
                dynamic_cohorts: false,
                exclusion_rules: false,
                experiment_analysis: false,
                fake_door_testing: false,
                feature_flag_foundation: false,
                funnel_metrics: false,
                geographic_targeting: false,
                group_level_experiments: false,
                holdout_testing: false,
                holdouts: false,
                integrated_session_replay: false,
                json_payloads: false,
                minimum_metrics: false,
                mobile: false,
                multivariate_experiments: false,
                multivariate_testing: true,
                namespaces: true,
                native_goal_tracking: false,
                no_code_experiments: false,
                percentage_rollouts: false,
                primary_secondary_metrics: false,
                ratio_metrics: false,
                recommended_run_time: false,
                redirect_testing: false,
                results_visualization: false,
                secondary_metrics: true,
                shared_metrics_library: false,
                side_effect_monitoring: false,
                split_testing: true,
                statistical_significance: true,
                statistics_engine: 'Bayesian, Frequentist',
                target_by_cohort: false,
                target_by_person_property: false,
                traffic_allocation: false,
                unlimited_experiments: false,
                visual_editor: true,
                web: false,
            },
        },
        product_analytics: {
            available: false,
        },
        session_replay: {
            available: false,
        },
        web_analytics: {
            available: false,
        },
        dashboards: {
            available: false,
        },
    },
    platform: {
        deployment: {
            open_source: true,
            self_host: true,
        },
        developer: {
            api: 'Beta',
            local_evaluation: true,
            native_data_sources: false,
            proxies: true,
            sdks: '11',
            sql: true,
        },
        pricing: {
            free_tier: true,
            transparent_pricing: true,
            usage_based_pricing: false,
        },
        integrations: {
            exports: false,
            imports: false,
            microsoft_teams: false,
            sentry: false,
            slack: false,
            zapier: false,
        },
        security: {
            gdpr_ready: false,
            hipaa_ready: false,
            history_audit_logs: false,
            saml_sso: false,
            soc2_certified: false,
            two_factor_auth: false,
            user_privacy_options: false,
        },
        analytics_integration: {
            built_in_analytics: false,
        },
    },
    pricing: {
        model: 'Seat-based',
    },
}
