export const heap = {
    name: 'Heap',
    key: 'heap',
    assets: {
        icon: '/images/competitors/heap.svg',
        comparisonArticle: '/blog/posthog-vs-heap',
    },
    products: {
        product_analytics: {
            available: true,
            pricing: {
                free_tier: '10k monthly tracked users',
            },
            features: {
                advertising_analytics: false,
                ai_insight_builder: true,
                alerts: false,
                anomaly_detection: false,
                any_step_order: false,
                autocapture: true,
                breakdown_by_person_property: true,
                clickmaps: false,
                cohorts: true,
                conversion_funnels: true,
                conversion_windows: true,
                correlation_analysis: true,
                custom_events: true,
                custom_properties: true,
                dashboards: true,
                define_number_of_users_on_path: false,
                exclusion_events: true,
                filter_by_cohort: true,
                filter_by_events_or_person_property: true,
                filter_by_person_property: true,
                filter_internal_and_test_users: false,
                formula_mode: false,
                funnels: true,
                group_analytics: true,
                heatmaps: false,
                hide_repeating_steps: false,
                historical_trends: true,
                include_and_exclude_wildcards: false,
                lifecycle: true,
                max_number_of_steps: '10',
                monetization_analytics: false,
                paths: true,
                predictive_insights: false,
                private_insights: true,
                project_level_permissions: true,
                ready_made_insight_types: true,
                real_time_view: false,
                regex_for_path_cleaning: false,
                retention: true,
                reveal_paths_between_points: false,
                reveal_paths_from_a_start_point: true,
                reveal_paths_from_an_end_point: true,
                reveal_paths_within_funnels: true,
                reveal_user_paths_between_steps: true,
                scrollmaps: false,
                sequential_step_order: true,
                sql_editor: 'Exports only',
                stickiness: false,
                strict_step_order: false,
                time_to_convert_insights: false,
                toolbar: false,
                track_custom_events: true,
                track_pageviews: true,
                traffic_breakdown: false,
                trends: true,
                user_level_permissions: true,
                user_paths: true,
                user_profiles: true,
                utm_tracking: false,
                insights: {
                    available: true,
                    features: {
                        formula_mode: false,
                        ready_made_insight_types: true,
                        sampling: false,
                        sql_editor: 'Exports only',
                    },
                },
            },
        },
        web_analytics: {
            available: true,
        },
        session_replay: {
            available: true,
            pricing: {
                free_tier: 'Limited trial',
            },
            features: {
                ai_summaries: false,
                android_recordings: false,
                canvas_recording: false,
                chat_with_recordings: false,
                clickmaps: false,
                conditional_recording: false,
                console_logs: false,
                dom_explorer: false,
                event_timeline: false,
                export_to_json: false,
                export_to_video: false,
                filter_by_user_or_event: false,
                flutter_recordings: false,
                heatmaps: false,
                identity_detection: true,
                ios_recordings: false,
                iframe_recording: false,
                minimum_duration: false,
                mobile_app_recordings: true,
                movement_maps: false,
                network_monitor: true,
                notes_on_replays: false,
                performance_monitoring: false,
                playlists: false,
                privacy_masking: false,
                rage_click_detection: false,
                react_native_recordings: false,
                retention_policy: false,
                screenshot_mode: false,
                scrollmaps: false,
                search_by_network: false,
                share_replays: false,
                single_page_app: false,
                target_by_feature_flag: false,
                target_by_sample: false,
                target_by_url: false,
                web_app_recordings: true,
                wireframe_mode: false,
            },
        },
        feature_flags: {
            available: false,
        },
        experiments: {
            available: false,
        },
        surveys: {
            available: false,
        },
        cdp: {
            available: false,
        },
        data_warehouse: {
            available: false,
        },
        error_tracking: {
            available: false,
        },
        dashboards: {
            available: true,
        },
        heatmaps: {
            available: true,
        },
    },
    platform: {
        deployment: {
            open_source: false,
            self_host: false,
        },
        pricing: {
            free_tier: true,
            transparent_pricing: false,
            usage_based_pricing: true,
        },
        analytics_integration: {
            built_in_analytics: true,
        },
        developer: {
            api: false,
            local_evaluation: false,
            proxies: false,
            sdks: false,
            sql: false,
        },
        integrations: {
            ci_cd_integrations: false,
            community_integrations: false,
            exports: false,
            google_ads: false,
            imports: false,
            microsoft_teams: false,
            segment: false,
            sentry: false,
            slack: false,
            zapier: false,
            zendesk: false,
        },
        security: {
            gdpr_ready: false,
            hipaa_ready: false,
            history_audit_logs: false,
            saml_sso: false,
            soc2_certified: false,
            two_factor_auth: false,
            user_privacy_options: false,
        },
    },
    pricing: {
        model: 'Usage-based',
    },
}
