export const hotjar = {
    name: 'Hotjar',
    key: 'hotjar',
    assets: {
        icon: '/images/competitors/hotjar.svg',
        comparisonArticle: '/blog/posthog-vs-hotjar',
    },
    products: {
        product_analytics: {
            available: true,
            features: {
                advertising_analytics: false,
                ai_insight_builder: false,
                alerts: false,
                anomaly_detection: false,
                any_step_order: false,
                autocapture: false,
                breakdown_by_person_property: false,
                clickmaps: true,
                cohorts: false,
                conversion_funnels: true,
                conversion_windows: false,
                correlation_analysis: false,
                custom_events: true,
                custom_properties: true,
                dashboards: true,
                define_number_of_users_on_path: false,
                exclusion_events: false,
                filter_by_cohort: false,
                filter_by_events_or_person_property: false,
                filter_by_person_property: false,
                filter_internal_and_test_users: false,
                formula_mode: false,
                funnels: true,
                group_analytics: false,
                heatmaps: true,
                hide_repeating_steps: false,
                historical_trends: false,
                include_and_exclude_wildcards: false,
                lifecycle: false,
                max_number_of_steps: false,
                monetization_analytics: false,
                paths: false,
                predictive_insights: false,
                private_insights: false,
                project_level_permissions: false,
                ready_made_insight_types: false,
                real_time_view: false,
                regex_for_path_cleaning: false,
                retention: false,
                reveal_paths_between_points: false,
                reveal_paths_from_a_start_point: false,
                reveal_paths_from_an_end_point: false,
                reveal_paths_within_funnels: false,
                reveal_user_paths_between_steps: false,
                scrollmaps: true,
                sequential_step_order: false,
                sql_editor: false,
                stickiness: false,
                strict_step_order: false,
                time_to_convert_insights: false,
                toolbar: false,
                track_custom_events: true,
                track_pageviews: false,
                traffic_breakdown: false,
                trends: true,
                user_level_permissions: false,
                user_paths: false,
                user_profiles: false,
                utm_tracking: false,
                insights: {
                    available: true,
                    features: {
                        formula_mode: false,
                        ready_made_insight_types: false,
                        sampling: false,
                        sql_editor: false,
                    },
                },
            },
        },
        web_analytics: {
            available: false,
        },
        session_replay: {
            available: true,
            pricing: {
                free_tier: true,
            },
            features: {
                ai_summaries: false,
                android_recordings: false,
                canvas_recording: false,
                chat_with_recordings: false,
                clickmaps: false,
                conditional_recording: false,
                console_logs: true,
                dom_explorer: false,
                event_timeline: false,
                export_to_json: false,
                export_to_video: false,
                filter_by_user_or_event: false,
                flutter_recordings: false,
                heatmaps: false,
                identity_detection: false,
                ios_recordings: false,
                iframe_recording: false,
                minimum_duration: false,
                mobile_app_recordings: false,
                movement_maps: false,
                network_monitor: false,
                notes_on_replays: false,
                performance_monitoring: false,
                playlists: false,
                privacy_masking: false,
                rage_click_detection: false,
                react_native_recordings: false,
                retention_policy: false,
                screenshot_mode: false,
                scrollmaps: false,
                search_by_network: false,
                share_replays: false,
                single_page_app: false,
                target_by_feature_flag: false,
                target_by_sample: false,
                target_by_url: false,
                web_app_recordings: true,
                wireframe_mode: false,
            },
        },
        heatmaps: {
            available: true,
            features: {
                heatmaps: true,
                clickmaps: true,
                scrollmaps: true,
                rage_clicks: true,
                save_heatmaps: true,
                toolbar: false,
            },
        },
        surveys: {
            available: true,
            features: {
                multiple_choice: true,
                popover: true,
                feedback_button: true,
                nps_surveys: true,
                csat_surveys: true,
                user_interview_requests: true,
                survey_templates: true,
                api_access: false,
            },
            presentation: {
                features: {
                    popover: true,
                    feedback_button: true,
                    hosted_surveys: true,
                },
            },
        },
        feature_flags: {
            available: false,
        },
        experiments: {
            available: false,
        },
        data_warehouse: {
            available: false,
        },
    },
    platform: {
        deployment: {
            open_source: false,
            self_host: false,
        },
        pricing: {
            free_tier: true,
            transparent_pricing: true,
            usage_based_pricing: false,
        },
        integrations: {
            azure_blob: false,
            bigquery: false,
            community_integrations: false,
            customer_io: false,
            exports: true,
            gcs: false,
            google_ads: false,
            hubspot: true,
            imports: false,
            intercom: true,
            microsoft_teams: true,
            redshift: false,
            s3: false,
            salesforce: true,
            segment: true,
            slack: true,
            snowflake: false,
            sentry: false,
            zapier: true,
            zendesk: false,
        },
        security: {
            cookieless_tracking: false,
            data_anonymization: true,
            gdpr_ready: true,
            hipaa_ready: true,
            history_audit_logs: false,
            saml_sso: false,
            soc2_certified: false,
            two_factor_auth: false,
            user_privacy_options: false,
        },
    },
    pricing: {
        model: 'Tiered subscription',
    },
}
