export const launchdarkly = {
    name: 'LaunchDarkly',
    key: 'launchdarkly',
    assets: {
        icon: '/images/competitors/launchdarkly.svg',
        comparisonArticle: '/blog/posthog-vs-launchdarkly',
    },
    products: {
        feature_flags: {
            available: true,
            pricing: {
                free_tier: false,
            },
            features: {
                activity_logs: false,
                api_access: false,
                automated_reports: false,
                boolean_flags: true,
                bootstrapping: true,
                correlation_analysis: false,
                custom_targeting: true,
                data_export: false,
                early_access_management: false,
                early_access_widget: false,
                experimentation: false,
                flag_administration: false,
                flag_overrides: false,
                flag_scheduling: 'Enterprise',
                free_third_party_plugins: false,
                geographic_targeting: false,
                group_targeting: false,
                history_activity: false,
                instant_rollbacks: false,
                ip_resolution: false,
                json_payloads: true,
                local_evaluation: false,
                multi_environment: true,
                multi_environment_support: false,
                multivariate_flags: true,
                percentage_rollouts: true,
                persist_across_auth: false,
                release_conditions: false,
                sdk_support: false,
                target_by_cohorts: false,
                target_by_percentage: false,
                target_by_person_properties: false,
                toolbar_integration: false,
                unlimited_flags_for_free: false,
                user_assignment: false,
            },
        },
        experiments: {
            available: true,
            pricing: {
                free_tier: false,
            },
            features: {
                aa_testing: false,
                ab_testing: false,
                abn_testing: false,
                api_access: false,
                bayesian_statistics: false,
                check_results_anytime: false,
                cohort_integration: false,
                count_value_metrics: false,
                cross_domain_experiments: false,
                custom_goals: true,
                duration_prediction: false,
                dynamic_cohorts: false,
                exclusion_rules: false,
                experiment_analysis: false,
                fake_door_testing: false,
                feature_flag_foundation: false,
                funnel_metrics: false,
                geographic_targeting: false,
                group_level_experiments: false,
                holdout_testing: false,
                holdouts: false,
                integrated_session_replay: false,
                json_payloads: false,
                minimum_metrics: false,
                mobile: false,
                multivariate_experiments: false,
                multivariate_testing: true,
                namespaces: false,
                native_goal_tracking: false,
                no_code_experiments: false,
                percentage_rollouts: false,
                primary_secondary_metrics: false,
                ratio_metrics: false,
                recommended_run_time: false,
                redirect_testing: false,
                results_visualization: false,
                secondary_metrics: true,
                shared_metrics_library: false,
                side_effect_monitoring: false,
                split_testing: true,
                statistical_significance: true,
                statistics_engine: false,
                target_by_cohort: false,
                target_by_person_property: false,
                traffic_allocation: false,
                unlimited_experiments: false,
                visual_editor: false,
                web: false,
            },
        },
        product_analytics: {
            available: true,
            features: {
                advertising_analytics: false,
                ai_insight_builder: false,
                alerts: false,
                anomaly_detection: false,
                any_step_order: false,
                autocapture: false,
                breakdown_by_person_property: false,
                clickmaps: false,
                cohorts: false,
                conversion_funnels: false,
                conversion_windows: false,
                correlation_analysis: false,
                custom_events: true,
                custom_properties: false,
                dashboards: false,
                define_number_of_users_on_path: false,
                exclusion_events: false,
                filter_by_cohort: false,
                filter_by_events_or_person_property: false,
                filter_by_person_property: false,
                filter_internal_and_test_users: false,
                formula_mode: false,
                funnels: false,
                group_analytics: false,
                heatmaps: false,
                hide_repeating_steps: false,
                historical_trends: false,
                include_and_exclude_wildcards: false,
                lifecycle: false,
                max_number_of_steps: false,
                monetization_analytics: false,
                paths: false,
                predictive_insights: false,
                private_insights: false,
                project_level_permissions: false,
                ready_made_insight_types: false,
                real_time_view: false,
                regex_for_path_cleaning: false,
                retention: false,
                reveal_paths_between_points: false,
                reveal_paths_from_a_start_point: false,
                reveal_paths_from_an_end_point: false,
                reveal_paths_within_funnels: false,
                reveal_user_paths_between_steps: false,
                scrollmaps: false,
                sequential_step_order: false,
                sql_editor: false,
                stickiness: false,
                strict_step_order: false,
                time_to_convert_insights: false,
                toolbar: false,
                track_custom_events: true,
                track_pageviews: false,
                traffic_breakdown: false,
                trends: true,
                user_level_permissions: false,
                user_paths: false,
                user_profiles: false,
                utm_tracking: false,
                insights: {
                    available: false,
                    features: {
                        formula_mode: false,
                        ready_made_insight_types: false,
                        sampling: false,
                        sql_editor: false,
                    },
                },
            },
        },
        session_replay: {
            available: false,
        },
        surveys: {
            available: false,
        },
        cdp: {
            available: true,
        },
        data_warehouse: {
            available: false,
        },
    },
    platform: {
        deployment: {
            open_source: 'Partial',
            self_host: false,
        },
        developer: {
            api: 'Pro',
            local_evaluation: true,
            native_data_sources: false,
            proxies: true,
            sdks: true,
            sql: false,
        },
        pricing: {
            free_tier: false,
            transparent_pricing: false,
            usage_based_pricing: true,
        },
        integrations: {
            exports: 'Enterprise',
            imports: true,
            microsoft_teams: true,
            sentry: true,
            slack: true,
            zapier: true,
        },
        security: {
            gdpr_ready: true,
            hipaa_ready: true,
            history_audit_logs: true,
            saml_sso: true,
            soc2_certified: true,
            two_factor_auth: true,
            user_privacy_options: true,
        },
        analytics_integration: {
            built_in_analytics: true,
        },
    },
    pricing: {
        model: 'Seat-based + usage',
    },
}
