export const matomo = {
    name: 'Matomo',
    key: 'matomo',
    assets: {
        icon: '/images/competitors/matomo.svg',
        comparisonArticle: '/blog/posthog-vs-matomo',
    },
    products: {
        session_replay: {
            available: true,
            beta: false,
            features: {
                ai_summaries: false,
                single_page_app: true,
                ios_recordings: false,
                android_recordings: false,
                react_native_recordings: false,
                flutter_recordings: false,
                identity_detection: true,
                target_by_url: true,
                target_by_sample: true,
                filter_by_user_or_event: true,
                search_by_network: true,
                rage_click_detection: false,
                privacy_masking: true,
                export_to_json: true,
                export_to_video: false,
                retention_policy: '24 months',
            },
        },
        web_analytics: {
            available: true,
            features: {
                pre_configured_dashboards: true,
                visitor_and_view_tracking: true,
                session_and_duration_tracking: true,
                bounce_rate_tracking: true,
                breakdown_by_geoip: true,
                breakdown_by_device_and_browser: true,
                web_vitals_reporting: 'On-premise only',
                revenue_tracking: true,
                real_time_reporting: true,
                open_source: true,
                first_party_cookies: true,
                cookieless_tracking: true,
                hipaa_compliance: true,
                gdpr_compliance: true,
                no_data_sampling: true,
                scroll_depth_tracking: false,
                custom_channel_types: false,
                integration_with_feature_flags: false,
                integration_with_session_replay: false,
                integration_with_surveys: false,
            },
        },
    },
    platform: {
        open_source: true,
        self_host: true,
        usage_based_pricing: false,
        transparent_pricing: false,
        free_tier: true,
    },
    pricing: {
        model: 'Tier-based',
    },
}
