export const matomo = {
    name: 'Matomo',
    key: 'matomo',
    assets: {
        icon: '/images/competitors/matomo.svg',
        comparisonArticle: '/blog/posthog-vs-matomo',
    },
    products: {
        product_analytics: {
            available: true,
            features: {
                advertising_analytics: false,
                ai_insight_builder: false,
                alerts: false,
                anomaly_detection: false,
                any_step_order: false,
                autocapture: false,
                breakdown_by_person_property: false,
                clickmaps: false,
                cohorts: true,
                conversion_funnels: true,
                conversion_windows: false,
                correlation_analysis: false,
                custom_events: true,
                custom_properties: true,
                dashboards: true,
                define_number_of_users_on_path: false,
                exclusion_events: false,
                filter_by_cohort: false,
                filter_by_events_or_person_property: false,
                filter_by_person_property: false,
                filter_internal_and_test_users: false,
                formula_mode: false,
                funnels: true,
                group_analytics: false,
                heatmaps: true,
                hide_repeating_steps: false,
                historical_trends: false,
                include_and_exclude_wildcards: false,
                lifecycle: false,
                max_number_of_steps: false,
                monetization_analytics: false,
                paths: true,
                predictive_insights: false,
                private_insights: false,
                project_level_permissions: false,
                ready_made_insight_types: false,
                real_time_view: false,
                regex_for_path_cleaning: false,
                retention: true,
                reveal_paths_between_points: false,
                reveal_paths_from_a_start_point: false,
                reveal_paths_from_an_end_point: false,
                reveal_paths_within_funnels: false,
                reveal_user_paths_between_steps: false,
                scrollmaps: false,
                sequential_step_order: false,
                sql_editor: 'Enterprise',
                stickiness: false,
                strict_step_order: false,
                time_to_convert_insights: false,
                toolbar: false,
                track_custom_events: true,
                track_pageviews: true,
                traffic_breakdown: false,
                trends: true,
                user_level_permissions: false,
                user_paths: true,
                user_profiles: true,
                utm_tracking: false,
                insights: {
                    available: true,
                    features: {
                        formula_mode: false,
                        ready_made_insight_types: false,
                        sampling: false,
                        sql_editor: 'Enterprise',
                    },
                },
            },
        },
        web_analytics: {
            available: true,
            features: {
                advertising_analytics: false,
                bounce_rate: true,
                bounce_rate_tracking: false,
                breakdown_by_device_and_browser: false,
                breakdown_by_geoip: false,
                clickmaps: false,
                conversions: true,
                cookieless_tracking: true,
                custom_channel_types: false,
                entry_exit_paths: true,
                first_party_cookies: false,
                heatmaps: false,
                hipaa_compliance: false,
                integration_with_feature_flags: false,
                integration_with_session_replay: false,
                integration_with_surveys: false,
                migration: false,
                movement_maps: false,
                open_source: false,
                outbound_clicks: true,
                pageviews: true,
                pre_configured_dashboards: false,
                real_time_reporting: false,
                revenue_tracking: false,
                script_size: false,
                scrollmaps: false,
                session_and_duration_tracking: false,
                sessions: true,
                snippet_install: true,
                traffic_breakdown: true,
                utm_tracking: true,
                visitor_and_view_tracking: false,
                web_vitals: false,
                web_vitals_reporting: false,
            },
        },
        session_replay: {
            available: true,
        },
        heatmaps: {
            available: true,
        },
        experiments: {
            available: true,
        },
        surveys: {
            available: false,
        },
        feature_flags: {
            available: false,
        },
    },
    platform: {
        analytics_integration: {
            built_in_analytics: false,
        },
        deployment: {
            eu_hosting: true,
            open_source: true,
            self_host: true,
        },
        developer: {
            api: true,
            mobile_sdks: true,
            server_side_sdks: true,
        },
        integrations: {
            bigquery: true,
            csv_exports: true,
            email_reports: true,
            hubspot: false,
            sentry: false,
            slack: true,
            stripe: false,
            warehouse_import: false,
            wordpress: true,
            zapier: false,
            zendesk: false,
        },
        pricing: {
            free_tier: true,
            transparent_pricing: false,
            usage_based_pricing: false,
        },
        security: {
            bot_blocking: true,
            data_anonymization: true,
            gdpr_ready: true,
            hipaa_ready: false,
            reverse_proxy: false,
            saml_sso: 'Enterprise',
            soc2_certified: false,
            two_factor_auth: true,
        },
    },
    pricing: {
        model: 'Tiered subscription',
    },
}
