export const mixpanel = {
    name: 'Mixpanel',
    key: 'mixpanel',
    assets: {
        icon: '/images/competitors/mixpanel.svg',
        comparisonArticle: '/blog/posthog-vs-mixpanel',
    },
    available: true,
    products: {
        product_analytics: {
            available: true,
            pricing: {
                free_tier: '1 million events',
            },
            features: {
                advertising_analytics: false,
                ai_insight_builder: true,
                alerts: true,
                anomaly_detection: false,
                any_step_order: true,
                autocapture: true,
                breakdown_by_person_property: true,
                clickmaps: true,
                cohorts: true,
                conversion_funnels: true,
                conversion_windows: true,
                correlation_analysis: true,
                custom_events: true,
                custom_properties: true,
                dashboards: true,
                define_number_of_users_on_path: false,
                exclusion_events: true,
                filter_by_cohort: true,
                filter_by_events_or_person_property: true,
                filter_by_person_property: true,
                filter_internal_and_test_users: false,
                formula_mode: true,
                funnels: true,
                group_analytics: true,
                heatmaps: false,
                hide_repeating_steps: true,
                historical_trends: true,
                include_and_exclude_wildcards: false,
                lifecycle: true,
                max_number_of_steps: '120+',
                monetization_analytics: false,
                paths: true,
                predictive_insights: false,
                private_insights: true,
                project_level_permissions: true,
                ready_made_insight_types: true,
                real_time_view: false,
                regex_for_path_cleaning: false,
                retention: true,
                reveal_paths_between_points: true,
                reveal_paths_from_a_start_point: true,
                reveal_paths_from_an_end_point: true,
                reveal_paths_within_funnels: true,
                reveal_user_paths_between_steps: true,
                scrollmaps: false,
                sequential_step_order: true,
                sql_editor: 'JQL only',
                stickiness: true,
                strict_step_order: false,
                time_to_convert_insights: true,
                toolbar: false,
                track_custom_events: true,
                track_pageviews: true,
                traffic_breakdown: false,
                trends: true,
                user_level_permissions: true,
                user_paths: true,
                user_profiles: true,
                utm_tracking: false,
                insights: {
                    available: true,
                    features: {
                        formula_mode: true,
                        ready_made_insight_types: true,
                        sampling: false,
                        sql_editor: 'JQL only',
                    },
                },
            },
        },
        web_analytics: {
            available: true,
            features: {
                advertising_analytics: false,
                bounce_rate: true,
                bounce_rate_tracking: false,
                breakdown_by_device_and_browser: false,
                breakdown_by_geoip: false,
                clickmaps: true,
                conversions: true,
                cookieless_tracking: false,
                custom_channel_types: true,
                entry_exit_paths: true,
                first_party_cookies: false,
                heatmaps: false,
                hipaa_compliance: false,
                integration_with_feature_flags: false,
                integration_with_session_replay: false,
                integration_with_surveys: false,
                migration: false,
                movement_maps: false,
                open_source: false,
                outbound_clicks: true,
                pageviews: true,
                pre_configured_dashboards: false,
                real_time_reporting: false,
                revenue_tracking: false,
                script_size: false,
                scrollmaps: false,
                session_and_duration_tracking: false,
                sessions: true,
                snippet_install: false,
                traffic_breakdown: true,
                utm_tracking: true,
                visitor_and_view_tracking: false,
                web_vitals: false,
                web_vitals_reporting: false,
            },
        },
        session_replay: {
            available: true,
            pricing: {
                free_tier: 'Unknown',
            },
            features: {
                ai_summaries: false,
                android_recordings: false,
                canvas_recording: false,
                chat_with_recordings: false,
                clickmaps: false,
                conditional_recording: false,
                console_logs: false,
                dom_explorer: false,
                event_timeline: true,
                export_to_json: false,
                export_to_video: false,
                filter_by_user_or_event: true,
                flutter_recordings: false,
                heatmaps: true,
                identity_detection: true,
                ios_recordings: 'Closed Beta',
                iframe_recording: false,
                minimum_duration: false,
                mobile_app_recordings: 'iOS Beta',
                movement_maps: false,
                network_monitor: false,
                notes_on_replays: false,
                performance_monitoring: false,
                playlists: false,
                privacy_masking: true,
                rage_click_detection: true,
                react_native_recordings: false,
                retention_policy: true,
                screenshot_mode: true,
                scrollmaps: false,
                search_by_network: false,
                share_replays: false,
                single_page_app: false,
                target_by_feature_flag: false,
                target_by_sample: true,
                target_by_url: true,
                web_app_recordings: true,
                wireframe_mode: false,
            },
        },
        feature_flags: {
            available: false,
        },
        experiments: {
            available: 'Analysis only',
            pricing: {
                free_tier: false,
            },
            features: {
                aa_testing: false,
                ab_testing: false,
                abn_testing: false,
                api_access: false,
                bayesian_statistics: false,
                check_results_anytime: false,
                cohort_integration: false,
                count_value_metrics: false,
                cross_domain_experiments: false,
                custom_goals: true,
                duration_prediction: false,
                dynamic_cohorts: false,
                exclusion_rules: false,
                experiment_analysis: true,
                fake_door_testing: false,
                feature_flag_foundation: false,
                funnel_metrics: false,
                geographic_targeting: false,
                group_level_experiments: false,
                holdout_testing: false,
                holdouts: false,
                integrated_session_replay: false,
                json_payloads: false,
                minimum_metrics: false,
                mobile: false,
                multivariate_experiments: false,
                multivariate_testing: false,
                namespaces: false,
                native_goal_tracking: false,
                no_code_experiments: false,
                percentage_rollouts: false,
                primary_secondary_metrics: false,
                ratio_metrics: false,
                recommended_run_time: false,
                redirect_testing: false,
                results_visualization: false,
                secondary_metrics: true,
                shared_metrics_library: false,
                side_effect_monitoring: false,
                split_testing: false,
                statistical_significance: true,
                statistics_engine: 'Frequentist',
                target_by_cohort: false,
                target_by_person_property: false,
                traffic_allocation: false,
                unlimited_experiments: false,
                visual_editor: false,
                web: false,
            },
        },
        surveys: {
            available: false,
        },
        error_tracking: {
            available: false,
        },
        llm_analytics: {
            available: false,
        },
        data_pipelines: {
            available: true,
        },
        cdp: {
            available: false,
        },
        data_warehouse: {
            available: false,
        },
        dashboards: {
            available: true,
            features: {},
        },
        revenue_analytics: {
            available: true,
            features: {
                revenue_tracking: true,
                event_based_revenue_tracking: true,
                native_multi_source_revenue_tracking: false,
                deferred_revenue: false,
                product_analytics_integration: true,
                multi_currency_support: false,
                revenue_prediction: false,
                sql_access: false,
            },
        },
    },
    platform: {
        deployment: {
            open_source: 'Libraries only',
            self_host: false,
        },
        pricing: {
            free_tier: true,
            transparent_pricing: false,
            usage_based_pricing: true,
        },
        integrations: {
            ci_cd_integrations: false,
            community_integrations: false,
            customer_io: true,
            exports: false,
            google_ads: false,
            imports: false,
            intercom: true,
            microsoft_teams: false,
            rudderstack: true,
            segment: true,
            sentry: false,
            slack: false,
            stripe: false,
            warehouse_import: true,
            zapier: true,
            zendesk: false,
        },
        security: {
            gdpr_ready: true,
            hipaa_ready: true,
            history_audit_logs: true,
            saml_sso: 'Enterprise',
            soc2_certified: true,
            two_factor_auth: true,
            user_privacy_options: true,
        },
        analytics_integration: {
            built_in_analytics: true,
        },
        developer: {
            api: false,
            local_evaluation: false,
            proxies: false,
            sdks: false,
            sql: false,
        },
    },
    pricing: {
        model: 'Usage-based',
    },
}
