export const mixpanel = {
    name: 'Mixpanel',
    key: 'mixpanel',
    assets: {
        icon: '/images/competitors/mixpanel.svg',
        comparisonArticle: '/blog/posthog-vs-mixpanel',
    },
    products: {
        revenue_analytics: {
            available: true,
            features: {
                revenue_tracking: true,
                event_based_revenue_tracking: true,
                native_multi_source_revenue_tracking: false,
                deferred_revenue: false,
                product_analytics_integration: true,
                multi_currency_support: false,
                revenue_prediction: false,
                sql_access: false,
            },
        },
        product_analytics: {
            available: true,
            features: {
                ready_made_insight_types: true,
                sql_mode: 'JQL only',
                conversion_funnels: true,
                historical_trends: true,
                time_to_convert_insights: true,
                sequential_step_order: true,
                strict_step_order: false,
                any_step_order: true,
                exclusion_events: true,
                conversion_windows: true,
                reveal_user_paths_between_steps: true,
                anomaly_detection: false,
                filter_internal_and_test_users: false,
                filter_by_cohort: true,
                filter_by_person_property: true,
                breakdown_by_person_property: true,
                correlation_analysis: false,
                reveal_paths_from_a_start_point: true,
                reveal_paths_from_an_end_point: true,
                reveal_paths_between_points: true,
                reveal_paths_within_funnels: true,
                zoom_in_out: false,
                track_pageviews: true,
                track_custom_events: true,
                filter_by_events_or_person_property: true,
                hide_repeating_steps: true,
                max_number_of_steps: '120+',
                user_level_permissions: true,
                project_level_permissions: true,
                dashboard_level_permissions: true,
                pinned_dashboards: true,
                share_dashboards_externally: true,
                subscribe_to_dashboards: true,
                embed_dashboards_anywhere: false,
                annotations: false,
                dashboard_insight_tags: false,
                private_insights: true,
            },
        },
    },
    platform: {
        open_source: false,
        self_host: false,
        usage_based_pricing: true,
        transparent_pricing: false,
        free_tier: true,
        built_in_analytics: true,
    },
    pricing: {
        model: 'Usage-based',
    },
}
