export const optimizely = {
    name: 'Optimizely',
    key: 'optimizely',
    assets: {
        icon: '/images/competitors/optimizely.svg',
        comparisonArticle: '/blog/posthog-vs-optimizely',
    },
    products: {
        experiments: {
            available: true,
            pricing: {
                free_tier: false,
            },
            features: {
                aa_testing: false,
                ab_testing: false,
                abn_testing: false,
                api_access: false,
                bayesian_statistics: false,
                check_results_anytime: false,
                cohort_integration: false,
                count_value_metrics: false,
                cross_domain_experiments: false,
                custom_goals: true,
                duration_prediction: false,
                dynamic_cohorts: false,
                exclusion_rules: false,
                experiment_analysis: false,
                fake_door_testing: false,
                feature_flag_foundation: false,
                funnel_metrics: true,
                geographic_targeting: false,
                group_level_experiments: false,
                holdout_testing: false,
                holdouts: false,
                integrated_session_replay: false,
                json_payloads: false,
                minimum_metrics: false,
                mobile: false,
                multivariate_experiments: false,
                multivariate_testing: true,
                namespaces: false,
                native_goal_tracking: false,
                no_code_experiments: true,
                percentage_rollouts: false,
                primary_secondary_metrics: false,
                ratio_metrics: false,
                recommended_run_time: false,
                redirect_testing: false,
                results_visualization: false,
                secondary_metrics: true,
                shared_metrics_library: false,
                side_effect_monitoring: false,
                split_testing: false,
                statistical_significance: true,
                statistics_engine: false,
                target_by_cohort: false,
                target_by_person_property: false,
                traffic_allocation: false,
                unlimited_experiments: false,
                visual_editor: false,
                web: false,
            },
        },
        feature_flags: {
            available: true,
            pricing: {
                free_tier: false,
            },
            features: {
                activity_logs: false,
                api_access: false,
                automated_reports: false,
                boolean_flags: true,
                bootstrapping: false,
                correlation_analysis: false,
                custom_targeting: true,
                data_export: false,
                early_access_management: false,
                early_access_widget: false,
                experimentation: false,
                flag_administration: false,
                flag_overrides: false,
                flag_scheduling: false,
                free_third_party_plugins: false,
                geographic_targeting: false,
                group_targeting: false,
                history_activity: false,
                instant_rollbacks: false,
                ip_resolution: false,
                json_payloads: false,
                local_evaluation: false,
                multi_environment: true,
                multi_environment_support: false,
                multivariate_flags: false,
                percentage_rollouts: true,
                persist_across_auth: false,
                release_conditions: false,
                sdk_support: false,
                target_by_cohorts: false,
                target_by_percentage: false,
                target_by_person_properties: false,
                toolbar_integration: false,
                unlimited_flags_for_free: false,
                user_assignment: false,
            },
        },
        product_analytics: {
            available: false,
        },
        web_analytics: {
            available: true,
        },
        session_replay: {
            available: false,
        },
        surveys: {
            available: false,
        },
    },
    platform: {
        deployment: {
            open_source: false,
            self_host: false,
        },
        developer: {
            api: true,
            local_evaluation: false,
            native_data_sources: false,
            proxies: false,
            sdks: '14',
            sql: false,
        },
        pricing: {
            free_tier: false,
            transparent_pricing: false,
            usage_based_pricing: true,
        },
        integrations: {
            exports: true,
            imports: false,
            microsoft_teams: true,
            sentry: false,
            slack: true,
            zapier: false,
        },
        security: {
            gdpr_ready: true,
            hipaa_ready: false,
            history_audit_logs: false,
            saml_sso: true,
            soc2_certified: false,
            two_factor_auth: true,
            user_privacy_options: false,
        },
        analytics_integration: {
            built_in_analytics: false,
        },
    },
    pricing: {
        model: 'Sales-driven',
    },
}
