export const optimizely = {
    name: 'Optimizely',
    key: 'optimizely',
    assets: {
        icon: '/images/competitors/optimizely.svg',
        comparisonArticle: '/blog/posthog-vs-optimizely',
    },
    products: {
        experiments: {
            available: true,
            features: {
                unlimited_experiments: true,
                multivariate_experiments: true,
                secondary_metrics: true,
                minimum_metrics: true,
                duration_prediction: false,
                cross_domain_experiments: true,
                traffic_allocation: true,
                target_by_cohort: true,
                target_by_person_property: true,
                bayesian_statistics: false,
                check_results_anytime: false,
                group_level_experiments: false,
                integrated_session_replay: false,
                shared_metrics_library: true,
            },
        },
        feature_flags: {
            available: true,
            features: {
                target_by_percentage: true,
                target_by_person_properties: true,
                flag_scheduling: false,
                experimentation: true,
                multivariate_flags: false,
                unlimited_flags_for_free: true,
                free_third_party_plugins: false,
                activity_logs: false,
                data_export: true,
                multi_environment_support: true,
            },
        },
    },
    platform: {
        open_source: false,
        self_host: false,
        usage_based_pricing: true,
        transparent_pricing: false,
        free_tier: true,
        built_in_analytics: false,
    },
    pricing: {
        model: 'Usage-based',
    },
}
