export const pendo = {
    name: 'Pendo',
    key: 'pendo',
    assets: {
        icon: '/images/competitors/pendo.svg',
        comparisonArticle: '/blog/posthog-vs-pendo',
    },
    products: {
        surveys: {
            available: true,
            features: {
                hosted_surveys: true,
                mobile_surveys: false,
                customizable_pop_ups: true,
                live_previews: true,
                multi_step_surveys: true,
                api_access: true,
                single_choice_questions: true,
                multiple_choice_questions: true,
                open_text_questions: true,
                rating_questions: true,
                nps_questions: true,
                csat_questions: true,
                third_party_link_support: true,
                target_by_url: true,
                survey_scheduling: true,
                export_responses: true,
                slack_integration: true,
            },
        },
        product_analytics: {
            available: true,
            features: {
                ready_made_insight_types: true,
                sql_mode: 'Exports only',
                conversion_funnels: true,
                historical_trends: false,
                time_to_convert_insights: false,
                sequential_step_order: true,
                strict_step_order: false,
                any_step_order: false,
                exclusion_events: false,
                conversion_windows: true,
                reveal_user_paths_between_steps: false,
                anomaly_detection: false,
                filter_internal_and_test_users: false,
                filter_by_cohort: true,
                filter_by_person_property: true,
                breakdown_by_person_property: true,
                correlation_analysis: false,
                reveal_paths_from_a_start_point: true,
                reveal_paths_from_an_end_point: true,
                reveal_paths_between_points: false,
                reveal_paths_within_funnels: false,
                zoom_in_out: false,
                track_pageviews: true,
                track_custom_events: true,
                filter_by_events_or_person_property: true,
                hide_repeating_steps: true,
                max_number_of_steps: '20',
                user_level_permissions: true,
                project_level_permissions: true,
                dashboard_level_permissions: true,
                pinned_dashboards: true,
                share_dashboards_externally: true,
                subscribe_to_dashboards: true,
                embed_dashboards_anywhere: false,
                annotations: false,
                dashboard_insight_tags: false,
                private_insights: true,
            },
        },
    },
    platform: {
        open_source: false,
        self_host: false,
        usage_based_pricing: true,
        transparent_pricing: false,
        free_tier: false,
        built_in_analytics: true,
    },
    pricing: {
        model: 'Seat-based',
    },
}
