export const pendo = {
    name: 'Pendo',
    key: 'pendo',
    assets: {
        icon: '/images/competitors/pendo.svg',
        comparisonArticle: '/blog/posthog-vs-pendo',
    },
    products: {
        product_analytics: {
            available: true,
            features: {
                advertising_analytics: false,
                ai_insight_builder: false,
                alerts: false,
                anomaly_detection: false,
                any_step_order: false,
                autocapture: false,
                breakdown_by_person_property: true,
                clickmaps: false,
                cohorts: true,
                conversion_funnels: true,
                conversion_windows: true,
                correlation_analysis: false,
                custom_events: true,
                custom_properties: true,
                dashboards: true,
                define_number_of_users_on_path: false,
                exclusion_events: false,
                filter_by_cohort: true,
                filter_by_events_or_person_property: true,
                filter_by_person_property: true,
                filter_internal_and_test_users: false,
                formula_mode: false,
                funnels: true,
                group_analytics: true,
                heatmaps: false,
                hide_repeating_steps: true,
                historical_trends: false,
                include_and_exclude_wildcards: false,
                lifecycle: false,
                max_number_of_steps: '20',
                monetization_analytics: false,
                paths: true,
                predictive_insights: false,
                private_insights: true,
                project_level_permissions: true,
                ready_made_insight_types: true,
                real_time_view: false,
                regex_for_path_cleaning: false,
                retention: true,
                reveal_paths_between_points: false,
                reveal_paths_from_a_start_point: true,
                reveal_paths_from_an_end_point: true,
                reveal_paths_within_funnels: false,
                reveal_user_paths_between_steps: false,
                scrollmaps: false,
                sequential_step_order: true,
                sql_editor: false,
                stickiness: false,
                strict_step_order: false,
                time_to_convert_insights: false,
                toolbar: false,
                track_custom_events: true,
                track_pageviews: true,
                traffic_breakdown: false,
                trends: true,
                user_level_permissions: true,
                user_paths: true,
                user_profiles: true,
                utm_tracking: false,
                insights: {
                    available: true,
                    features: {
                        formula_mode: false,
                        ready_made_insight_types: true,
                        sampling: false,
                        sql_editor: false,
                    },
                },
            },
        },
        web_analytics: {
            available: false,
        },
        session_replay: {
            available: true,
        },
        surveys: {
            available: true,
        },
        feature_flags: {
            available: false,
        },
        experiments: {
            available: false,
        },
    },
    platform: {
        deployment: {
            open_source: false,
            self_host: false,
        },
        pricing: {
            free_tier: true,
            transparent_pricing: false,
            usage_based_pricing: false,
        },
        integrations: {
            azure_blob: false,
            bigquery: true,
            ci_cd_integrations: false,
            community_integrations: false,
            customer_io: false,
            exports: true,
            gcs: false,
            google_ads: false,
            hubspot: true,
            imports: true,
            intercom: true,
            microsoft_teams: true,
            redshift: true,
            rudderstack: false,
            s3: false,
            salesforce: true,
            segment: true,
            sentry: false,
            slack: true,
            snowflake: true,
            stripe: false,
            zapier: true,
            zendesk: false,
        },
        security: {
            gdpr_ready: true,
            hipaa_ready: true,
            history_audit_logs: false,
            saml_sso: true,
            soc2_certified: true,
            two_factor_auth: true,
            user_privacy_options: false,
        },
        analytics_integration: {
            built_in_analytics: false,
        },
        developer: {
            api: false,
            local_evaluation: false,
            proxies: false,
            sdks: false,
            sql: false,
        },
    },
    pricing: {
        model: 'Seat-based',
    },
}
