import React from 'react'
import { IconPiggyBank } from '@posthog/icons'
import OSButton from 'components/OSButton'
import Link from 'components/Link'

export const posthog = {
    name: 'PostHog',
    key: 'posthog',
    assets: {
        icon: '/images/logo.svg',
    },
    products: {
        heatmaps: {
            available: true,
            features: {
                clickmaps: true,
                heatmaps: true,
                scrollmaps: true,
                movement_maps: true,
                rage_clicks: true,
                save_heatmaps: true,
                toolbar: true,
            },
        },
        error_tracking: {
            available: true,
            features: {
                error_alerts: true,
                exception_capture: true,
                issue_management: true,
                error_grouping: true,
                stack_tracing: true,
                network_performance: true,
                source_map_support: true,
            },
            integrations: {
                datadog: false,

                product_analytics: true,
                session_replays: true,
                ab_experiments: true,
            },
        },
        session_replay: {
            available: true,
            beta: false,
            pricing: {
                free_tier: '5,000 recordings',
            },
            features: {
                canvas_recording: true,
                chat_with_recordings: true,
                clickmaps: true,
                conditional_recording: true,
                event_timeline: true,
                export_to_json: true,
                export_to_video: 'Beta',
                filter_by_user_or_event: true,
                identity_detection: true,
                iframe_recording: true,
                minimum_duration: true,
                movement_maps: false,
                notes_on_replays: true,
                playlists: true,
                privacy_masking: true,
                rage_click_detection: true,
                retention_policy: 'Up to 3 months',
                screenshot_mode: true,
                scrollmaps: true,
                search_by_network: false,
                share_replays: true,
                single_page_app: false,
                target_by_feature_flag: true,
                target_by_sample: true,
                target_by_url: true,
                wireframe_mode: true,
            },
            platform_support: {
                features: {
                    web_app_recordings: true,
                    mobile_app_recordings: true,
                    ios_recordings: true,
                    android_recordings: true,
                    react_native_recordings: true,
                    flutter_recordings: true,
                },
            },
            analysis: {
                features: {
                    console_logs: true,
                    performance_monitoring: true,
                    network_monitor: true,
                    dom_explorer: true,
                },
            },
            ai: {
                features: {
                    ai_summaries: 'In alpha',
                },
            },
        },
        product_analytics: {
            available: true,
            pricing: {
                free_tier: '1 million events',
            },
            features: {
                actions: true,
                advertising_analytics: 'Beta',
                ai_insight_builder: true,
                alerts: true,
                anomaly_detection: true,
                any_step_order: true,
                autocapture: true,
                breakdown_by_person_property: true,
                clickmaps: true,
                cohorts: true,
                conversion_funnels: true,
                conversion_windows: true,
                correlation_analysis: true,
                custom_events: true,
                custom_properties: true,
                define_number_of_users_on_path: true,
                exclusion_events: true,
                filter_by_cohort: true,
                filter_by_events_or_person_property: true,
                filter_by_person_property: true,
                filter_internal_and_test_users: true,
                hide_repeating_steps: true,
                historical_trends: true,
                include_and_exclude_wildcards: true,
                max_number_of_steps: '20',
                monetization_analytics: (
                    <>
                        Via{' '}
                        <Link to="/revenue-analytics" className="group !no-underline" state={{ newWindow: true }}>
                            <IconPiggyBank className="size-4 inline-block text-green" />{' '}
                            <span className="group-hover:!underline">Revenue Analytics</span>
                        </Link>
                    </>
                ),
                predictive_insights: false,
                private_insights: true,
                project_level_permissions: true,
                ready_made_insight_types: true,
                real_time_view: true,
                regex_for_path_cleaning: true,
                reveal_paths_between_points: true,
                reveal_paths_from_a_start_point: true,
                reveal_paths_from_an_end_point: true,
                reveal_paths_within_funnels: true,
                reveal_user_paths_between_steps: true,
                scrollmaps: true,
                sequential_step_order: true,
                strict_step_order: true,
                time_to_convert_insights: true,
                toolbar: true,
                track_custom_events: true,
                track_pageviews: true,
                user_level_permissions: true,
                user_profiles: true,
                insights: {
                    available: true,
                    features: {
                        formula_mode: true,
                        ready_made_insight_types: true,
                        sampling: true,
                        sql_editor: true,
                    },
                },
                trends: {
                    available: true,
                    features: {},
                },
                funnels: {
                    available: true,
                    features: {
                        conversion_funnels: true,
                        conversion_windows: true,
                        correlation_analysis: true,
                        exclusion_events: true,
                        filter_by_cohort: true,
                        filter_by_events_or_person_property: true,
                        filter_by_person_property: true,
                        filter_internal_and_test_users: true,
                        hide_repeating_steps: true,
                        historical_trends: true,
                        max_number_of_steps: '20',
                        private_insights: true,
                        project_level_permissions: true,
                        ready_made_insight_types: true,
                        reveal_paths_between_points: true,
                        reveal_paths_from_a_start_point: true,
                        reveal_paths_from_an_end_point: true,
                    },
                },
                user_paths: {
                    available: true,
                    features: {
                        reveal_paths_between_points: true,
                        reveal_paths_from_a_start_point: true,
                        reveal_paths_from_an_end_point: true,
                        reveal_paths_within_funnels: true,
                        reveal_user_paths_between_steps: true,
                    },
                },
                group_analytics: {
                    available: true,
                    features: {},
                },
            },
        },
        dashboards: {
            available: true,
            features: {
                annotations: true,
                dashboard_level_permissions: true,
                dashboard_tags: true,
                embed_dashboards: false,
                pinned_dashboards: true,
                private_insights: true,
                project_level_permissions: true,
                share_dashboards_externally: true,
                subscribe_to_dashboards: true,
                user_level_permissions: true,
            },
        },
        feature_flags: {
            available: true,
            pricing: {
                free_tier: '1 million API requests',
            },
            features: {
                boolean_flags: true,
                multivariate_flags: true,
                json_payloads: true,
                release_conditions: true,
            },
            implementation: {
                features: {
                    local_evaluation: true,
                    bootstrapping: true,
                    api_access: true,
                    sdk_support: true,
                },
            },
            targeting: {
                features: {
                    target_by_percentage: true,
                    target_by_person_properties: true,
                    target_by_cohorts: true,
                    geographic_targeting: true,
                    group_targeting: true,
                },
            },
            management: {
                features: {
                    approvals: false,
                    flag_administration: true,
                    flag_scheduling: true,
                    history_activity: true,
                    instant_rollbacks: true,
                    multi_environment: 'Partial',
                    permissioning: true,
                },
            },
            testing: {
                features: {
                    flag_overrides: true,
                    toolbar_integration: true,
                    user_assignment: true,
                },
            },
            experimentation: {
                features: {
                    experimentation: true,
                    correlation_analysis: true,
                },
            },
            advanced: {
                features: {
                    persist_across_auth: true,
                    early_access_widget: true,
                },
            },
        },
        experiments: {
            available: true,
            pricing: {
                free_tier: '1 million API requests',
            },
            experiment_types: {
                features: {
                    count_value_metrics: true,
                    custom_goals: true,
                    funnel_metrics: true,
                    ratio_metrics: true,
                    secondary_metrics: true,
                    shared_metrics_library: true,
                },
            },
            supported_tests: {
                features: {
                    aa_testing: true,
                    ab_testing: true,
                    abn_testing: true,
                    data_warehouse_experiments: 'Beta',
                    fake_door_testing: true,
                    holdout_testing: true,
                    multi_armed_bandit: false,
                    mutually_exclusive_experiments: false,
                    redirect_testing: true,
                },
            },
            targeting: {
                features: {
                    cohort_integration: true,
                    exclusion_rules: true,
                    geographic_targeting: true,
                    group_level_experiments: true,
                    holdouts: true,
                    percentage_rollouts: true,
                },
            },
            implementation: {
                features: {
                    api_access: true,
                    feature_flag_foundation: true,
                    json_payloads: true,
                    multivariate_testing: true,
                },
            },
            analysis: {
                features: {
                    results_visualization: true,
                    side_effect_monitoring: true,
                    statistical_significance: true,
                    statistics_engine: 'Bayesian or Sequential',
                },
            },
            platforms: {
                features: {
                    mobile: true,
                    web: true,
                },
            },
            features: {
                dynamic_cohorts: true,
                experiment_analysis: true,
                namespaces: false,
                native_goal_tracking: true,
                no_code_experiments: true,
                recommended_run_time: true,
                split_testing: true,
                visual_editor: 'Beta',
            },
        },
        surveys: {
            available: true,
            pricing: {
                free_tier: '1500 responses',
            },
            features: {
                aggregated_results: true,
                ai_response_summaries: 'Beta',
                api_access: true,
                automatic_nps_calculation: true,
                calendar_invites: true,
                capture_partial_responses: true,
                cdp_destinations: true,
                completion_conditions: true,
                conditional_logic: true,
                csat_surveys: true,
                custom_html: true,
                custom_targeting: true,
                custom_ui: true,
                customizable_wait_periods: true,
                display_conditions: true,
                embedded_links: true,
                emoji_reaction: true,
                event_triggered: true,
                feedback_button: true,
                freeform_text: true,
                hosted_surveys: true,
                iframe_embedding: true,
                link_to_webpage: true,
                multi_select: true,
                multi_step_surveys: true,
                multiple_choice: true,
                no_code: true,
                nps_surveys: true,
                pmf_surveys: true,
                popover: true,
                rating: true,
                sdk_support: true,
                slack_integration: true,
                survey_templates: true,
                user_interview_requests: true,
            },
        },
        revenue_analytics: {
            available: true,
            beta: true,
            features: {
                revenue_tracking: true,
                event_based_revenue_tracking: true,
                native_multi_source_revenue_tracking: true,
                deferred_revenue: true,
                product_analytics_integration: true,
                multi_currency_support: true,
                revenue_prediction: false,
                sql_access: true,
            },
        },
        cdp: {
            available: true,
            features: {
                number_of_integrations: '60+',
                real_time_streaming: true,
                data_warehouse_sources: true,
                real_time_destinations: true,
                batch_exports: true,
                custom_transformations: true,
                no_code_setup: true,
                built_in_analytics: true,
            },
        },
        llm_analytics: {
            available: true,
        },
        data_warehouse: {
            available: true,
            pricing: {
                free_tier: '1 million synced rows',
            },
            features: {
                sql_queries: true,
                save_queries_as_views: true,
                ai_sql: true,
                simplified_syntax: true,
                smart_joins: true,
                product_functions: true,
                data_warehouse_sources: true,
                unified_queries: true,
                custom_views: true,
                scheduled_syncs: true,
                cloud_storage: true,
            },
        },
        web_analytics: {
            available: true,
            features: {
                advertising_analytics: false,
                bounce_rate: true,
                bounce_rate_tracking: false,
                breakdown_by_device_and_browser: false,
                breakdown_by_geoip: false,
                clickmaps: true,
                conversions: true,
                cookieless_tracking: true,
                custom_channel_types: true,
                entry_exit_paths: true,
                first_party_cookies: false,
                heatmaps: true,
                hipaa_compliance: false,
                integration_with_feature_flags: true,
                integration_with_session_replay: true,
                integration_with_surveys: true,
                migration: true,
                movement_maps: true,
                open_source: false,
                outbound_clicks: true,
                pageviews: true,
                pre_configured_dashboards: false,
                real_time_reporting: false,
                revenue_tracking: false,
                script_size: '50.6 kb',
                scrollmaps: true,
                session_and_duration_tracking: false,
                sessions: true,
                snippet_install: true,
                traffic_breakdown: true,
                utm_tracking: true,
                visitor_and_view_tracking: false,
                web_vitals: true,
                web_vitals_reporting: false,
            },
        },
    },
    platform: {
        deployment: {
            eu_hosting: true,
            open_source: true,
            reverse_proxy: true,
            managed_reverse_proxy: true,
            self_host: 'Limited',
        },
        pricing: {
            usage_based_pricing: true,
            transparent_pricing: true,
            free_tier: true,
        },
        integrations: {
            azure_blob: true,
            bigquery: true,
            ci_cd_integrations: true,
            community_integrations: true,
            csv_exports: true,
            customer_io: true,
            email_reports: true,
            exports: true,
            gcs: true,
            google_ads: true,
            google_search_console: false,
            hubspot: true,
            imports: true,
            intercom: true,
            microsoft_teams: true,
            redshift: true,
            rudderstack: true,
            salesforce: true,
            s3: true,
            segment: true,
            sentry: true,
            slack: true,
            snowflake: true,
            stripe: true,
            warehouse_import: true,
            wordpress: false,
            zapier: true,
            zendesk: true,
        },
        developer: {
            api: true,
            collaboration: 'Invite teammates to collaborate on all features',
            cross_domain_tracking: true,
            mobile_sdks: true,
            native_data_sources: true,
            notebooks: true,
            proxies: true,
            sdks: '14',
            server_side_sdks: true,
            sql: true,
        },
        analytics_integration: {
            built_in_analytics: true,
        },
        security: {
            bot_blocking: true,
            cookieless_tracking: true,
            data_anonymization: true,
            data_retention: '7 years',
            gdpr_ready: true,
            hipaa_ready: true,
            history_audit_logs: true,
            role_based_access_control: true,
            saml_sso: 'Enterprise',
            soc2_certified: true,
            security_certification: 'SOC 2 Type II',
            two_factor_auth: true,
            user_privacy_options: true,
        },
    },
    pricing: {
        model: 'Usage-based',
    },
}
