export const posthog = {
    name: 'PostHog',
    key: 'posthog',
    assets: {
        icon: '/images/logo.svg',
    },
    products: {
        error_tracking: {
            available: true,
            features: {
                error_alerts: true,
                exception_capture: true,
                issue_management: true,
                error_grouping: true,
                stack_tracing: true,
                network_performance: true,
                source_map_support: true,
            },
            integrations: {
                product_analytics: true,
                session_replays: true,
                ab_experiments: true,
            },
        },
        session_replay: {
            available: true,
            beta: false,
            pricing: {
                free_tier: '5,000 recordings',
            },
            features: {
                canvas_recording: true,
                chat_with_recordings: true,
                event_timeline: true,
                iframe_recording: true,
                minimum_duration: true,
                wireframe_mode: true,
                screenshot_mode: true,
                web_app_recordings: true,
                mobile_app_recordings: true,
                ios_recordings: true,
                android_recordings: true,
                react_native_recordings: true,
                flutter_recordings: true,
                heatmaps: true,
                console_logs: true,
                performance_monitoring: true,
                dom_explorer: true,
                ai_summaries: 'In alpha',
                conditional_recording: true,
                target_by_url: true,
                target_by_sample: true,
                target_by_feature_flag: true,
                filter_by_user_or_event: true,
                search_by_network: false,
                playlists: true,
                rage_click_detection: true,
                privacy_masking: true,
                export_to_json: true,
                export_to_video: 'Beta',
                retention_policy: 'Up to 3 months',
                identity_detection: true,
            },
        },
        product_analytics: {
            available: true,
            pricing: {
                free_tier: '1 million events',
            },
            features: {
                ai_insight_builder: true,
                alerts: true,
                anomaly_detection: true,
                any_step_order: true,
                autocapture: true,
                breakdown_by_person_property: true,
                clickmaps: true,
                conversion_funnels: true,
                conversion_windows: true,
                correlation_analysis: true,
                heatmaps: true,
                scrollmaps: true,
                define_number_of_users_on_path: true,
                exclusion_events: true,
                filter_by_cohort: true,
                filter_by_events_or_person_property: true,
                filter_by_person_property: true,
                filter_internal_and_test_users: true,
                hide_repeating_steps: true,
                historical_trends: true,
                include_and_exclude_wildcards: true,
                max_number_of_steps: '20',
                private_insights: true,
                project_level_permissions: true,
                ready_made_insight_types: true,
                regex_for_path_cleaning: true,
                reveal_paths_between_points: true,
                reveal_paths_from_a_start_point: true,
                reveal_paths_from_an_end_point: true,
                reveal_paths_within_funnels: true,
                reveal_user_paths_between_steps: true,
                sequential_step_order: true,
                strict_step_order: true,
                time_to_convert_insights: true,
                track_custom_events: true,
                track_pageviews: true,
                user_level_permissions: true,
                insights: {
                    available: true,
                    features: {
                        ready_made_insight_types: true,
                        sql_editor: true,
                        formula_mode: true,
                        sampling: true,
                    },
                },
                trends: {
                    available: true,
                    features: {},
                },
                funnels: {
                    available: true,
                    features: {
                        conversion_funnels: true,
                        conversion_windows: true,
                        correlation_analysis: true,
                        exclusion_events: true,
                        filter_by_cohort: true,
                        filter_by_events_or_person_property: true,
                        filter_by_person_property: true,
                        filter_internal_and_test_users: true,
                        hide_repeating_steps: true,
                        historical_trends: true,
                        max_number_of_steps: '20',
                        private_insights: true,
                        project_level_permissions: true,
                        ready_made_insight_types: true,
                        reveal_paths_between_points: true,
                        reveal_paths_from_a_start_point: true,
                        reveal_paths_from_an_end_point: true,
                    },
                },
                user_paths: {
                    available: true,
                    features: {
                        reveal_paths_between_points: true,
                        reveal_paths_from_a_start_point: true,
                        reveal_paths_from_an_end_point: true,
                        reveal_paths_within_funnels: true,
                        reveal_user_paths_between_steps: true,
                    },
                },
                group_analytics: {
                    available: true,
                    features: {},
                },
            },
        },
        dashboards: {
            available: true,
            features: {
                annotations: true,
                dashboard_level_permissions: true,
                dashboard_tags: true,
                embed_dashboards: false,
                pinned_dashboards: true,
                private_insights: true,
                project_level_permissions: true,
                share_dashboards_externally: true,
                subscribe_to_dashboards: true,
                user_level_permissions: true,
            },
        },
        feature_flags: {
            available: true,
            pricing: {
                free_tier: '1 million API requests',
            },
            features: {
                boolean_flags: true,
                multivariate_flags: true,
                json_payloads: true,
                release_conditions: true,
                local_evaluation: true,
                bootstrapping: true,
                api_access: true,
                sdk_support: true,
                target_by_percentage: true,
                target_by_person_properties: true,
                target_by_cohorts: true,
                geographic_targeting: true,
                group_targeting: true,
                flag_scheduling: true,
                instant_rollbacks: true,
                history_activity: true,
                flag_administration: true,
                multi_environment: 'Partial',
                flag_overrides: true,
                toolbar_integration: true,
                user_assignment: true,
                experimentation: true,
                correlation_analysis: true,
                persist_across_auth: true,
                early_access_widget: true,
                automated_reports: false,
                ip_resolution: true,
            },
        },
        experiments: {
            available: true,
            pricing: {
                free_tier: '1 million API requests',
            },
            features: {
                funnel_metrics: true,
                count_value_metrics: true,
                ratio_metrics: true,
                custom_goals: true,
                secondary_metrics: true,
                primary_secondary_metrics: true,
                shared_metrics_library: true,
                ab_testing: true,
                experiment_analysis: true,
                no_code_experiments: true,
                split_testing: true,
                recommended_run_time: true,
                dynamic_cohorts: true,
                aa_testing: true,
                abn_testing: true,
                holdout_testing: true,
                fake_door_testing: true,
                redirect_testing: true,
                cohort_integration: true,
                geographic_targeting: true,
                percentage_rollouts: true,
                group_level_experiments: true,
                holdouts: true,
                exclusion_rules: true,
                feature_flag_foundation: true,
                json_payloads: true,
                multivariate_testing: true,
                api_access: true,
                statistical_significance: true,
                results_visualization: true,
                side_effect_monitoring: true,
                statistics_engine: 'Bayesian or Sequential',
                web: true,
                mobile: true,
            },
        },
        surveys: {
            available: true,
            pricing: {
                free_tier: '1500 responses',
            },
            features: {
                multiple_choice: true,
                multi_select: true,
                rating: true,
                emoji_reaction: true,
                embedded_links: true,
                freeform_text: true,
                survey_templates: true,
                nps_surveys: true,
                csat_surveys: true,
                user_interview_requests: true,
                display_conditions: true,
                event_triggered: true,
                custom_targeting: true,
                popover: true,
                feedback_button: true,
                hosted_surveys: true,
                custom_ui: true,
                iframe_embedding: true,
                multi_step_surveys: true,
                conditional_logic: true,
                link_to_webpage: true,
                calendar_invites: true,
                slack_integration: true,
                cdp_destinations: true,
                no_code: true,
                api_access: true,
                sdk_support: true,
                capture_partial_responses: true,
                completion_conditions: true,
                customizable_wait_periods: true,
                aggregated_results: true,
                automatic_nps_calculation: true,
                ai_response_summaries: 'Beta',
                custom_html: true,
            },
        },
        revenue_analytics: {
            available: true,
            beta: true,
            features: {
                revenue_tracking: true,
                event_based_revenue_tracking: true,
                native_multi_source_revenue_tracking: true,
                deferred_revenue: true,
                product_analytics_integration: true,
                multi_currency_support: true,
                revenue_prediction: false,
                sql_access: true,
            },
        },
        cdp: {
            available: true,
            features: {
                number_of_integrations: '60+',
                real_time_streaming: true,
                data_warehouse_sources: true,
                real_time_destinations: true,
                batch_exports: true,
                custom_transformations: true,
                no_code_setup: true,
                built_in_analytics: true,
            },
        },
        llm_analytics: {
            available: true,
        },
        data_warehouse: {
            available: true,
            pricing: {
                free_tier: '1 million synced rows',
            },
            features: {
                sql_queries: true,
                save_queries_as_views: true,
                ai_sql: true,
                simplified_syntax: true,
                smart_joins: true,
                product_functions: true,
                data_warehouse_sources: true,
                unified_queries: true,
                custom_views: true,
                scheduled_syncs: true,
                cloud_storage: true,
            },
        },
        web_analytics: {
            available: true,
            features: {
                bounce_rate: true,
                conversions: true,
                clickmaps: true,
                custom_channel_types: true,
                entry_exit_paths: true,
                heatmaps: true,
                outbound_clicks: true,
                pageviews: true,
                scrollmaps: true,
                sessions: true,
                traffic_breakdown: true,
                utm_tracking: true,
                web_vitals: true,
            },
        },
    },
    platform: {
        deployment: {
            open_source: true,
            self_host: 'Limited',
            managed_reverse_proxy: true,
        },
        pricing: {
            usage_based_pricing: true,
            transparent_pricing: true,
            free_tier: true,
        },
        integrations: {
            imports: true,
            exports: true,
            warehouse_import: true,
            stripe: false,
            zendesk: true,
            hubspot: false,
            sentry: true,
            segment: true,
            rudderstack: true,
            zapier: true,
            customer_io: false,
            intercom: false,
            slack: true,
            microsoft_teams: true,
            community_integrations: true,
            google_ads: true,
            ci_cd_integrations: true,
        },
        analytics_integration: {
            built_in_analytics: true,
        },
        security: {
            user_privacy_options: true,
            history_audit_logs: true,
            gdpr_ready: true,
            hipaa_ready: true,
            soc2_certified: true,
            two_factor_auth: true,
            saml_sso: 'Enterprise',
        },
    },
    pricing: {
        model: 'Usage-based',
    },
}
