export const rollbar = {
    name: 'Rollbar',
    key: 'rollbar',
    assets: {
        icon: '/images/competitors/rollbar.svg',
    },
    products: {
        product_analytics: {
            available: false,
        },
        session_replay: {
            available: true,
        },
        surveys: {
            available: false,
        },
        error_tracking: {
            available: true,
            features: {
                console_log_capture: true,
                error_alerts: true,
                error_grouping: true,
                exception_capture: true,
                issue_management: true,
                log_management: false,
                mobile_sdk_coverage: true,
                profiling: false,
                source_map_support: true,
                stack_tracing: true,
                user_device_context: true,
            },
            monitoring: {
                features: {
                    cron_monitoring: '',
                    distributed_tracing: false,
                    release_tracking: true,
                    performance_monitoring: false,
                },
            },
            integrations: {
                product_analytics: false,
                session_replay: false,
            },
        },
    },
    platform: {
        deployment: {
            eu_hosting: false,
            managed_reverse_proxy: false,
            open_source: false,
            self_host: false,
        },
        pricing: {
            free_tier: true,
            model: 'Usage-based',
            self_serve: true,
            transparent_pricing: true,
            usage_based_pricing: true,
        },
        developer: {
            api: true,
            collaboration: true,
            mobile_sdks: true,
            native_data_sources: true,
            proxies: false,
            sdks: true,
            server_side_sdks: true,
            sql: true,
        },
        tools: {
            cms: '',
            notebooks: false,
            project_management_tools: '',
        },
        integrations: {
            azure_blob: false,
            bigquery: false,
            cdp: false,
            ci_cd_integrations: true,
            community_integrations: true,
            csv_exports: true,
            customer_io: false,
            data_warehouse: true,
            datadog: true,
            email_reports: true,
            exports: true,
            gcs: false,
            google_ads: false,
            hubspot: false,
            imports: false,
            intercom: false,
            microsoft_teams: true,
            redshift: false,
            rudderstack: false,
            s3: false,
            salesforce: true,
            segment: true,
            sentry: false,
            slack: true,
            snowflake: false,
            stripe: false,
            warehouse_import: false,
            wordpress: false,
            zapier: true,
            zendesk: true,
        },
        security: {
            bot_blocking: false,
            cookieless_tracking: false,
            data_anonymization: true,
            data_retention: true,
            gdpr_ready: true,
            hipaa_ready: true,
            history_audit_logs: 'Enterprise',
            reverse_proxy: false,
            role_based_access_control: true,
            saml_sso: true,
            soc2_certified: true,
            two_factor_auth: true,
            user_privacy_options: true,
        },
        analytics_integration: {
            built_in_analytics: false,
        },
    },
}
