export const rudderstack = {
    name: 'RudderStack',
    key: 'rudderstack',
    assets: {
        icon: '/images/competitors/rudderstack.svg',
    },
    products: {
        cdp: {
            available: true,
            features: {
                number_of_integrations: '200+',
                realtime_streaming: true,
                custom_transformations: true,
                no_code_setup: true,
                built_in_analytics: false,
            },
        },
        product_analytics: {
            available: false,
        },
        session_replay: {
            available: false,
        },
    },
    data_warehouse: {
        available: true,
        features: {
            batch_exports: true,
            warehouse_sources: true,
        },
    },
    platform: {
        analytics_integration: {
            built_in_analytics: false,
        },
        deployment: {
            open_source: true,
            self_host: true,
        },
        developer: {
            api: true,
            collaboration: true,
            mobile_sdks: true,
            native_data_sources: true,
            proxies: true,
            sdks: true,
            server_side_sdks: true,
            sql: false,
        },
        tools: {
            cms: '',
            notebooks: false,
            project_management_tools: '',
        },
        integrations: {
            azure_blob: true,
            bigquery: true,
            ci_cd_integrations: true,
            community_integrations: true,
            csv_exports: false,
            customer_io: false,
            datadog: true,

            email_reports: false,
            exports: true,
            gcs: true,
            google_ads: true,
            hubspot: true,
            imports: true,
            intercom: true,
            microsoft_teams: false,
            redshift: true,
            s3: true,
            segment: false,
            sentry: true,
            slack: true,
            snowflake: true,
            stripe: true,
            warehouse_import: true,
            wordpress: false,
            zapier: true,
            zendesk: true,
        },
        pricing: {
            free_tier: true,
            transparent_pricing: true,
            usage_based_pricing: true,
        },
        security: {
            bot_blocking: false,
            cookieless_tracking: false,
            data_anonymization: true,
            data_retention: true,
            gdpr_ready: true,
            hipaa_ready: true,
            history_audit_logs: true,
            reverse_proxy: false,
            saml_sso: true,
            soc2_certified: true,
            two_factor_auth: true,
            user_privacy_options: true,
        },
    },
    pricing: {
        model: 'Usage-based',
    },
}
