export const sentry = {
    name: 'Sentry',
    key: 'sentry',
    assets: {
        icon: '/images/competitors/sentry.svg',
        comparisonArticle: '/blog/posthog-vs-sentry',
    },
    products: {
        error_tracking: {
            available: true,
        },
        session_replay: {
            available: true,
            pricing: {
                free_tier: 'Limited',
            },
            features: {
                ai_summaries: false,
                android_recordings: false,
                canvas_recording: false,
                chat_with_recordings: false,
                clickmaps: false,
                conditional_recording: false,
                console_logs: false,
                dom_explorer: false,
                event_timeline: false,
                export_to_json: false,
                export_to_video: false,
                filter_by_user_or_event: false,
                flutter_recordings: false,
                heatmaps: false,
                identity_detection: false,
                ios_recordings: false,
                iframe_recording: false,
                minimum_duration: false,
                mobile_app_recordings: false,
                movement_maps: false,
                network_monitor: false,
                notes_on_replays: false,
                performance_monitoring: false,
                playlists: false,
                privacy_masking: false,
                rage_click_detection: false,
                react_native_recordings: false,
                retention_policy: false,
                screenshot_mode: false,
                scrollmaps: false,
                search_by_network: false,
                share_replays: false,
                single_page_app: false,
                target_by_feature_flag: false,
                target_by_sample: false,
                target_by_url: false,
                web_app_recordings: false,
                wireframe_mode: false,
            },
        },
        surveys: {
            available: true,
        },
        product_analytics: {
            available: 'Partial',
            features: {
                advertising_analytics: false,
                ai_insight_builder: false,
                alerts: false,
                anomaly_detection: false,
                any_step_order: false,
                autocapture: 'Errors only',
                breakdown_by_person_property: false,
                clickmaps: false,
                cohorts: false,
                conversion_funnels: false,
                conversion_windows: false,
                correlation_analysis: false,
                custom_events: true,
                custom_properties: false,
                dashboards: true,
                define_number_of_users_on_path: false,
                exclusion_events: false,
                filter_by_cohort: false,
                filter_by_events_or_person_property: false,
                filter_by_person_property: false,
                filter_internal_and_test_users: false,
                formula_mode: false,
                funnels: false,
                group_analytics: false,
                heatmaps: false,
                hide_repeating_steps: false,
                historical_trends: false,
                include_and_exclude_wildcards: false,
                lifecycle: false,
                max_number_of_steps: false,
                monetization_analytics: false,
                paths: false,
                predictive_insights: false,
                private_insights: false,
                project_level_permissions: false,
                ready_made_insight_types: false,
                real_time_view: false,
                regex_for_path_cleaning: false,
                retention: false,
                reveal_paths_between_points: false,
                reveal_paths_from_a_start_point: false,
                reveal_paths_from_an_end_point: false,
                reveal_paths_within_funnels: false,
                reveal_user_paths_between_steps: false,
                scrollmaps: false,
                sequential_step_order: false,
                sql_editor: false,
                stickiness: false,
                strict_step_order: false,
                time_to_convert_insights: false,
                toolbar: false,
                track_custom_events: true,
                track_pageviews: false,
                traffic_breakdown: false,
                trends: 'Trends only',
                user_level_permissions: false,
                user_paths: false,
                user_profiles: false,
                utm_tracking: false,
                insights: {
                    available: false,
                    features: {
                        formula_mode: false,
                        ready_made_insight_types: false,
                        sampling: false,
                        sql_editor: false,
                    },
                },
            },
        },
        web_analytics: {
            available: false,
        },
        feature_flags: {
            available: false,
        },
        experiments: {
            available: false,
        },
        heatmaps: {
            available: false,
        },
    },
    platform: {
        deployment: {
            eu_hosting: true,
            managed_reverse_proxy: false,
            open_source: true,
            self_host: false,
        },
        pricing: {
            free_tier: 'Limited',
            transparent_pricing: false,
            usage_based_pricing: false,
        },
        developer: {
            api: true,
            collaboration: false,
            local_evaluation: false,
            mobile_sdks: false,
            native_data_sources: false,
            proxies: false,
            sdks: true,
            server_side_sdks: false,
            sql: false,
        },
        integrations: {
            azure_blob: false,
            bigquery: false,
            cdp: false,
            ci_cd_integrations: false,
            community_integrations: false,
            csv_exports: false,
            customer_io: false,
            data_warehouse: false,
            email_reports: false,
            exports: false,
            gcs: false,
            google_ads: false,
            hubspot: false,
            imports: false,
            intercom: false,
            microsoft_teams: true,
            redshift: false,
            rudderstack: false,
            s3: false,
            salesforce: false,
            segment: true,
            sentry: false,
            slack: true,
            snowflake: false,
            stripe: false,
            warehouse_import: false,
            wordpress: false,
            zapier: false,
            zendesk: false,
        },
        security: {
            bot_blocking: false,
            cookieless_tracking: false,
            data_anonymization: false,
            data_retention: false,
            gdpr_ready: true,
            hipaa_ready: true,
            history_audit_logs: false,
            reverse_proxy: false,
            saml_sso: true,
            soc2_certified: true,
            two_factor_auth: true,
            user_privacy_options: false,
        },
        analytics_integration: {
            built_in_analytics: false,
        },
    },
    pricing: {
        model: 'Seat-based + usage',
    },
}
