export const statsig = {
    name: 'Statsig',
    key: 'statsig',
    assets: {
        icon: '/images/competitors/statsig.svg',
        comparisonArticle: '/blog/posthog-vs-statsig',
    },
    products: {
        experiments: {
            available: true,
            pricing: {
                free_tier: false,
            },
            features: {
                aa_testing: false,
                ab_testing: false,
                abn_testing: false,
                api_access: false,
                bayesian_statistics: false,
                check_results_anytime: false,
                cohort_integration: false,
                count_value_metrics: false,
                cross_domain_experiments: false,
                custom_goals: true,
                duration_prediction: false,
                dynamic_cohorts: false,
                exclusion_rules: false,
                experiment_analysis: false,
                fake_door_testing: false,
                feature_flag_foundation: false,
                funnel_metrics: false,
                geographic_targeting: false,
                group_level_experiments: false,
                holdout_testing: false,
                holdouts: false,
                integrated_session_replay: false,
                json_payloads: false,
                minimum_metrics: false,
                mobile: false,
                multivariate_experiments: false,
                multivariate_testing: true,
                namespaces: false,
                native_goal_tracking: false,
                no_code_experiments: false,
                percentage_rollouts: false,
                primary_secondary_metrics: false,
                ratio_metrics: false,
                recommended_run_time: false,
                redirect_testing: false,
                results_visualization: false,
                secondary_metrics: true,
                shared_metrics_library: false,
                side_effect_monitoring: false,
                split_testing: false,
                statistical_significance: true,
                statistics_engine: false,
                target_by_cohort: false,
                target_by_person_property: false,
                traffic_allocation: false,
                unlimited_experiments: false,
                visual_editor: false,
                web: false,
            },
        },
        feature_flags: {
            available: true,
            pricing: {
                free_tier: false,
            },
            features: {
                activity_logs: false,
                api_access: false,
                automated_reports: false,
                boolean_flags: true,
                bootstrapping: false,
                correlation_analysis: false,
                custom_targeting: true,
                data_export: false,
                early_access_management: false,
                early_access_widget: false,
                experimentation: false,
                flag_administration: false,
                flag_overrides: false,
                flag_scheduling: false,
                free_third_party_plugins: false,
                geographic_targeting: false,
                group_targeting: false,
                history_activity: false,
                instant_rollbacks: false,
                ip_resolution: false,
                json_payloads: false,
                local_evaluation: false,
                multi_environment: true,
                multi_environment_support: false,
                multivariate_flags: false,
                percentage_rollouts: true,
                persist_across_auth: false,
                release_conditions: false,
                sdk_support: false,
                target_by_cohorts: false,
                target_by_percentage: false,
                target_by_person_properties: false,
                toolbar_integration: false,
                unlimited_flags_for_free: false,
                user_assignment: false,
            },
        },
        product_analytics: {
            available: true,
            features: {
                advertising_analytics: false,
                ai_insight_builder: false,
                alerts: false,
                anomaly_detection: false,
                any_step_order: false,
                autocapture: false,
                breakdown_by_person_property: false,
                clickmaps: false,
                cohorts: true,
                conversion_funnels: true,
                conversion_windows: false,
                correlation_analysis: false,
                custom_events: true,
                custom_properties: true,
                dashboards: true,
                define_number_of_users_on_path: false,
                exclusion_events: false,
                filter_by_cohort: false,
                filter_by_events_or_person_property: false,
                filter_by_person_property: false,
                filter_internal_and_test_users: false,
                formula_mode: true,
                funnels: true,
                group_analytics: true,
                heatmaps: false,
                hide_repeating_steps: false,
                historical_trends: false,
                include_and_exclude_wildcards: false,
                lifecycle: false,
                max_number_of_steps: false,
                monetization_analytics: false,
                paths: 'In beta',
                predictive_insights: false,
                private_insights: false,
                project_level_permissions: false,
                ready_made_insight_types: false,
                real_time_view: false,
                regex_for_path_cleaning: false,
                retention: true,
                reveal_paths_between_points: false,
                reveal_paths_from_a_start_point: false,
                reveal_paths_from_an_end_point: false,
                reveal_paths_within_funnels: false,
                reveal_user_paths_between_steps: false,
                scrollmaps: false,
                sequential_step_order: false,
                sql_editor: false,
                stickiness: false,
                strict_step_order: false,
                time_to_convert_insights: false,
                toolbar: false,
                track_custom_events: true,
                track_pageviews: false,
                traffic_breakdown: false,
                trends: true,
                user_level_permissions: false,
                user_paths: 'In beta',
                user_profiles: false,
                utm_tracking: false,
                insights: {
                    available: true,
                    features: {
                        formula_mode: true,
                        ready_made_insight_types: false,
                        sampling: false,
                        sql_editor: false,
                    },
                },
            },
        },
        web_analytics: {
            available: true,
        },
        session_replay: {
            available: true,
            pricing: {
                free_tier: '50,000 recordings',
            },
            features: {
                ai_summaries: false,
                android_recordings: false,
                canvas_recording: true,
                chat_with_recordings: false,
                clickmaps: false,
                conditional_recording: true,
                console_logs: false,
                dom_explorer: false,
                event_timeline: true,
                export_to_json: false,
                export_to_video: false,
                filter_by_user_or_event: true,
                flutter_recordings: false,
                heatmaps: false,
                identity_detection: true,
                ios_recordings: false,
                iframe_recording: true,
                minimum_duration: false,
                mobile_app_recordings: false,
                movement_maps: false,
                network_monitor: false,
                notes_on_replays: false,
                performance_monitoring: false,
                playlists: false,
                privacy_masking: true,
                rage_click_detection: false,
                react_native_recordings: false,
                retention_policy: '30 days',
                screenshot_mode: false,
                scrollmaps: false,
                search_by_network: false,
                share_replays: false,
                single_page_app: false,
                target_by_feature_flag: true,
                target_by_sample: true,
                target_by_url: false,
                web_app_recordings: true,
                wireframe_mode: false,
            },
        },
        surveys: {
            available: false,
        },
    },
    platform: {
        deployment: {
            eu_hosting: false,
            managed_reverse_proxy: false,
            open_source: false,
            self_host: false,
        },
        pricing: {
            free_tier: false,
            transparent_pricing: false,
            usage_based_pricing: true,
        },
        developer: {
            api: false,
            collaboration: false,
            local_evaluation: false,
            mobile_sdks: false,
            native_data_sources: false,
            proxies: false,
            sdks: false,
            server_side_sdks: false,
            sql: false,
        },
        integrations: {
            azure_blob: false,
            bigquery: false,
            cdp: false,
            ci_cd_integrations: false,
            community_integrations: false,
            csv_exports: false,
            customer_io: false,
            data_warehouse: false,
            email_reports: false,
            exports: true,
            gcs: false,
            google_ads: false,
            hubspot: false,
            imports: true,
            intercom: false,
            microsoft_teams: true,
            redshift: false,
            rudderstack: false,
            s3: false,
            salesforce: false,
            segment: false,
            sentry: false,
            slack: true,
            snowflake: false,
            stripe: false,
            warehouse_import: false,
            wordpress: false,
            zapier: false,
            zendesk: false,
        },
        security: {
            bot_blocking: false,
            cookieless_tracking: false,
            data_anonymization: false,
            data_retention: false,
            gdpr_ready: true,
            hipaa_ready: 'Enterprise',
            history_audit_logs: false,
            reverse_proxy: false,
            saml_sso: 'Enterprise',
            soc2_certified: true,
            two_factor_auth: true,
            user_privacy_options: false,
        },
        analytics_integration: {
            built_in_analytics: false,
        },
    },
    pricing: {
        model: 'Usage-based',
    },
}
