export const vwo = {
    name: 'VWO',
    key: 'vwo',
    assets: {
        icon: '/images/competitors/vwo.svg',
    },
    products: {
        experiments: {
            available: true,
            pricing: {
                free_tier: false,
            },
            features: {
                aa_testing: false,
                ab_testing: false,
                abn_testing: false,
                api_access: false,
                bayesian_statistics: false,
                check_results_anytime: false,
                cohort_integration: false,
                count_value_metrics: false,
                cross_domain_experiments: true,
                custom_goals: false,
                duration_prediction: true,
                dynamic_cohorts: false,
                exclusion_rules: false,
                experiment_analysis: false,
                fake_door_testing: false,
                feature_flag_foundation: false,
                funnel_metrics: false,
                geographic_targeting: false,
                group_level_experiments: false,
                holdout_testing: false,
                holdouts: false,
                integrated_session_replay: true,
                json_payloads: false,
                minimum_metrics: true,
                mobile: false,
                multivariate_experiments: true,
                multivariate_testing: false,
                namespaces: false,
                native_goal_tracking: false,
                no_code_experiments: false,
                percentage_rollouts: false,
                primary_secondary_metrics: false,
                ratio_metrics: false,
                recommended_run_time: false,
                redirect_testing: false,
                results_visualization: false,
                secondary_metrics: true,
                shared_metrics_library: false,
                side_effect_monitoring: false,
                split_testing: false,
                statistical_significance: false,
                statistics_engine: false,
                target_by_cohort: true,
                target_by_person_property: true,
                traffic_allocation: true,
                unlimited_experiments: true,
                visual_editor: false,
                web: false,
            },
        },
    },
    platform: {
        deployment: {
            open_source: false,
            self_host: false,
        },
        developer: {
            api: false,
            local_evaluation: false,
            native_data_sources: false,
            proxies: false,
            sdks: false,
            sql: false,
        },
        pricing: {
            free_tier: false,
            transparent_pricing: false,
            usage_based_pricing: false,
        },
        integrations: {
            exports: false,
            imports: false,
            microsoft_teams: false,
            sentry: false,
            slack: false,
            zapier: false,
        },
        security: {
            gdpr_ready: false,
            hipaa_ready: false,
            history_audit_logs: false,
            saml_sso: false,
            soc2_certified: false,
            two_factor_auth: false,
            user_privacy_options: false,
        },
        analytics_integration: {
            built_in_analytics: false,
        },
    },
    pricing: {
        model: 'Tier-based',
    },
}
