// Inlined Lottie animation data for fast loading
// These are critical for the loading state, so we inline them to avoid network requests

export const hourglassAnimation = {
    v: '5.6.5',
    fr: 24,
    ip: 0,
    op: 28,
    w: 30,
    h: 30,
    nm: 'hourglass',
    ddd: 0,
    assets: [],
    layers: [
        {
            ddd: 0,
            ind: 1,
            ty: 4,
            nm: 'middle Outlines',
            sr: 1,
            ks: {
                o: { a: 0, k: 100, ix: 11 },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [15, 15.5, 0], ix: 2 },
                a: { a: 0, k: [1, 5.5, 0], ix: 1 },
                s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 0,
                                k: {
                                    i: [
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    o: [
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    v: [
                                        [1, 2.188],
                                        [1, 11],
                                    ],
                                    c: false,
                                },
                                ix: 2,
                            },
                            nm: 'Path 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: false,
                        },
                        {
                            ty: 'st',
                            c: { a: 0, k: [0, 0, 0, 1], ix: 3 },
                            o: { a: 0, k: 100, ix: 4 },
                            w: { a: 0, k: 2, ix: 5 },
                            lc: 2,
                            lj: 2,
                            bm: 0,
                            nm: 'Stroke 1',
                            mn: 'ADBE Vector Graphic - Stroke',
                            hd: false,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [0, 0], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transform',
                        },
                    ],
                    nm: 'Group 1',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 1,
                    mn: 'ADBE Vector Group',
                    hd: false,
                },
                {
                    ty: 'tm',
                    s: {
                        a: 1,
                        k: [
                            { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 18, s: [0] },
                            { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 22, s: [0] },
                            { t: 25, s: [100] },
                        ],
                        ix: 1,
                    },
                    e: {
                        a: 1,
                        k: [
                            { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 18, s: [0] },
                            { t: 22, s: [100] },
                        ],
                        ix: 2,
                    },
                    o: { a: 0, k: 0, ix: 3 },
                    m: 1,
                    ix: 2,
                    nm: 'Trim Paths 1',
                    mn: 'ADBE Vector Filter - Trim',
                    hd: false,
                },
            ],
            ip: 0,
            op: 28,
            st: 0,
            bm: 0,
        },
        {
            ddd: 0,
            ind: 2,
            ty: 4,
            nm: 'hourglass Outlines',
            sr: 1,
            ks: {
                o: { a: 0, k: 100, ix: 11 },
                r: {
                    a: 1,
                    k: [
                        { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 3, s: [0] },
                        { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 5, s: [40] },
                        { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 9, s: [193] },
                        { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 11, s: [180] },
                        { t: 18, s: [180] },
                    ],
                    ix: 10,
                },
                p: { a: 0, k: [15, 15, 0], ix: 2 },
                a: { a: 0, k: [12, 16, 0], ix: 1 },
                s: {
                    a: 1,
                    k: [
                        {
                            i: { x: [0.667, 0.667, 0.667], y: [1, 1, 1] },
                            o: { x: [0.333, 0.333, 0.333], y: [0, 0, 0] },
                            t: 3,
                            s: [100, 100, 100],
                        },
                        {
                            i: { x: [0.667, 0.667, 0.667], y: [1, 1, 1] },
                            o: { x: [0.333, 0.333, 0.333], y: [0, 0, 0] },
                            t: 5,
                            s: [90, 90, 100],
                        },
                        {
                            i: { x: [0.667, 0.667, 0.667], y: [1, 1, 1] },
                            o: { x: [0.333, 0.333, 0.333], y: [0, 0, 0] },
                            t: 9,
                            s: [90, 90, 100],
                        },
                        {
                            i: { x: [0.667, 0.667, 0.667], y: [1, 1, 1] },
                            o: { x: [0.333, 0.333, 0.333], y: [0, 0, 0] },
                            t: 11,
                            s: [100, 100, 100],
                        },
                        { t: 18, s: [100, 100, 100] },
                    ],
                    ix: 6,
                },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 0,
                                k: {
                                    i: [
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    o: [
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    v: [
                                        [-7, -2],
                                        [7, -2],
                                        [7, 2],
                                        [-7, 2],
                                    ],
                                    c: true,
                                },
                                ix: 2,
                            },
                            nm: 'Path 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: false,
                        },
                        {
                            ty: 'fl',
                            c: { a: 0, k: [0, 0, 0, 1], ix: 4 },
                            o: { a: 0, k: 100, ix: 5 },
                            r: 1,
                            bm: 0,
                            nm: 'Fill 1',
                            mn: 'ADBE Vector Graphic - Fill',
                            hd: false,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [12, 25], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transform',
                        },
                    ],
                    nm: 'Group 1',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 1,
                    mn: 'ADBE Vector Group',
                    hd: false,
                },
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 0,
                                k: {
                                    i: [
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    o: [
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    v: [
                                        [-7, -2],
                                        [7, -2],
                                        [7, 2],
                                        [-7, 2],
                                    ],
                                    c: true,
                                },
                                ix: 2,
                            },
                            nm: 'Path 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: false,
                        },
                        {
                            ty: 'fl',
                            c: { a: 0, k: [0, 0, 0, 1], ix: 4 },
                            o: { a: 0, k: 100, ix: 5 },
                            r: 1,
                            bm: 0,
                            nm: 'Fill 1',
                            mn: 'ADBE Vector Graphic - Fill',
                            hd: false,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [12, 7], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transform',
                        },
                    ],
                    nm: 'Group 2',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 2,
                    mn: 'ADBE Vector Group',
                    hd: false,
                },
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 0,
                                k: {
                                    i: [
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                        [0, 5],
                                        [0, 0],
                                    ],
                                    o: [
                                        [0, 0],
                                        [0, -5],
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    v: [
                                        [2.5, 11],
                                        [2.5, 8],
                                        [-2.5, 0],
                                        [2.5, -8],
                                        [2.5, -11],
                                    ],
                                    c: false,
                                },
                                ix: 2,
                            },
                            nm: 'Path 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: false,
                        },
                        {
                            ty: 'st',
                            c: { a: 0, k: [0, 0, 0, 1], ix: 3 },
                            o: { a: 0, k: 100, ix: 4 },
                            w: { a: 0, k: 2, ix: 5 },
                            lc: 2,
                            lj: 2,
                            bm: 0,
                            nm: 'Stroke 1',
                            mn: 'ADBE Vector Graphic - Stroke',
                            hd: false,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [16.5, 16.001], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transform',
                        },
                    ],
                    nm: 'Group 3',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 3,
                    mn: 'ADBE Vector Group',
                    hd: false,
                },
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 0,
                                k: {
                                    i: [
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                        [0, -5],
                                        [0, 0],
                                    ],
                                    o: [
                                        [0, 0],
                                        [0, 5],
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    v: [
                                        [-2.5, -11],
                                        [-2.5, -8],
                                        [2.5, 0],
                                        [-2.5, 8],
                                        [-2.5, 11],
                                    ],
                                    c: false,
                                },
                                ix: 2,
                            },
                            nm: 'Path 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: false,
                        },
                        {
                            ty: 'st',
                            c: { a: 0, k: [0, 0, 0, 1], ix: 3 },
                            o: { a: 0, k: 100, ix: 4 },
                            w: { a: 0, k: 2, ix: 5 },
                            lc: 2,
                            lj: 2,
                            bm: 0,
                            nm: 'Stroke 1',
                            mn: 'ADBE Vector Graphic - Stroke',
                            hd: false,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [7.5, 16], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transform',
                        },
                    ],
                    nm: 'Group 4',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 4,
                    mn: 'ADBE Vector Group',
                    hd: false,
                },
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 0,
                                k: {
                                    i: [
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    o: [
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    v: [
                                        [3, 27.001],
                                        [21, 27.001],
                                    ],
                                    c: false,
                                },
                                ix: 2,
                            },
                            nm: 'Path 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: false,
                        },
                        {
                            ty: 'st',
                            c: { a: 0, k: [0, 0, 0, 1], ix: 3 },
                            o: { a: 0, k: 100, ix: 4 },
                            w: { a: 0, k: 2, ix: 5 },
                            lc: 2,
                            lj: 2,
                            bm: 0,
                            nm: 'Stroke 1',
                            mn: 'ADBE Vector Graphic - Stroke',
                            hd: false,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [0, 0], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transform',
                        },
                    ],
                    nm: 'Group 5',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 5,
                    mn: 'ADBE Vector Group',
                    hd: false,
                },
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 0,
                                k: {
                                    i: [
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    o: [
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    v: [
                                        [3, 5],
                                        [21, 5],
                                    ],
                                    c: false,
                                },
                                ix: 2,
                            },
                            nm: 'Path 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: false,
                        },
                        {
                            ty: 'st',
                            c: { a: 0, k: [0, 0, 0, 1], ix: 3 },
                            o: { a: 0, k: 100, ix: 4 },
                            w: { a: 0, k: 2, ix: 5 },
                            lc: 2,
                            lj: 2,
                            bm: 0,
                            nm: 'Stroke 1',
                            mn: 'ADBE Vector Graphic - Stroke',
                            hd: false,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [0, 0], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transform',
                        },
                    ],
                    nm: 'Group 6',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 6,
                    mn: 'ADBE Vector Group',
                    hd: false,
                },
            ],
            ip: 0,
            op: 28,
            st: 0,
            bm: 0,
        },
        {
            ddd: 0,
            ind: 3,
            ty: 4,
            nm: 'bottom shape',
            parent: 2,
            sr: 1,
            ks: {
                o: { a: 0, k: 100, ix: 11 },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [12, 21.594, 0], ix: 2 },
                a: { a: 0, k: [4.167, 1.844, 0], ix: 1 },
                s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 1,
                                k: [
                                    {
                                        i: { x: 0.833, y: 0.833 },
                                        o: { x: 0.167, y: 0.167 },
                                        t: 3,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [1.931, 0],
                                                    [0.376, -1.819],
                                                ],
                                                o: [
                                                    [-0.376, -1.819],
                                                    [-1.931, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [3.917, 1.594],
                                                    [0, -1.594],
                                                    [-3.917, 1.594],
                                                ],
                                                c: true,
                                            },
                                        ],
                                    },
                                    {
                                        i: { x: 0.833, y: 0.833 },
                                        o: { x: 0.167, y: 0.167 },
                                        t: 5,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [1.931, 0],
                                                    [0.376, -1.819],
                                                ],
                                                o: [
                                                    [-0.376, -1.819],
                                                    [-1.931, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [4.008, 2.243],
                                                    [0.091, -0.945],
                                                    [-3.826, 2.243],
                                                ],
                                                c: true,
                                            },
                                        ],
                                    },
                                    {
                                        i: { x: 0.833, y: 0.833 },
                                        o: { x: 0.167, y: 0.167 },
                                        t: 9,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [1.931, 0],
                                                    [0.376, -1.819],
                                                ],
                                                o: [
                                                    [-0.376, -1.819],
                                                    [-1.931, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [3.972, 0.541],
                                                    [0.055, -2.647],
                                                    [-3.862, 0.541],
                                                ],
                                                c: true,
                                            },
                                        ],
                                    },
                                    {
                                        i: { x: 0.833, y: 0.833 },
                                        o: { x: 0.167, y: 0.167 },
                                        t: 11,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [1.471, 0],
                                                    [0.286, -1.386],
                                                ],
                                                o: [
                                                    [-0.286, -1.386],
                                                    [-1.471, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [2.918, -0.656],
                                                    [-0.066, -3.085],
                                                    [-3.05, -0.656],
                                                ],
                                                c: true,
                                            },
                                        ],
                                    },
                                    {
                                        i: { x: 0.833, y: 0.833 },
                                        o: { x: 0.167, y: 0.167 },
                                        t: 20,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [1.471, 0],
                                                    [0.286, -1.386],
                                                ],
                                                o: [
                                                    [-0.286, -1.386],
                                                    [-1.471, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [2.918, -0.656],
                                                    [-0.066, -3.085],
                                                    [-3.05, -0.656],
                                                ],
                                                c: true,
                                            },
                                        ],
                                    },
                                    {
                                        t: 23,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [0.832, 0],
                                                    [0.162, -0.784],
                                                ],
                                                o: [
                                                    [-0.162, -0.784],
                                                    [-0.832, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [1.688, -1.991],
                                                    [0, -3.365],
                                                    [-1.688, -1.991],
                                                ],
                                                c: true,
                                            },
                                        ],
                                    },
                                ],
                                ix: 2,
                            },
                            nm: 'Path 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: false,
                        },
                        {
                            ty: 'fl',
                            c: { a: 0, k: [0, 0, 0, 1], ix: 4 },
                            o: { a: 0, k: 100, ix: 5 },
                            r: 1,
                            bm: 0,
                            nm: 'Fill 1',
                            mn: 'ADBE Vector Graphic - Fill',
                            hd: false,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [4.167, 1.844], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transform',
                        },
                    ],
                    nm: 'Group 1',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 1,
                    mn: 'ADBE Vector Group',
                    hd: false,
                },
            ],
            ip: 0,
            op: 23,
            st: 0,
            bm: 0,
        },
        {
            ddd: 0,
            ind: 4,
            ty: 4,
            nm: 'bottom shape2',
            sr: 1,
            ks: {
                o: { a: 0, k: 100, ix: 11 },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [15, 20.594, 0], ix: 2 },
                a: { a: 0, k: [4.167, 1.844, 0], ix: 1 },
                s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 1,
                                k: [
                                    {
                                        i: { x: 0.667, y: 1 },
                                        o: { x: 0.333, y: 0 },
                                        t: 22,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [0.678, 0],
                                                    [0.132, -0.639],
                                                ],
                                                o: [
                                                    [-0.132, -0.639],
                                                    [-0.678, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [1.375, 1.56],
                                                    [0, 0.44],
                                                    [-1.375, 1.56],
                                                ],
                                                c: true,
                                            },
                                        ],
                                    },
                                    {
                                        t: 25,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [1.931, 0],
                                                    [0.376, -1.819],
                                                ],
                                                o: [
                                                    [-0.376, -1.819],
                                                    [-1.931, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [3.917, 1.594],
                                                    [0, -1.594],
                                                    [-3.917, 1.594],
                                                ],
                                                c: true,
                                            },
                                        ],
                                    },
                                ],
                                ix: 2,
                            },
                            nm: 'Path 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: false,
                        },
                        {
                            ty: 'fl',
                            c: { a: 0, k: [0, 0, 0, 1], ix: 4 },
                            o: { a: 0, k: 100, ix: 5 },
                            r: 1,
                            bm: 0,
                            nm: 'Fill 1',
                            mn: 'ADBE Vector Graphic - Fill',
                            hd: false,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [4.167, 1.844], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transform',
                        },
                    ],
                    nm: 'Group 1',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 1,
                    mn: 'ADBE Vector Group',
                    hd: false,
                },
            ],
            ip: 22,
            op: 28,
            st: 0,
            bm: 0,
        },
    ],
    markers: [],
}

export const hourglassAnimationWhite = {
    nm: 'hourglass',
    h: 30,
    w: 30,
    meta: { g: '@lottiefiles/toolkit-js 0.33.2' },
    layers: [
        {
            ty: 4,
            nm: 'middle Outlines',
            sr: 1,
            st: 0,
            op: 28,
            ip: 0,
            hasMask: false,
            ao: 0,
            ks: {
                a: { a: 0, k: [1, 5.5, 0] },
                s: { a: 0, k: [100, 100, 100] },
                sk: { a: 0, k: 0 },
                p: { a: 0, k: [15, 15.5, 0] },
                r: { a: 0, k: 0 },
                sa: { a: 0, k: 0 },
                o: { a: 0, k: 100 },
            },
            ef: [],
            shapes: [
                {
                    ty: 'gr',
                    nm: 'Group 1',
                    it: [
                        {
                            ty: 'sh',
                            nm: 'Path 1',
                            d: 1,
                            ks: {
                                a: 0,
                                k: {
                                    c: false,
                                    i: [
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    o: [
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    v: [
                                        [1, 2.188],
                                        [1, 11],
                                    ],
                                },
                            },
                        },
                        {
                            ty: 'st',
                            nm: 'Stroke 1',
                            lc: 2,
                            lj: 2,
                            ml: 1,
                            o: { a: 0, k: 100 },
                            w: { a: 0, k: 2 },
                            c: { a: 0, k: [1, 1, 1] },
                        },
                        {
                            ty: 'tr',
                            a: { a: 0, k: [0, 0] },
                            s: { a: 0, k: [100, 100] },
                            sk: { a: 0, k: 0 },
                            p: { a: 0, k: [0, 0] },
                            r: { a: 0, k: 0 },
                            sa: { a: 0, k: 0 },
                            o: { a: 0, k: 100 },
                        },
                    ],
                },
                {
                    ty: 'tm',
                    nm: 'Trim Paths 1',
                    e: {
                        a: 1,
                        k: [
                            { o: { x: 0.333, y: 0 }, i: { x: 0.667, y: 1 }, s: [0], t: 18 },
                            { s: [100], t: 22 },
                        ],
                    },
                    o: { a: 0, k: 0 },
                    s: {
                        a: 1,
                        k: [
                            { o: { x: 0.333, y: 0 }, i: { x: 0.667, y: 1 }, s: [0], t: 18 },
                            { o: { x: 0.333, y: 0 }, i: { x: 0.667, y: 1 }, s: [0], t: 22 },
                            { s: [100], t: 25 },
                        ],
                    },
                    m: 1,
                },
            ],
            ind: 1,
        },
        {
            ty: 4,
            nm: 'hourglass Outlines',
            sr: 1,
            st: 0,
            op: 28,
            ip: 0,
            hasMask: false,
            ao: 0,
            ks: {
                a: { a: 0, k: [12, 16, 0] },
                s: {
                    a: 1,
                    k: [
                        { o: { x: 0.333, y: 0 }, i: { x: 0.667, y: 1 }, s: [100, 100, 100], t: 3 },
                        { o: { x: 0.333, y: 0 }, i: { x: 0.667, y: 1 }, s: [90, 90, 100], t: 5 },
                        { o: { x: 0.333, y: 0 }, i: { x: 0.667, y: 1 }, s: [90, 90, 100], t: 9 },
                        { o: { x: 0.333, y: 0 }, i: { x: 0.667, y: 1 }, s: [100, 100, 100], t: 11 },
                        { s: [100, 100, 100], t: 18 },
                    ],
                },
                sk: { a: 0, k: 0 },
                p: { a: 0, k: [15, 15, 0] },
                r: {
                    a: 1,
                    k: [
                        { o: { x: 0.333, y: 0 }, i: { x: 0.667, y: 1 }, s: [0], t: 3 },
                        { o: { x: 0.333, y: 0 }, i: { x: 0.667, y: 1 }, s: [40], t: 5 },
                        { o: { x: 0.333, y: 0 }, i: { x: 0.667, y: 1 }, s: [193], t: 9 },
                        { o: { x: 0.333, y: 0 }, i: { x: 0.667, y: 1 }, s: [180], t: 11 },
                        { s: [180], t: 18 },
                    ],
                },
                sa: { a: 0, k: 0 },
                o: { a: 0, k: 100 },
            },
            ef: [],
            shapes: [
                {
                    ty: 'gr',
                    nm: 'Group 1',
                    it: [
                        {
                            ty: 'sh',
                            nm: 'Path 1',
                            d: 1,
                            ks: {
                                a: 0,
                                k: {
                                    c: true,
                                    i: [
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    o: [
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    v: [
                                        [-7, -2],
                                        [7, -2],
                                        [7, 2],
                                        [-7, 2],
                                    ],
                                },
                            },
                        },
                        { ty: 'fl', nm: 'Fill 1', c: { a: 0, k: [1, 1, 1] }, r: 1, o: { a: 0, k: 100 } },
                        {
                            ty: 'tr',
                            a: { a: 0, k: [0, 0] },
                            s: { a: 0, k: [100, 100] },
                            sk: { a: 0, k: 0 },
                            p: { a: 0, k: [12, 25] },
                            r: { a: 0, k: 0 },
                            sa: { a: 0, k: 0 },
                            o: { a: 0, k: 100 },
                        },
                    ],
                },
                {
                    ty: 'gr',
                    nm: 'Group 2',
                    it: [
                        {
                            ty: 'sh',
                            nm: 'Path 1',
                            d: 1,
                            ks: {
                                a: 0,
                                k: {
                                    c: true,
                                    i: [
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    o: [
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    v: [
                                        [-7, -2],
                                        [7, -2],
                                        [7, 2],
                                        [-7, 2],
                                    ],
                                },
                            },
                        },
                        { ty: 'fl', nm: 'Fill 1', c: { a: 0, k: [1, 1, 1] }, r: 1, o: { a: 0, k: 100 } },
                        {
                            ty: 'tr',
                            a: { a: 0, k: [0, 0] },
                            s: { a: 0, k: [100, 100] },
                            sk: { a: 0, k: 0 },
                            p: { a: 0, k: [12, 7] },
                            r: { a: 0, k: 0 },
                            sa: { a: 0, k: 0 },
                            o: { a: 0, k: 100 },
                        },
                    ],
                },
                {
                    ty: 'gr',
                    nm: 'Group 3',
                    it: [
                        {
                            ty: 'sh',
                            nm: 'Path 1',
                            d: 1,
                            ks: {
                                a: 0,
                                k: {
                                    c: false,
                                    i: [
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                        [0, 5],
                                        [0, 0],
                                    ],
                                    o: [
                                        [0, 0],
                                        [0, -5],
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    v: [
                                        [2.5, 11],
                                        [2.5, 8],
                                        [-2.5, 0],
                                        [2.5, -8],
                                        [2.5, -11],
                                    ],
                                },
                            },
                        },
                        {
                            ty: 'st',
                            nm: 'Stroke 1',
                            lc: 2,
                            lj: 2,
                            ml: 1,
                            o: { a: 0, k: 100 },
                            w: { a: 0, k: 2 },
                            c: { a: 0, k: [1, 1, 1] },
                        },
                        {
                            ty: 'tr',
                            a: { a: 0, k: [0, 0] },
                            s: { a: 0, k: [100, 100] },
                            sk: { a: 0, k: 0 },
                            p: { a: 0, k: [16.5, 16.001] },
                            r: { a: 0, k: 0 },
                            sa: { a: 0, k: 0 },
                            o: { a: 0, k: 100 },
                        },
                    ],
                },
                {
                    ty: 'gr',
                    nm: 'Group 4',
                    it: [
                        {
                            ty: 'sh',
                            nm: 'Path 1',
                            d: 1,
                            ks: {
                                a: 0,
                                k: {
                                    c: false,
                                    i: [
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                        [0, -5],
                                        [0, 0],
                                    ],
                                    o: [
                                        [0, 0],
                                        [0, 5],
                                        [0, 0],
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    v: [
                                        [-2.5, -11],
                                        [-2.5, -8],
                                        [2.5, 0],
                                        [-2.5, 8],
                                        [-2.5, 11],
                                    ],
                                },
                            },
                        },
                        {
                            ty: 'st',
                            nm: 'Stroke 1',
                            lc: 2,
                            lj: 2,
                            ml: 1,
                            o: { a: 0, k: 100 },
                            w: { a: 0, k: 2 },
                            c: { a: 0, k: [1, 1, 1] },
                        },
                        {
                            ty: 'tr',
                            a: { a: 0, k: [0, 0] },
                            s: { a: 0, k: [100, 100] },
                            sk: { a: 0, k: 0 },
                            p: { a: 0, k: [7.5, 16] },
                            r: { a: 0, k: 0 },
                            sa: { a: 0, k: 0 },
                            o: { a: 0, k: 100 },
                        },
                    ],
                },
                {
                    ty: 'gr',
                    nm: 'Group 5',
                    it: [
                        {
                            ty: 'sh',
                            nm: 'Path 1',
                            d: 1,
                            ks: {
                                a: 0,
                                k: {
                                    c: false,
                                    i: [
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    o: [
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    v: [
                                        [3, 27.001],
                                        [21, 27.001],
                                    ],
                                },
                            },
                        },
                        {
                            ty: 'st',
                            nm: 'Stroke 1',
                            lc: 2,
                            lj: 2,
                            ml: 1,
                            o: { a: 0, k: 100 },
                            w: { a: 0, k: 2 },
                            c: { a: 0, k: [1, 1, 1] },
                        },
                        {
                            ty: 'tr',
                            a: { a: 0, k: [0, 0] },
                            s: { a: 0, k: [100, 100] },
                            sk: { a: 0, k: 0 },
                            p: { a: 0, k: [0, 0] },
                            r: { a: 0, k: 0 },
                            sa: { a: 0, k: 0 },
                            o: { a: 0, k: 100 },
                        },
                    ],
                },
                {
                    ty: 'gr',
                    nm: 'Group 6',
                    it: [
                        {
                            ty: 'sh',
                            nm: 'Path 1',
                            d: 1,
                            ks: {
                                a: 0,
                                k: {
                                    c: false,
                                    i: [
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    o: [
                                        [0, 0],
                                        [0, 0],
                                    ],
                                    v: [
                                        [3, 5],
                                        [21, 5],
                                    ],
                                },
                            },
                        },
                        {
                            ty: 'st',
                            nm: 'Stroke 1',
                            lc: 2,
                            lj: 2,
                            ml: 1,
                            o: { a: 0, k: 100 },
                            w: { a: 0, k: 2 },
                            c: { a: 0, k: [1, 1, 1] },
                        },
                        {
                            ty: 'tr',
                            a: { a: 0, k: [0, 0] },
                            s: { a: 0, k: [100, 100] },
                            sk: { a: 0, k: 0 },
                            p: { a: 0, k: [0, 0] },
                            r: { a: 0, k: 0 },
                            sa: { a: 0, k: 0 },
                            o: { a: 0, k: 100 },
                        },
                    ],
                },
            ],
            ind: 2,
        },
        {
            ty: 4,
            nm: 'bottom shape',
            sr: 1,
            st: 0,
            op: 23,
            ip: 0,
            hasMask: false,
            ao: 0,
            ks: {
                a: { a: 0, k: [4.167, 1.844, 0] },
                s: { a: 0, k: [100, 100, 100] },
                sk: { a: 0, k: 0 },
                p: { a: 0, k: [12, 21.594, 0] },
                r: { a: 0, k: 0 },
                sa: { a: 0, k: 0 },
                o: { a: 0, k: 100 },
            },
            ef: [],
            shapes: [
                {
                    ty: 'gr',
                    nm: 'Group 1',
                    it: [
                        {
                            ty: 'sh',
                            nm: 'Path 1',
                            d: 1,
                            ks: {
                                a: 1,
                                k: [
                                    {
                                        o: { x: 0.167, y: 0.167 },
                                        i: { x: 0.833, y: 0.833 },
                                        s: [
                                            {
                                                c: true,
                                                i: [
                                                    [0, 0],
                                                    [1.931, 0],
                                                    [0.376, -1.819],
                                                ],
                                                o: [
                                                    [-0.376, -1.819],
                                                    [-1.931, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [3.917, 1.594],
                                                    [0, -1.594],
                                                    [-3.917, 1.594],
                                                ],
                                            },
                                        ],
                                        t: 3,
                                    },
                                    {
                                        o: { x: 0.167, y: 0.167 },
                                        i: { x: 0.833, y: 0.833 },
                                        s: [
                                            {
                                                c: true,
                                                i: [
                                                    [0, 0],
                                                    [1.931, 0],
                                                    [0.376, -1.819],
                                                ],
                                                o: [
                                                    [-0.376, -1.819],
                                                    [-1.931, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [4.008, 2.243],
                                                    [0.091, -0.945],
                                                    [-3.826, 2.243],
                                                ],
                                            },
                                        ],
                                        t: 5,
                                    },
                                    {
                                        o: { x: 0.167, y: 0.167 },
                                        i: { x: 0.833, y: 0.833 },
                                        s: [
                                            {
                                                c: true,
                                                i: [
                                                    [0, 0],
                                                    [1.931, 0],
                                                    [0.376, -1.819],
                                                ],
                                                o: [
                                                    [-0.376, -1.819],
                                                    [-1.931, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [3.972, 0.541],
                                                    [0.055, -2.647],
                                                    [-3.862, 0.541],
                                                ],
                                            },
                                        ],
                                        t: 9,
                                    },
                                    {
                                        o: { x: 0.167, y: 0.167 },
                                        i: { x: 0.833, y: 0.833 },
                                        s: [
                                            {
                                                c: true,
                                                i: [
                                                    [0, 0],
                                                    [1.471, 0],
                                                    [0.286, -1.386],
                                                ],
                                                o: [
                                                    [-0.286, -1.386],
                                                    [-1.471, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [2.918, -0.656],
                                                    [-0.066, -3.085],
                                                    [-3.05, -0.656],
                                                ],
                                            },
                                        ],
                                        t: 11,
                                    },
                                    {
                                        o: { x: 0.167, y: 0.167 },
                                        i: { x: 0.833, y: 0.833 },
                                        s: [
                                            {
                                                c: true,
                                                i: [
                                                    [0, 0],
                                                    [1.471, 0],
                                                    [0.286, -1.386],
                                                ],
                                                o: [
                                                    [-0.286, -1.386],
                                                    [-1.471, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [2.918, -0.656],
                                                    [-0.066, -3.085],
                                                    [-3.05, -0.656],
                                                ],
                                            },
                                        ],
                                        t: 20,
                                    },
                                    {
                                        s: [
                                            {
                                                c: true,
                                                i: [
                                                    [0, 0],
                                                    [0.832, 0],
                                                    [0.162, -0.784],
                                                ],
                                                o: [
                                                    [-0.162, -0.784],
                                                    [-0.832, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [1.688, -1.991],
                                                    [0, -3.365],
                                                    [-1.688, -1.991],
                                                ],
                                            },
                                        ],
                                        t: 23,
                                    },
                                ],
                            },
                        },
                        { ty: 'fl', nm: 'Fill 1', c: { a: 0, k: [1, 1, 1] }, r: 1, o: { a: 0, k: 100 } },
                        {
                            ty: 'tr',
                            a: { a: 0, k: [0, 0] },
                            s: { a: 0, k: [100, 100] },
                            sk: { a: 0, k: 0 },
                            p: { a: 0, k: [4.167, 1.844] },
                            r: { a: 0, k: 0 },
                            sa: { a: 0, k: 0 },
                            o: { a: 0, k: 100 },
                        },
                    ],
                },
            ],
            ind: 3,
            parent: 2,
        },
        {
            ty: 4,
            nm: 'bottom shape2',
            sr: 1,
            st: 0,
            op: 28,
            ip: 22,
            hasMask: false,
            ao: 0,
            ks: {
                a: { a: 0, k: [4.167, 1.844, 0] },
                s: { a: 0, k: [100, 100, 100] },
                sk: { a: 0, k: 0 },
                p: { a: 0, k: [15, 20.594, 0] },
                r: { a: 0, k: 0 },
                sa: { a: 0, k: 0 },
                o: { a: 0, k: 100 },
            },
            ef: [],
            shapes: [
                {
                    ty: 'gr',
                    nm: 'Group 1',
                    it: [
                        {
                            ty: 'sh',
                            nm: 'Path 1',
                            d: 1,
                            ks: {
                                a: 1,
                                k: [
                                    {
                                        o: { x: 0.333, y: 0 },
                                        i: { x: 0.667, y: 1 },
                                        s: [
                                            {
                                                c: true,
                                                i: [
                                                    [0, 0],
                                                    [0.678, 0],
                                                    [0.132, -0.639],
                                                ],
                                                o: [
                                                    [-0.132, -0.639],
                                                    [-0.678, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [1.375, 1.56],
                                                    [0, 0.44],
                                                    [-1.375, 1.56],
                                                ],
                                            },
                                        ],
                                        t: 22,
                                    },
                                    {
                                        s: [
                                            {
                                                c: true,
                                                i: [
                                                    [0, 0],
                                                    [1.931, 0],
                                                    [0.376, -1.819],
                                                ],
                                                o: [
                                                    [-0.376, -1.819],
                                                    [-1.931, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [3.917, 1.594],
                                                    [0, -1.594],
                                                    [-3.917, 1.594],
                                                ],
                                            },
                                        ],
                                        t: 25,
                                    },
                                ],
                            },
                        },
                        { ty: 'fl', nm: 'Fill 1', c: { a: 0, k: [1, 1, 1] }, r: 1, o: { a: 0, k: 100 } },
                        {
                            ty: 'tr',
                            a: { a: 0, k: [0, 0] },
                            s: { a: 0, k: [100, 100] },
                            sk: { a: 0, k: 0 },
                            p: { a: 0, k: [4.167, 1.844] },
                            r: { a: 0, k: 0 },
                            sa: { a: 0, k: 0 },
                            o: { a: 0, k: 100 },
                        },
                    ],
                },
            ],
            ind: 4,
        },
    ],
    v: '5.6.5',
    fr: 24,
    op: 28,
    ip: 0,
    assets: [],
}
