name: Spell Checker

on:
    - pull_request

jobs:
    spell-check:
        name: Spell Checker
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install codespell with pip
              run: |
                  python -m pip install -U pip
                  python -m pip install git+https://github.com/yakkomajuri/codespell.git

            - name: Correct spelling
              run: |
                  codespell ./contents -w -S "./contents/images/*,./contents/docs/_media/*" -q 8 -I ./.codespellignore
                  git config user.name PostHog Bot
                  git config user.email hey@posthog.com
                  git add .
                  [ "$(git status -s)" = "" ] && exit 0 || git commit -m "Fix typos" && git push
