name: Spell Checker

on:
    - pull_request

jobs:
    spell-check:
        name: Spell Checker
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.base_ref }}

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install Python dependencies with pip
              run: |
                  python -m pip install -U pip
                  python -m pip install codespell

            - name: Correct spelling
              run: |
                  codespell ./contents -w -S "./contents/images/*,./contents/docs/_media/*" -q 8
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add .
                  git commit -m "Fix typos"
                  git push
