name: Spell Checker

on:
    - pull_request

jobs:
    spell-check:
        name: Spell Checker
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install Python dependencies with pip
              run: |
                  python -m pip install -U pip
                  python -m pip install codespell

            - name: Correct spelling
              run: |
                  codespell ./contents -S "images/*"
